### ISSUE TITLE
Can't see profile bio in light theme

### ISSUE THREAD

**Issue by greenart7c3** [vitorpamplona/amethyst#1]
![Screenshot_20230118-190638.png](https://user-images.githubusercontent.com/115044884/213305883-1630c14c-561e-48c0-b5ef-7773ddf46630.png)

![Screenshot_20230118-190627.png](https://user-images.githubusercontent.com/115044884/213305919-8500f8a0-0d6e-4dae-a82c-6be488714ccd.png)

**Comment by vitorpamplona** [comment]
Awesome! Thank you! 

Fixed on https://github.com/vitorpamplona/amethyst/commit/ce4e3e6589acd59e8f57a489fe3cf993e5bfe9b7

**Comment by manakill** [comment]
Where is the dark mode setting?

**Comment by vitorpamplona** [comment]
It follows the mode on the phone.
