### ISSUE TITLE
In "New Threads" view, treat subsequent 'reposts' as already seen when scrolling through content

### ISSUE THREAD

**Issue by coinzdude** [vitorpamplona/amethyst#100]
currently multiple reposts of popular posts shows up repeatedly in the New Threads view, like this one note155sxarv8564zh79tjwvespcv7c3jfwjppqe4w0ysfr0e6dte28xsmjzsdl

Is it feasible to detect these have already been shown and skip reposts?

**Comment by bitcoinuser** [comment]
I would like to see something like this too. Maybe do not show reposts if the same post is on the last 20 messages on user feed.

**Comment by vitorpamplona** [comment]
We now only show if they are sufficiently far away from each other 100 posts or 1 day.
