### ISSUE TITLE
Multiple reactions

### ISSUE THREAD

**Issue by freemyminde** [vitorpamplona/amethyst#1010]
https://github.com/user-attachments/assets/b31c0c18-d681-4bfc-8587-27ce90ff0320

**Describe the bug**
I assume that a user should be able to leave one emoji-reaction (like in other socialmedia) per post. So that when there are 100 reactions 100 people reacted to it.
Currently I am able to give kind of infinit amount of emoji-reactions.

**To Reproduce**
1. Go to any post
2. Click on heart symbol and select a emoji
3. Click on heart symbol again and select a new emoji
4. Result: post has two reactions now.

**Expected behavior**
I can select one emoji. And when I select another then it should switch to this one and not add to it.

**Video and Screenshots**
If applicable, add a video and/or screenshots to help explain your problem.

**Device (please complete the following information):**
 - Phone Brand/Model: Pixel 6a
 - Android Version: android 14 graphene build 2024080600
 - App Version: 0.89.8

**Comment by davotoula** [comment]
Have you noticed that you can deselect a previous reaction?

The way it is designed makes it possible to leave just one emoji... Or multiple.

**Comment by freemyminde** [comment]
Yes this I have noticed. But to me this seems unintuitive. Shouldn't the number of reactions be an espression of how many users react to a post? Similar to a like button to display a posts popularity.?

**Comment by davotoula** [comment]
To be honest I haven't checked the nostr protocol around reactions.

But I suspect it's a flexible modern protocol that allows flexibility like this and nostr clients take advantage of using it?

Nostr is not about replicating traditional social media, it's a new experience.

**Comment by davotoula** [comment]
Also note that it's free and easy to create thousands of "accounts" and like posts.

Reactions are ultimately not a measure of "how many actual people have liked" something.

**Comment by freemyminde** [comment]
Yes but this is kind of true of most socialmedia. I just state that this is an issue. And if there is no good solution to show popularity. How would you find popular posts?

**Comment by freemyminde** [comment]
Thank you very much for the discussion. Then probably zaps are rather the real likes, since they are at least bond to value. 

I think I know more now. And for me this issue can be closed when no further questions to this topic come up.

**Comment by davotoula** [comment]
Please close this issue if it is not required anymore
