### ISSUE TITLE
How to create a long-form text content (NIP-23, Kind 30023, Kind 30024) event?

### ISSUE THREAD

**Issue by GitKalle** [vitorpamplona/amethyst#1014]
I would like to create a long-form text content (NIP-23, Kind 30023, Kind 30024) event but I don't know how. During my research I found the issue #295 but no help how to create that event. Maybe @gzuuus can help.

**Comment by vitorpamplona** [comment]
Yes, we render the event on the feed and if you search it should show up as well.
