### ISSUE TITLE
[SUGGESTION] PoW displayed as higher than the target

### ISSUE THREAD

**Issue by Czino** [vitorpamplona/amethyst#1021]
**Describe the bug**
I've been playing around with PoW and set my target to 25. I did however hit a post with level 26. Amethyst is displaying it as PoW 26, as well. 

**Expected behavior**
But I would suggest since the target was set to 25, it should be displayed as such. Since NIP-13 already suggests to make use of it to reject posts with a target lower than your set threshold for filtering. UX might want to align with that.

**Example in the wild**
![image](https://github.com/user-attachments/assets/857815ff-f535-421c-ae69-083e47dc755c)

[pow-25-post-with-26-hit.json](https://github.com/user-attachments/files/16674174/pow-25-post-with-26-hit.json)

**Comment by vitorpamplona** [comment]
Solved:https://github.com/vitorpamplona/amethyst/commit/17c758f8f86903ed49ca1bec663c664b5ff4e3f3
