### ISSUE TITLE
Slight issue with BookmarkListEvent

### ISSUE THREAD

**Issue by KotlinGeekDev** [vitorpamplona/amethyst#1023]
While looking at the BookmarkListEvent source code, I noticed that the kind used is 30,001. However, after looking at specs, it seems that it's supposed to be either kind 10,003 or 30,003(?).
So I don't know which kind to use, to fix it.
Thanks for reading.

**Comment by vitorpamplona** [comment]
We have to migrate all current posts to 10003, since we don't have labeled bookmarks groups yet.

**Comment by KotlinGeekDev** [comment]
> We have to migrate all current posts to 10003, since we don't have labeled bookmarks groups yet.

I see. So does it mean that the fix to #815 should cover this?

**Comment by vitorpamplona** [comment]
Yeah, but I would focus first on lists of pubkeys. Then you can copy the infrastructure to work with posts as well. List of pubkeys is already a massive amount of work.

**Comment by KotlinGeekDev** [comment]
> Yeah, but I would focus first on lists of pubkeys. Then you can copy the infrastructure to work with posts as well. List of pubkeys is already a massive amount of work.

Got it. Closing issue then as it a subset of #815 .
