### ISSUE TITLE
[BUG] Tor setting reset to off after switching away in Amethyst version > 0.90.x

### ISSUE THREAD

**Issue by markwaters** [vitorpamplona/amethyst#1037]
**Describe the bug**
Tor setting reset to off after switching away in Amethyst version > 0.90.x
If you upgrade from 0.89.x to 0.90.x with Tor already enabled then Tor stays enabled.

**To Reproduce**
Steps to reproduce the behaviour:
1. Enable Tor , Save
2. Switch to another app , Kill Amethyst or remove from recent apps.
3. Open Amethyst
4. Tor no longer enabled.

**Expected behaviour**
Tor should remain enabled until disabled.

**Device (please complete the following information):**
 - Pixel 7 
 - GrapheneOS 2024082200
 - Amethyst 0.90.x onwards

**Comment by vitorpamplona** [comment]
I believe 0.90.5 fixed this. Can you folks try?

**Comment by davotoula** [comment]
Works for me. Also the tor checkbox is back on login screen.

**Comment by markwaters** [comment]
Working perfectly now , thank you both.
