### ISSUE TITLE
[BUG] Profile Lightning payment is 100x too large

### ISSUE THREAD

**Issue by markwaters** [vitorpamplona/amethyst#1038]
**Describe the bug**
Profile Lightning payment is 100x too large.

**To Reproduce**
Steps to reproduce the behaviour:
1. Open a users profile in Amethyst.
2. Click on their lightning address.
3. A box pops up with a default zap amount of 1000 sats
4. Not using NWC , so wallet opens with a payment page ready to send 1,000,000 sats (!) , if I try to send 47 sats the wallet page shows 47,000 sats.

**Expected behaviour**
Sats amount to be correct.

**Device (please complete the following information):**
 - Pixel 7.
 - GrapheneOS.
 - 0.90.4-fdroid.

**Comment by davotoula** [comment]
Reproduced in Google play version

**Comment by davotoula** [comment]
Found the issue, fixing

**Comment by davotoula** [comment]
What wallet supplier did the user use?

Does it happen every time for you or just certain users?

**Comment by markwaters** [comment]
It happens for me using minibits and phoenix wallets.

I only tried two different user accounts and it happened identically for both.

**Comment by davotoula** [comment]
Seems like a minor fix only. Hopefully @vitorpamplona will review and find no other side issues 👍

**Comment by markwaters** [comment]
Thanks for your work on Amethyst @davotoula

**Comment by davotoula** [comment]
All the credit goes to @vitorpamplona. Amazing project he runs.

**Comment by davotoula** [comment]
Please close if resolved

**Comment by markwaters** [comment]
Confirmed. Fixed. Thank you.
