### ISSUE TITLE
[FEATURE] Cache user profile or DM list

### ISSUE THREAD

**Issue by kehiy** [vitorpamplona/amethyst#1048]
**Is your feature request related to a problem? Please describe.**

When we open the app, all of my own account information is defaulted!!!
I have to wait for data to be fetched.

**Describe the solution you'd like**

The client can cache my last metadata and show it first. then in the background, it can fetch a new kind-0 and replace it, if it's new.

**Additional context**

This makes a better user experience and the user feels using a more reliable platform.

**Comment by vitorpamplona** [comment]
Hum.. I am not sure what you mean by "defaulted". 

Amethyst does store your kind 0 locally. So, your name should be there. 

Images and videos on the profile though can be deleted based on the disk availability.

**Comment by kehiy** [comment]
@vitorpamplona Name is there, but the profile is defaulte. We should not keep image URL. Maybe cache image as well. it worths.

**Comment by vitorpamplona** [comment]
hum... the image itself is cached in the disk. How long does it take to load? Sometimes the disk access is quite slow.

**Comment by kehiy** [comment]
around 6-7 seconds this time!
