### ISSUE TITLE
Feature request: Do not auto-translate language XY

### ISSUE THREAD

**Issue by dergigi** [vitorpamplona/amethyst#105]
People that speak multiple language probably don't want to have the languages that they speak auto-translated to English.

A settings screen in the spirit of "Do not translate the following languages: " would probably do it.

**Comment by vitorpamplona** [comment]
Other than this? https://nostr.build/av/nostr.build_e5286525acb00c94606035ab951f5c2cc28aac1418bc5521deb050a3f170199a.mp4

It was released yesterday.

**Comment by dergigi** [comment]
Oh snap! That's perfect! Thank you! 💜
