### ISSUE TITLE
[BUG] NIP-05 verified profile shows red exclamation mark

### ISSUE THREAD

**Issue by neudabei** [vitorpamplona/amethyst#1055]
**Describe the bug**
The Android app shows profiles as not verified, when they do on other nostr apps. 

**To Reproduce**
1. Go to user profile of npub1vppdwqmhlzhftstq5exturmry4u0pdfm93mqj4zfuuznhclxygfsdatk8w
2. See a red exclamation mark next to the identifier address.

**Expected behavior**
The user should have a checkmark on their profile as other verified profiles (see screenshots).
Compare to https://coracle.social/npub1vppdwqmhlzhftstq5exturmry4u0pdfm93mqj4zfuuznhclxygfsdatk8w or the same account on Primal. On both apps the the user is shown as verified.

The identifier robert@cosanostr.com is backed up by the NIP-05 compliant implementation on [cosanostr.com/.well-known/nostr.json](https://www.cosanostr.com/.well-known/nostr.json?name=robert)

**Video and Screenshots**
![7a3346c3-3cf4-4fea-aebf-590decb8da04 Screenshot_20240905_103107_Amethyst](https://github.com/user-attachments/assets/84445e2c-1a18-4464-a47d-454b8ad1bca1)
![5b3b9f5c-6d93-48fd-8d6d-929578d7e6ec Screenshot_20240905_102952_Amethyst](https://github.com/user-attachments/assets/ae3bbb2c-800e-4198-b39d-fe992b1db9de)

**Device (please complete the following information):**
 - Android Version [e.g. 33]:v0.89.10-PLAY

**Comment by davotoula** [comment]
I'm looking into this

**Comment by davotoula** [comment]
It looks like a global redirect from cosanostr.com _www_.cosanostr.com.

NIP-05 specifically forbids any redirects.

Solutions:

- Exclude /.well-known/nostr.json from the redirect
or
- Add www. prefix to Nostr Address in Amethyst profile

**Comment by davotoula** [comment]
Feel free to ask any other questions of close if not an amethyst issue

**Comment by neudabei** [comment]
Thank you @davotoula I will try to disable the redirect.

**Comment by KotlinGeekDev** [comment]
> Thank you @davotoula I disabled the redirect.

Nice! I think the issue can be closed then, @neudabei if the fix works. :)

**Comment by neudabei** [comment]
Removing the redirect works 🎉 Thanks for your help!
