### ISSUE TITLE
[Request]   Multi-language support for UI

### ISSUE THREAD

**Issue by webcreazy** [vitorpamplona/amethyst#107]

**Comment by webcreazy** [comment]
we can use transifex like Damus app
![图片](https://user-images.githubusercontent.com/14907173/219557854-eb091ebf-d89b-482e-808d-19eb3a830177.png)

**Comment by Inwises** [comment]
Victor expressed his intention in the group that he needed native speakers to help accurately translate the project

**Comment by chiajlingvoj** [comment]
We can already translate the strings.xml file to provide translations for the UI, this request is kind of connected to #298 though...

**Comment by vitorpamplona** [comment]
We use crowdin: https://crowdin.com/project/amethyst-social
