### ISSUE TITLE
[BUG] Edit draft button is not functional

### ISSUE THREAD

**Issue by dtonon** [vitorpamplona/amethyst#1070]
**Describe the bug**
The "Edit draft" button you find after a long press on a draft, does nothing.

**To Reproduce**
1. Start replying to note;
2. Exit the draft;
3. Long press the draft;
4. Choose "Edit draft";

**Expected behavior**
The user should be taken to the draft window.

**Device (please complete the following information):**
 - Pixel 7a
 - Android Version 14
 - App Version v0.91.0-PLAY

**Comment by dtonon** [comment]
@vitorpamplona @greenart7c3 the problem is still present in v1.00.5.

**Comment by vitorpamplona** [comment]
Found the issue. Wrong nav param was being passed down
