### ISSUE TITLE
[BUG] Security settings (blocks, filters) not loaded with multiple accounts

### ISSUE THREAD

**Issue by maridonkers** [vitorpamplona/amethyst#1073]
When multiple accounts are configured then security settings are often not loaded and not activated for the additional accounts

1. Configure several accounts
2. Select a 'not the first' account
3. Do stuff, browse around in notes, etc. Block some users, ad filters.
4. View Security in menu to verify it has your block list and filters
5. Close Amethyst and remove from recent apps
6. Open Amethyst again
7. Check Security in menu: now often block list is empty and filters too (intermittent – sometimes flushing cache  restores security info; remove and re-add account apparently always restore info).

Expected behavior
Security info, such as block list and filters per account and always loaded and activated for all accounts.

Device
 - Phone Brand/Model: Samsung M13 5G model
 - Android Version: 14
 - App Version [e.g. v0.20.3]: v0.89.10-fdroid (also play store version)

**Comment by vitorpamplona** [comment]
Not really. Security settings is per account. We can make it easier to copy blocks for all the other accounts, but they have to be signed as each account and go to each account relay set.

**Comment by maridonkers** [comment]
It no longer occurs so closing this.
