### ISSUE TITLE
[Request] Ask for confirmation before liking or boosting a note.

### ISSUE THREAD

**Issue by sopans** [vitorpamplona/amethyst#110]
I see people talking about this, so I added an issue.
Since you can't delete or undo any posts.

**Comment by sopans** [comment]
boosting already talked about in #21

**Comment by murdawkmedia** [comment]
I like this idea - but it should be up to the user. Kind of like an 'only once ' or 'never ask again' prompt.

**Comment by anton-isidore** [comment]
Btw, why the boost or like cannot be undone. The protocol is not supporting it? Why? I think technically it should be possible.

**Comment by vitorpamplona** [comment]
It's like sending an email. Once you hit send, the email is in many servers and other clients already. Even if you ask servers to remove, there is no guarantee relays or clients will delete.

**Comment by anton-isidore** [comment]
@vitorpamplona yes, I understand, but I can send another email (Nostr event) saying, this (reference to the boost) is undone.

Yes, its not 100% guaranteed all clients implement this, and its not 100% guaranteed that they got the message, but thats also case for any Nostr event.

Everything in distributed system is only **eventually consistent**.

**Comment by vitorpamplona** [comment]
Sure, but from a UI perspective, it's going to get real confusing if people think they have deleted something just to see it coming back later. I am not sure how to make this super clear.

**Comment by anton-isidore** [comment]
What do you mean? Local version of data will be consistent (retweet was undone). No confusion there. Rest of the network may see this with delay or never (so it will display the boost). 

Its not wrong, its just that information about the state is not distributed evenly. So some people can look on the older state.

**Comment by vitorpamplona** [comment]
Local data will be overridden when the same old event comes back from the relay people are using. 

>  state is not distributed evenly

And that is extremely confusing to a non-tech user. 

Plus, we cannot state that something has been "deleted" if it is still out there, right? That's just not cool.

**Comment by anton-isidore** [comment]
This, honestly I think some aspects are so crucial that they cannot be abstracted away form the user. I would not call it deleted. I would called it "undone" or maybe better "reverted".

I think the UI should reflect the event-driven nature of the system that does write-only (edit does not exists).

I can imagine there can be 3 states of the boost icon (and similar for others).

1. Boosted
2. Not boosted
3. Boost reverted

**Comment by anton-isidore** [comment]
I am now reading through the spec, and event deletion is a thing ad it is defined in [NIP-09](https://github.com/nostr-protocol/nips/blob/master/09.md)

**Comment by vitorpamplona** [comment]
v0.17.5 has a popup to Boost/Quote. Do we really need to implement this for likes?

**Comment by sopans** [comment]
> v0.17.5 has a popup to Boost/Quote. Do we really need to implement this for likes?

Because you can simply undo a like now, I don't think asking for confirmation is needed.
Should this be closed because it isn't as needed as before?

**Comment by Chemaclass** [comment]
I would say we can close this ticket. We don't need this "confirmation check" for likes.
