### ISSUE TITLE
Draft note lost when switching back and forth from other apps

### ISSUE THREAD

**Issue by jlopp** [vitorpamplona/amethyst#113]
This is pretty annoying when you're composing a longer note and switch from amethyst to another app: when you switch back to amethyst, it shows the main feed rather than your draft note - the draft is lost.

**Comment by bitcoinuser** [comment]
I agree, I have this same kind of experience as you can see in this video:


https://user-images.githubusercontent.com/1178856/218290360-d8690fc1-961a-4646-b952-6e9602026d72.mp4

**Comment by jlopp** [comment]
Confirmed this behavior no longer occurs for me.
