### ISSUE TITLE
[BUG] Note discovery = "Job requested, waiting for reply" (only the 2 primal sources work)

### ISSUE THREAD

**Issue by Mangoes** [vitorpamplona/amethyst#1135]
**Describe the bug**
After trying Amethyst I understand why nostr is barely used. People try, and then just leave.

As a new user, sorry, but this nostr experience is a mess. Fortunately switching to the Primal app showed me how great nostr can be -> with 24h trending, etc... I discovered some great content.

But with Amethyst:

Global > Note discovery : none but the 2 primal trending entries work. All of the others show "Job requested, waiting for reply" (only the 2 primal sources work).

I can see many hearts & up to several thousand thunders. But when I click on the entries -> "Job requested, waiting for reply"

Everything else works (searching, etc...). But to discover the good content, we need the trending posts in Global > Note discovery to work.

The app seems great otherwise. Hope you can fix this. 

Thanks.

**Comment by davotoula** [comment]
Thank you for the honest feedback!

Amethyst is a decentralised mobile app which has no web servers running that can load, process and cache content like some other Nostr clients.

The note discovery in the app is a new feature that relies on distributed servers operated by anonymous individuals. These servers run computations and return results to mobile apps like Amethyst. Sometimes for a small donation.

The standard is called Nostr NIP90 Data Vending Machines (DVM). Even you can run your own DVM!

For me the `"Currently popular notes DVM" `is returning pretty swiftly at the moment.

The quality of the DVM is very dependant on who has developed it and how it is maintained. Amethyst app has no control over that.

Decentralised solutions are often less efficient but very censorship resistant.

I hope this explains a little why Amethyst will not have built in content discovery but also how exciting this new decentralised protocol is!

**Comment by davotoula** [comment]
I've had an issue twice that prevented any DVMs from loading. I was connected via vpn so maybe that is why.

@Mangoes can you please provide more details? 
- Are DVMs intermittent for you or they never work?
- Are you connecting via VPN?
- Are you connecting via built in tor, Orbot or clearnet?
- Any other areas of amethyst that aren't working when DVMs aren't working like loading notes or user profiles?

**Comment by Mangoes** [comment]
> * Are DVMs intermittent for you or they never work?

They never work. I try regularly, every couple days since the beginning.

The only ones that do work and the primal ones ("Trending on Primal").

> * Are you connecting via VPN?

Yes, I am always on a VPN.

> * Are you connecting via built in tor, Orbot or clearnet?

No.

> * Any other areas of amethyst that aren't working when DVMs aren't working like loading notes or user profiles?

Everything else seems to work properly.

Thanks!

**Comment by vitorpamplona** [comment]
Can you test without your VPN and Tor? I just went through the DVMs and they seem to be working now. 

Many relays block VPNs and Tor connections so that could be the problem.

**Comment by davotoula** [comment]
I've tried full Tor and vpn, works well.

Full Tor over vpn was a bit intermittent and slower.

How is it working for you @Mangoes ?

**Comment by Mangoes** [comment]
Today it works! (both, with vpn & internal tor).

So after 1 month, something seems it have changed (it's probably the allowed ip filtering these services use, as the app wasn't updated).

I think you can close this issue for now at least.

Thanks!

**Comment by davotoula** [comment]
Good to hear. Yes, it works better for me as well compared to when they first appeared.

Closing!
