### ISSUE TITLE
Não consigo logar

### ISSUE THREAD

**Issue by MatintaPere** [vitorpamplona/amethyst#114]
Não consigo logar no Amethyst com minha chave privada. Ele abre uma conta genérica.

**Comment by vitorpamplona** [comment]
A chave está formatada em nsec ou hex? A mesma chave funciona em outros clientes?

**Comment by MatintaPere** [comment]
nsec. Quais outros clientes?

**Comment by vitorpamplona** [comment]
Se vc usar a mesma chave no https://snort.social/, ela funciona?

**Comment by MatintaPere** [comment]
É a chave que aparece em Settings > Profile > Your Private Key Is (do not share this with anyone):

**Comment by vitorpamplona** [comment]
Vc criou a chave no Amethyst ou estás importando de outro cliente?

**Comment by MatintaPere** [comment]
Criei no https://snort.social/

**Comment by MatintaPere** [comment]
No https://snort.social/ funciona.

**Comment by vitorpamplona** [comment]
Hum... acabei de criar uma conta lá e importou corretamente no Amethyst.

Para vc aparece uma conta nova no Amethyst ou carrega uma outra conta randomica?

**Comment by MatintaPere** [comment]
Creio que uma conta nova.![Screenshot_20230211-141425.png](https://user-images.githubusercontent.com/125146546/218271531-e140d4d1-cc84-46ca-98c3-f76c08d2312a.png)

**Comment by vitorpamplona** [comment]
hum... Muito estranho...

**Comment by MatintaPere** [comment]
Criei uma nova conta e funcionou. Inclusive importou quem eu seguia na minha conta antiga. Realmente muito estranho, mas como acabei de criar a conta vou usar a conta nova. Obrigado!
