### ISSUE TITLE
[BUG] App crashes when receiving messages via nip-44

### ISSUE THREAD

**Issue by Anderson-Juhasc** [vitorpamplona/amethyst#1145]
**Describe the bug**
I created a NIP-44 event using the nostr-tools lib and when I went to open the notifications and messages tab the application simply closed.

**To Reproduce**
1. Make the event https://gist.github.com/Anderson-Juhasc/a17587d8537a80191748ad02562de82a
2. Go to Messages or Notifications
3. See error

**Expected behavior**
Decrypt and display correctly without breaking the app.

**Device (please complete the following information):**
 - Phone Brand/Model [e.g. Pixel 7 Pro]: Moto g73
 - Android Version [e.g. 33]: 14
 - App Version [e.g. v0.20.3]: 0.92.5

**Comment by vitorpamplona** [comment]
You cannot send NIP-44 inside a NIP-04 event. The DM spec is on NIP-17

**Comment by Anderson-Juhasc** [comment]
@vitorpamplona is there a way to prevent the app from crashing because of this event?

**Comment by vitorpamplona** [comment]
delete it from the relay? :)

**Comment by vitorpamplona** [comment]
Lots of apps will crash because of it.

**Comment by Anderson-Juhasc** [comment]
Thanks @vitorpamplona, now it's fine
