### ISSUE TITLE
Image uploads get converted to .jpg

### ISSUE THREAD

**Issue by Dielan** [vitorpamplona/amethyst#115]
When you try to upload an animated gif the resulting link is to a jpg image, a single frame of the animated gif.

I know imgur supports animated gifs as well as some video formats. Can we preserve the filetype? That would enable us to post animated gifs and webms and the like. Those types already embed well on Amethyst

**Comment by Radiokot** [comment]
@vitorpamplona Vitor, skipping Bitmap compression before image uploading obviously fixes the GIF uploading issue, but this also means that the images are uploaded as originals and so contain EXIF data. 
Imgur strips EXIF data themselves, hence as long it is used as an image storage – it is fine. But if you consider switching to IPFS or another storage that preserves the metadata, this might be a privacy issue. What do you think?

**Comment by vitorpamplona** [comment]
Let's keep working with imgur for now. We should move away from loading the bitmap into memory and just sending the file directly to imgur. It feels like it's about getting the proper setup for all types of image and video files. 

The upload button also needs some major overhauls to show the upload progress as feedback to the user.
