### ISSUE TITLE
Auto translate from English breaks Imgur image URLs

### ISSUE THREAD

**Issue by Radiokot** [vitorpamplona/amethyst#117]
When the post content is autotranslated, and it contains an Imgur image URL, something happens to the URL and the preview fails.
In my case, the autotranslate translates from English to Russian.
<p float="left">
<img src="https://user-images.githubusercontent.com/5675681/218430021-22fbceaf-ccdd-4b59-95d3-4a8d540d62dd.png" width=300 />
<img src="https://user-images.githubusercontent.com/5675681/218430054-66f7878a-81d5-431c-8ddf-4e6c6de71da0.png" width=300 />
</p>

**Comment by vitorpamplona** [comment]
Same for #[0] Nostr tags. I am not sure how to solve this. Sometimes the translator translates the URL or adds spaces, breaking it into two separate words. Maybe we need to find out how to encode into something the translator won't change.

**Comment by vitorpamplona** [comment]
Also realized that we need to internationalize the `timeAgo` function to reduce the default behavior in other languages.
