### ISSUE TITLE
[BUG ]Not rendering event

### ISSUE THREAD

**Issue by laestrygonian** [vitorpamplona/amethyst#1191]
Amethyst is not rendering certain events:

https://njump.me/nevent1qqsqqqppnqswz5dqnhfnvvyftwjlqphkx9ml5u49cewzmwpv3r073tcpz9mhxue69uhkummnw3ezuamfdejj7q3q80cvv07tjdrrgpa0j7j7tmnyl2yr6yr7l8j4s3evf6u64th6gkwsxpqqqqqqzy8avg5

![Screenshot_20241126_225910_Amethyst](https://github.com/user-attachments/assets/51e96c97-c707-40d9-9254-a30dd358807c)

**Comment by vitorpamplona** [comment]
It is rendering correctly. That's how fiatjaf wrote it.

**Comment by laestrygonian** [comment]
I don't understand why primal shows a different thing.

![Screenshot_20241126_231809_Amethyst](https://github.com/user-attachments/assets/3f6d80c2-4c2e-459b-9a0d-a6b1acb54cac)
![Screenshot_20241126_231803_Primal](https://github.com/user-attachments/assets/182b4a81-199b-4905-8e84-20d88f6a73f3)

**Comment by davotoula** [comment]
Amethyst supports editing of posts, primal doesn't.

In amethyst you can click on Edited to see the original post.

**Comment by laestrygonian** [comment]
Alright sorry for the confussion.
