### ISSUE TITLE
Limit the total of characters of notes on feed and add an option to click to read more.

### ISSUE THREAD

**Issue by bitcoinuser** [vitorpamplona/amethyst#12]
Hi,

Limit the total of characters of notes on feed and add an option to click to read full text.

The total of characters of notes on feed could be a settings that the user choose on app settings.

**Comment by maxmoney21m** [comment]
This issue can probably be closed? The current limit is 350 characters.

**Comment by vitorpamplona** [comment]
This has been fixed a few months ago.. closing.
