### ISSUE TITLE
[BUG] Long urls does not show the download button

### ISSUE THREAD

**Issue by greenart7c3** [vitorpamplona/amethyst#1222]
Disable videos and images preview in settings
Go to nostr:nevent1qqs2ylfyym6nsjz8djs9mm9hw27nmct66h3ukzjhfx2x83tfd3f54lczyqndd22xva0xq0udujlkl880gssr0dcv0mhpwrlsdmtkw07rfjv0zqcyqqqqqqgc2ss5l
There's only the url text, the download button  and loading is gone

I'll try to fix it on monday.

**Comment by davotoula** [comment]
I can't reproduce this issue... Do you have a screenshot or another note id?

thanks
