### ISSUE TITLE
[FEATURE] Ability to navigate to "Add NWC Connection" screen

### ISSUE THREAD

**Issue by MegalithicBTC** [vitorpamplona/amethyst#1228]
We're testing the [rizful.com](https://rizful.com) lightning-node-in-the-cloud service, which offers NWC connections, with Amethyst. 

The first time we ran Amethyst, we were able to get to the screen where we could add the NWC connection by clicking a "zap" button. (That seems to be the only way to navigate to it? It's not in the settings?). That worked!

Now we have Amethyst running on a different device, but we have not yet figured out how we could add the NWC connection with this second device. When we try to "zap", we get...

>  "Unable to send zap, No Wallets found to pay a lightning invoice. Please install a Lightning wallet..."... 

But so far we can't figure out how to "install a lightning wallet" ... that is, add our NWC info.... the only way to navigate to the NWC window that we have found ..... is from the zap button!

**Comment by vitorpamplona** [comment]
Click and hold the zap button

**Comment by MegalithicBTC** [comment]
Ah! thanks. Closing this.
