### ISSUE TITLE
Preview breaks some content 

### ISSUE THREAD

**Issue by tlindi** [vitorpamplona/amethyst#125]
Like story about Iris links

First view on Iris
![Screenshot_20230214-192051](https://user-images.githubusercontent.com/7249767/218810994-08fe754d-3ebe-4e93-ad6b-34d526bf2cd0.png)

And same on Amethyst:
![Screenshot_20230210-004340](https://user-images.githubusercontent.com/7249767/218811121-2cd97104-eae1-4c3b-a5b4-1bc26e897be9.png)

You see how story line gets lost due auto preview?

Note ID:
note1w7vxz9xcqjcrkcu4f4326gflky4eedjm5wwma9cy2udy0639ty8s3yhahc

**Comment by vitorpamplona** [comment]
Their issue, right? If they don't want a preview, don't put preview information on their link. Otherwise, every app will show the same preview :(

**Comment by tlindi** [comment]
I can't tell. I'm just end user. I let them ***@***.***) clarify.

________________________________

**Comment by mmalmi** [comment]
Yeah, Iris preview rendering doesn't always work correctly. Depends on both server-side rendering (iris server) and preview agent (amethyst's choice).

**Comment by vitorpamplona** [comment]
@mmalmi I think you should cache previews with people's pictures. It's ok if they are outdated. Twitter's Preview cards take days to update as well :)

**Comment by mmalmi** [comment]
I used prerender.io for that, but the 100K rendered pages quota got filled in a few days. Set up my own prerender server, but don't know how to hook it up with Netlify 🤷

**Comment by vitorpamplona** [comment]
ohh, no. I meant just set the OpenGraph html tags in the page of users. Super simple :) 

```
<meta property="og:title" content="${userName}" />
<meta property="og:description" content="${userAboutMe}" />
<meta property="og:image" content="${userProfilePicture}" />
```

The app parses it to assemble to preview card :)

**Comment by vitorpamplona** [comment]
There is something on our side as well. Looks like the tags are already there, but it fails in some OG test pages

**Comment by vitorpamplona** [comment]
This has been resolved a couple weeks back. Let me know if it shows up again.
