### ISSUE TITLE
Zap does nothing (not error, nothing)

### ISSUE THREAD

**Issue by anton-isidore** [vitorpamplona/amethyst#127]
My lightning address is `isidore@stacker.news`. I was able to send myself a tip from the profile page.

But when I want to Zap my own post, nothing happens. There is no error, nothing. I have tried to see whats going on with `adb logcat` but there was no exception when I pressed the :zap:. 

It would be great to see what is wrong there.

Zapping other ppl. sometimes works, sometimes not.

- My pubkey: `npub1glec0ncefl0qzgvemv08uy9hltdunmz0fha0cdslhhqfcpe24fjs277pt6`
- The endpoint on Stacker News looks correct: https://stacker.news/.well-known/lnurlp/isidore

(Maybe this may be helpful, the post about adding Zap support to SN: https://stacker.news/items/136477)

**But if SN has some error, no need to investigate it, but I just need to see it in the UI so I can fix it.**

**Comment by vitorpamplona** [comment]
humm... I just sent you a zap and it showed up. I am assuming this is the cache not having your latest ln address

**Comment by anton-isidore** [comment]
@vitorpamplona I was just about to write here that I got a Zap :D and I see it was you. Thank you. I returned the favor. ;)

I have cleared storage of the app and logged again. Still the same.

Also, when I changed the LN Address to non-existing one, I immediately got an error (something about not finding the users callback...)

When I changed it back, again - hitting the :zap: icon does nothing.

**Comment by anton-isidore** [comment]
I am using version from F-Droid the `0.15.1`

**Comment by hax0rbana-adam** [comment]
I am having this same problem with an Alby wallet connected.

When I click the zap icon, and click the amount to zap, I get the loading circle as one would expect. Within a couple seconds, the loading icon completes and it goes back to the unlit lightning bolt icon. No money is moved out of my wallet.

However, if I disable Tor, it works just fine. This is repeatable.

I agree with @anton-isidore that the issue in Amethyst is the lack of any error message to indicate why an outbound zap is failing. There may be additional issues, but until we can see why it's failing, we can't be sure if it's a problem on the wallet side or the Amethyst side.

It could be the timeout is too short, the wallet is prejudiced against Tor users, or any number of other things. If, after the error message is added, there's an issue preventing zaps from working, I'll open another ticket.

For posterity, I am using Ameythst 0.76.0 from F-Droid on GrapheneOS (without Google Play Services installed).

**Comment by vitorpamplona** [comment]
> I agree with @anton-isidore that the issue in Amethyst is the lack of any error message to indicate why an outbound zap is failing. 

In many of these errors, there is no return from the relay that Amethyst requests the payment. So, the app doesn't know it if was successful, if there was an error, or if they even received it or not. 

If Tor is blocking or if the relay is not accepting connections from Tor, the app wouldn't know :(

**Comment by hax0rbana-adam** [comment]
Interesting. I didn't realize the relay was another link in the chain. In my case, I am able to get posts from the relay, so I don't think that's the weak link in the chain for me, but it's important to know about it.

Could we get a message saying something like "Relay timed out" or "Relay error: $ErrorMsg"? Ideally with which relay was attempting to be used.

That should be small enough to fit in a toast message (which I expect would make the UI easier to write), but still give the user some indication of what went wrong.

**Comment by vitorpamplona** [comment]
The issue is that we don't know if it is a time-out. And users should not be paying again. Otherwise, they might send 2 zaps. 

Some zappers take all the way up to 15 minutes to send the confirmation :(

> I am able to get posts from the relay, so I don't think that's the weak link in the chain for me, but it's important to know about it.

Are you receiving any events or specific error message kinds? For each payment request (event kind 23194) the relay should send a success or an error event (23195). I wonder if Alby's relay isn't simply blocking the connection. 

Has any Nostr Wallet Connect Zap via Alby worked over Tor ever?

**Comment by hax0rbana-adam** [comment]
> Has any Nostr Wallet Connect Zap via Alby worked over Tor ever?

Not for me. I am also working with Alby's support team to help get to the bottom of this. If we can't get it sorted out soon, I'll try a different provider and see how that goes.

> Are you receiving any events or specific error message kinds? For each payment request (event kind 23194) the relay should send a success or an error event (23195). I wonder if Alby's relay isn't simply blocking the connection.

Not in the Amethyst UI and I'm not sure how to check at a lower layer. If the connections to the relays don't use TLS, getting a packet capture should be easy enough, but I haven't gone that far in debugging yet.

Nothing shows up in my wallet software. It's as if I never clicked the zap button from the wallet's perspective.

I'll try to get someone from Alby's support team to comment here with what they are seeing on their side. Perhaps if we figure out what's going wrong in my case, we might be able to figure out how to best inform the user of what is going on in at least this situation.

**Comment by vitorpamplona** [comment]
But it works without Tor, right? Have you asked if they are blocking connections through Tor?

**Comment by hax0rbana-adam** [comment]
Yep, it works fine without Tor. They said they're looking into it and will post more info from there side here on this ticket

**Comment by hax0rbana-adam** [comment]
From Roland on Alby's technical support team:

> We have reproduced the issue and it seems enabling TOR in Amethyst breaks zaps for everyone using Alby NWC, however we haven't found the cause yet. We don't do anything special in the relay and we don't block TOR traffic.

I'll continue following up with them to get to the bottom of this and then we can determine if there's anything that can be done on the Amethyst side to help users know when there may have been a problem with sending a zap.

**Comment by vitorpamplona** [comment]
Well... looks like it now works. Can you see if you can zap while using Tor?

**Comment by rolznz** [comment]
@vitorpamplona did you change anything on your side? or is it just related to the TOR network?

**Comment by hax0rbana-adam** [comment]
> Well... looks like it now works. Can you see if you can zap while using Tor?

It worked for me over Tor now, but I have zero confidence that it will remain functional unless Alby made a change on their side. I'll probably switch to another provider to get something that I know will be reliable unless Alby takes sone action to provide confidence in their systems.

**Comment by vitorpamplona** [comment]
> @vitorpamplona did you change anything on your side? or is it just related to the TOR network?

No. I believe this was on Alby's side. They just didn't consider Tor until a few weeks back.

**Comment by vitorpamplona** [comment]
The new UI now displays a more comprehensive error message to make sure if there is something happening with the servers the users can talk to each other and resolve it on the fly.

**Comment by anton-isidore** [comment]
Hi, I have the issue back. It says: 

```
Could not fetch invoice from https://stacker.news/api/lnurlp/isidore/pay: Bad Request - The server can’t or won’t process the request.
```

I get also errors like `could not generate invoice to customers attached wallet stacker news` when I try to send there from Wallet of Satoshi / Phoenix. 

I suspect there is some incompatibility (most probably on Stacker News side) but haven't time to investigate further.

**Comment by vitorpamplona** [comment]
Yeah, those are issues in the receiver wallet that do not allow our apps to create the invoice to send the funds.
