### ISSUE TITLE
Bug on feed when there are posts with videos. 

### ISSUE THREAD

**Issue by bitcoinuser** [vitorpamplona/amethyst#13]
Hi,

Bug on feed when there are posts with videos. See the video:

https://user-images.githubusercontent.com/1178856/213919524-e8fd4d2c-5351-49f4-a4e5-7f10abb19862.mp4

**Comment by vitorpamplona** [comment]
This behavior will unfortunately always exist because it depends on how the author of each post setup their tags. However we have recently reduced the amount of posts that require these loading times.
