### ISSUE TITLE
FR: QR Code showing your pub key to others can scan your QR code and add you

### ISSUE THREAD

**Issue by improvethings** [vitorpamplona/amethyst#130]
On your personal profile, when you click the share button, have an option to display a QR code so others can add you. I was at an event tonight where Damus users were able to do this with each other, but there was no easy way in person for people to share their pubkey with strangers. 
IIRC (saw it for less than 2 seconds) Damus does it in the format of nostr:$pubkey like an href, likely worth emulating that so it's cross client compatible.

**Comment by greenart7c3** [comment]
In the side menu you can generate and read qr code

![Screenshot_20230216-095723.png](https://user-images.githubusercontent.com/115044884/219371297-d87ab34a-34bd-4878-91ab-b75eb347cc56.png)

**Comment by improvethings** [comment]
doh, where were you yesterday? :D   Thanks!   

Maybe the QR code should be the bottom half of that screen instead of an extra click to make it more intuitive
