### ISSUE TITLE
QR private key scanning

### ISSUE THREAD

**Issue by 1ma** [vitorpamplona/amethyst#131]
I think it would be dope to be able to scan private keys directly from the rana output.

They merged support for QR output two weeks ago https://github.com/grunch/rana/pull/26

**Comment by maxmoney21m** [comment]
Agreed, login should have QR support and automatically detect nsec, npub, privkey, or pubkey. Many people feel safer with the QR than copy-pasting where other apps could potentially see the secret keys.

**Comment by vitorpamplona** [comment]
In large scale there are two issues related to this proposal: 

1. QRs with public keys/notes/addresses absolutely cannot be confused with QRs with private keys. If sharing posts via QRs becomes common, we will need to protect users from sharing the wrong QR the same way we have to protect them from reporting themselves today. 

2. Storing passwords in QR codes is generally a bad idea: 
   2.1. You can't recover if the QR is damaged (water damage on paper).
   2.2. Users will be forced to print it, which generally saves the QR inside the disk of the printer. Donated printers have been known to contain sensitive info about the user's life. 

We should probably code and encourage the use of mnemonic words instead: https://github.com/nostr-protocol/nips/blob/master/06.md

**Comment by 1ma** [comment]
I understand the reservations. My original pain point was that I ended up typing the nsec by hand looking straight at the rana output from my computer, because I didn't want to paste it anywhere.

If you think it can be alleviated some other way it's fine by me.

**Comment by vitorpamplona** [comment]
Well, if you didn't want to copy-paste for security reasons, you probably don't want to use a camera either. If people happen to try to use Google's default camera, intentionally or by mistake, it's likely that the nsec has been sent to Google for processing and if you click the QR image, it goes straight into Google Search. 

But, yes. This problem (safely moving keys between devices) is an issue that needs to be solved.

**Comment by maxmoney21m** [comment]
I wasn't imagining exporting from Amethyst via QR, but mainly scanning a QR to log in. If people store their nsec in a password manager, for example, many of them have a QR display option. No doubt people are already doing this using Google camera to copy the QR and paste it into Amethyst, and it would be much safer to just scan it directly in-app.

I definitely agree about NIP-06, too. I could probably work on that after my outstanding PRs are resolved, don't want to open too many at once 😅

**Comment by vitorpamplona** [comment]
Added on: https://github.com/vitorpamplona/amethyst/commit/20aca144faf2b858f8ea1b7cdf4d6b7952e1f750
