### ISSUE TITLE
SOCKS proxy support

### ISSUE THREAD

**Issue by luke-jr** [vitorpamplona/amethyst#132]

**Comment by vitorpamplona** [comment]
I don't know what an app needs to do to support SOCKS (isn't it automatic when you add proxies to the OS?) but we will figure it out :)

**Comment by luke-jr** [comment]
Wouldn't want it for the entire OS, just for Amethyst (ie, a local Tor/Orbot). :)

**Comment by 05nelsonm** [comment]
https://github.com/05nelsonm/kmp-tor

**Comment by luke-jr** [comment]
To be clear, I'm not expecting Amethyst to embed an entire Tor service, just make it practical to use one run separately in a normal Tor app.

**Comment by vitorpamplona** [comment]
Hi Luke, 

Another user mentioned that we could make it work (accessing a local relay) with Orbot over Tor. 

Did you have any issues with it? 

Best,

**Comment by KotlinGeekDev** [comment]
cc @luke-jr

**Comment by luke-jr** [comment]
I don't understand the question.

**Comment by KotlinGeekDev** [comment]
I think he meant using Orbot as a VPN and accessing a relay through that.(Please, am I right @vitorpamplona ?)

**Comment by moonsettler** [comment]
just add

`        .proxy(new Proxy(Proxy.Type.HTTP, new InetSocketAddress(proxyHost, proxyPort)))`

to

```
    private val httpClient = OkHttpClient.Builder()
        .followRedirects(true)
        .followSslRedirects(true)
        .build();
```

i think orbot uses localhost:9050, so that could be default...

**Comment by moonsettler** [comment]
> Hi Luke,
> 
> Another user mentioned that we could make it work (accessing a local relay) with Orbot over Tor.
> 
> Did you have any issues with it?
> 
> Best,

using your own relay is one option but there is an inherent risk with somehow reverting to the default relays and leaking ip. orbot vpn mode is also not reliable in not leaking your ip randomly. using orbot as http proxy ensures that it either works and builds a circuit, or you are not connecting to a relay. it should be a just few lines of code in theory plus an extra triplet of settings.

**Comment by greenart7c3** [comment]
Is this what you want?

Enable orbot
![Screenshot_20230419-073214](https://user-images.githubusercontent.com/115044884/233051715-37f10d23-e58c-42bc-ad5d-be6e64a4d1c6.png)

Enable a setting in amethyst and connect to an onion relay or any other relay through tor


https://user-images.githubusercontent.com/115044884/233052355-6e368edc-4dd6-4787-b45b-d96297eab711.mp4

**Comment by moonsettler** [comment]
> Is this what you want?
> 
> Enable orbot ![Screenshot_20230419-073214](https://user-images.githubusercontent.com/115044884/233051715-37f10d23-e58c-42bc-ad5d-be6e64a4d1c6.png)
> 
> Enable a setting in amethyst and connect to an onion relay or any other relay through tor
> Untitled.mp4

i think so, yes. but i couldn't do it myself. i gave it a try, but didn't manage to start the emulator. stuck there.
the important thing is that you force connecting to relays over tor proxy even if they are wss tcp endpoints.

**Comment by greenart7c3** [comment]
Created a draft pull request #357 so we can discuss what's the best approach to implement this

**Comment by vitorpamplona** [comment]
Tor Support through Orbot released in https://github.com/vitorpamplona/amethyst/releases/tag/v0.46.0 

@luke-jr, let us know if this satisfies your needs.
