### ISSUE TITLE
Amethyst Plus (Paid): What is it?

### ISSUE THREAD

**Issue by alltheseas** [vitorpamplona/amethyst#133]
### Origin

"_I do not mind paying $5 (in Lightning) a month for Amethyst to get costly features. Maybe some form of paid Amethyst?_"
roaming@nostrplebs.com
note1u2hwm0petfn7m0snm70037ymfmevvcu8hqly0gmmqmqcp3kfa87q4gv9um

@vitorpamplona seems to not sleep, and codes 24/7 to give around an expected 1-2 releases per day. Amethyst users have expressed interest to support Vitor, and to potentially receive a few exclusive features in return for their patronage. 

## What could Amethyst Paid include? ##

1. Capability to upload media 
2. Amethyst paid relay 
3. Amethyst supporter badge 

"_Maybe a little nice icon or circle on profile pic and maybe access to a private relay for starters?_"
note109emwktqsxldh0zr3lqnmwnxur82854tf6nkecellfpcnlqgj8tsdegz70

4. Make costs public [of Amethyst server costs], and add zap/pay capability
"_Make the cost and a wallet that will pay for it viewable to the public and we will make sure the bills get paid._"
note15fxv5nkymg0nejah7lzdx58kav34n63vqvyu2dgxrwxfzhhkvukqf5dnzj

## What should Amethyst Paid *not* include ##
"_I would want to pay for Vitor to work on Amethyst, not to distract him from it by requiring him to operate a relay or other services."_

"_The badge would suffice imho._"
-@donnyxray 

### Please add suggestions to this ticket below

**Comment by donnyxray** [comment]
I would want to pay for Vitor to work on Amethyst, not to distract him from it by requiring him to operate a relay or other services.

The badge would suffice imho.

**Comment by vitorpamplona** [comment]
Thank you!

I really want to avoid creating classes of users. 

What about this: Ship the exact same app for paid and unpaid users. Everything stays free and open source, fully open. 

Those who can help, make monthly payments via Zaps to a new Amethyst npub and get an "Amethyst Supporter" (Sponsor?) badge on their profile pictures that shows up to everyone else using Amethyst. The list of sponsors is just the Zap list on the new account's profile page. 

If this gets to a big amount (enough to spike the ire of the IRS), I will create some formal structure to receive the funds. 

In that way, we make sure there is no preferred user base while assuring some resources to a never-ending app :) 

Maybe this "display of goodwill" through badges can help other projects to finance themselves as well?

**Comment by vitorpamplona** [comment]
We can do streaming as well, but that requires an LN wallet in the app that needs to be recharged. :(

**Comment by Chemaclass** [comment]
As you said, I really appreciate that everything is OSS and there is no "different user classes".

Just my 2 cents idea: what about displaying the "Amethyst supporter" badge, with whatever that means (something in the profile saying it, a different style for the avatar,... but mostly something symbolic), after doing a donation of XXk sats, and that will stay active for 30 days, and then it's gone. So, you will keep your supporter "benefits" as long as you manually send that amount.

This way you don't need to worry developing the recurring payment complexity, and just need to watch for a payment done by a certain user, and that user will receive the badge valid for 30 days starting by the payment day.

This would be an easy first step, and you could iterate over this idea after seen how the people like it and use it.

**Comment by donnyxray** [comment]
> This would be an easy first step, and you could iterate over this idea after seen how the people like it and use it.

I can tell you that I would find this pretty annoying. The donation you make is essentially converted into code. That code does not expire after a set time, so I don't see why the badge should expire either. Which is not to say that I would not want to donate repeatedly, I know Vitor needs to keep eating, but I hate being a slave to my device and have it push me to do things. 

My alternative proposal would be to create a new badge once a year or so. And perhaps additional ones at special occasions. That way people are encouraged to donate repeatedly without losing the appreciation that they donated before. In fact, it would reward those that started donating early by giving them a badge that later donations cannot buy.

**Comment by vitorpamplona** [comment]
I agree that a monthly manual payment is too annoying. Yearly might be too big? I am thinking 100K sats as the threshold for the yearly badge, which is around 25 dollars today: basically 2 dollars/mo. 

What do you folks think? Too high? Too low?

**Comment by Chemaclass** [comment]
What about introducing different level of yearly supporters? like 50k for a bronce, 100k silver, 200k gold and 500k platinum. And that will be reflected in the border of your avatar.

And, I like what @donnyxray said, if I do a donation, I like the idea of keeping it there forever, like a badge that won't get lost after time passes. So there are 2 things to consider: the current "supporter status" and the historical ones.

**Comment by vitorpamplona** [comment]
Closing this discussion since we went with the value4value "Zap the Devs" model
