### ISSUE TITLE
Zaps defaulted to amount of 1000 Sats

### ISSUE THREAD

**Issue by michaelg-au** [vitorpamplona/amethyst#136]
Zaps default to amount of 1000 Sats - at least when seperate lightning app/wallet is installed on phone (Zeus) - without any apparent ability to adjust amount. To properly zap and ascribe a value to a nostr note, need choice as to amount.

**Comment by grunch** [comment]
this is fixed in the new version

**Comment by braydonf** [comment]
Yeah, specifically in https://github.com/vitorpamplona/amethyst/releases/tag/v0.17.1
