### ISSUE TITLE
"Bell" section has always a "new" mark

### ISSUE THREAD

**Issue by Perlover** [vitorpamplona/amethyst#139]
V0.16.2

After I sent the first zap to myself and statistics about it appeared in the statistics of the post and profile, after that (it seems to me that the reason for the bug is this) the "bell" tab always has the label "new". Previously, the label was reset when I entered the "bell" section, but now it is not. Even log off does not help: log off -> stopping the application -> deleting the cache and data: after logging in, a constant notification about new, unread events appears again ("bell" section)

**Comment by Perlover** [comment]
I installed 0.17.0 release and there is no same bug
I am closing the ticket

**Comment by Perlover** [comment]
V0.17.1
After sending to myself a zap again I see the same problem again

**Comment by Perlover** [comment]
I updated to v0.17.4 and don't see permanent "Bell/new" notification. But may be it's because I didn't send zap to myself again after this :-/

**Comment by vitorpamplona** [comment]
v0.17.5 also fixed a bug in the notifications of Zaps (I was using the time of the request event and not the time of the payment)

**Comment by djkazic** [comment]
Seeing this on v0.22.0

**Comment by vitorpamplona** [comment]
Please see if it still happens on v0.22.1: I did some fixes in that area.
