### ISSUE TITLE
Amethyst always crashes when hitting notifications

### ISSUE THREAD

**Issue by Funman2** [vitorpamplona/amethyst#143]
Since release 17.0 every time I want to access notifications amethyst app crashes completely, notifications not accessible anymore.
The same happens on version 0.17.1 , also clearing the cache and erasing data did not help. Going back to 0.16.2 solved the issue but of course i want the zaps!...

**Comment by vitorpamplona** [comment]
Should be fixed on v0.17.5, please confirm.

**Comment by Quin5** [comment]
I had this same issue, and can confirm that it has been corrected (for my environment, anyway).

**Comment by Funman2** [comment]
Yes solved! Thanks.
