### ISSUE TITLE
Images being resized on a third party

### ISSUE THREAD

**Issue by bokybanton** [vitorpamplona/amethyst#145]
You should advise users you are parsing all images through your private server to resize'em all. This is a security issue and I will advise users not to use this app. The server is: https://d12fidohs5rlxk.cloudfront.net/  You are resizing imgs on your server ? This component should be audited and it is not transparent. AsyncImageProxy.kt

**Comment by bokybanton** [comment]
Users should get images as they get them, with all its characteristics.

**Comment by vitorpamplona** [comment]
It's a bandwidth+memory problem. People with fixed data plans can't be
downloading 20MB per profile picture and most phones with entry-level specs
crash when simply trying to open these large files.

Happy to use alternatives, but right now the app doesn't work well without
MASSIVE resizing.

**Comment by braydonf** [comment]
Disabling automatically loading images could be an option. Settings could configure what size of images to automatically load, and larger would need to be requested specifically by clicking on it.

**Comment by vitorpamplona** [comment]
We don't use a image proxy anymore, so I am closing this.
