### ISSUE TITLE
[ISSUE] View flickering when switching between "New Threads" and "Conversation"

### ISSUE THREAD

**Issue by kirillkovalenko** [vitorpamplona/amethyst#146]
When I switch between "New Threads" and "Conversation" the feed view starts to flicker. For a short period of time I also see users icons on the right side of the view.

**Comment by vitorpamplona** [comment]
hum... which phone and OS?

**Comment by kirillkovalenko** [comment]
> hum... which phone and OS?

Xiaomi Redmi Note 9 Pro

Also note that I have a non default system-wide text size (large). In my experience this also tend to cause issues with different apps.

**Comment by vitorpamplona** [comment]
Interesting.. Will do some research and try to see if I can replicate somehow

**Comment by kirillkovalenko** [comment]
> Interesting.. Will do some research and try to see if I can replicate somehow

Note that is only happens if I tap on the tabs, and works okay if I swap between views.

**Comment by vitorpamplona** [comment]
https://github.com/vitorpamplona/amethyst/commit/4dcf38c492ca1c9ef541dccfe044552224c737cd
