### ISSUE TITLE
Viewing others follows if select more than one changes other to follow

### ISSUE THREAD

**Issue by jaschadub** [vitorpamplona/amethyst#148]
In latest version if select multiple to follow changes unfollow button back to follow. See screen recording.

https://user-images.githubusercontent.com/768841/220732882-89825394-c619-473f-9aac-ca79df1a7556.mp4

**Comment by vitorpamplona** [comment]
Which version was this recorded, 17.6 or 17.7?

**Comment by jaschadub** [comment]
17.6

**Comment by jaschadub** [comment]
On a Samsung ZFold4 Android 13 One UI 5

**Comment by vitorpamplona** [comment]
It should be solved on 17.7, but I am hunting a similar but different issue.

**Comment by jaschadub** [comment]
This is resolved for me using v0.17.9
