### ISSUE TITLE
ZAP request without relays tags

### ISSUE THREAD

**Issue by mutatrum** [vitorpamplona/amethyst#149]
I just received a zap originating from Amethyst 0.17.9, and couldn't send the zap note because there were no relays mentioned. I think this should not happen, following NIP-57 spec.

Unfortunately couldn't reproduce this a second time.

**Comment by vitorpamplona** [comment]
Hum... looks like the only way this could have happened is when the user has an actual Nostr event with empty relays. Literally "{}" in the contents of a kind 3 event. 

I will make a fix for those cases.
