### ISSUE TITLE
We should always have a loading profile icon on feed.

### ISSUE THREAD

**Issue by bitcoinuser** [vitorpamplona/amethyst#15]
Hi,

Sometimes I open the feed and some users profile icons do not appear Immediately (Take some time to load), then suddenly load and blinks on the screen. I think this is not good, so I suggest that all profiles on feed always show a loading profile icon with animation until the profile image is loaded. Something like what camelus.app does. See the video:

https://user-images.githubusercontent.com/1178856/213920235-8e4181ad-2999-4000-a1f9-7ae407a20d0c.mp4

**Comment by vitorpamplona** [comment]
We currently display a little robot before the image is downloaded.
