### ISSUE TITLE
Show the release version

### ISSUE THREAD

**Issue by BTCBellyButton** [vitorpamplona/amethyst#151]
It'd be nice to have the release version somewhere without having to go to the app properties in android.

For example, with a less invasive font of course:

![Screenshot_20230223-190601](https://user-images.githubusercontent.com/68573637/221060040-f9ff190b-88ba-4754-b69d-2db6576255e5.png)

**Comment by vitorpamplona** [comment]
Good idea

**Comment by BTCBellyButton** [comment]
Do you ever sleep?😃

Thanks!! 🙏
