### ISSUE TITLE
An app update clears the usernames for all follows and followers, mentions not possible without manually scrolling follows and followers list in own profile view

### ISSUE THREAD

**Issue by alaznem** [vitorpamplona/amethyst#153]
**Briefing**

To mention a follower or someone I follow after an Amethyst update, I need to manually scroll my follows and followers list to fetch the usernames of the npubs.

**Desired outcome**

Keep the user name list persistent during an app update or fetch the usernames of follows and followers in the background after an app update.

**Comment by alaznem** [comment]
Reply from @vitorpamplona via nostr:

"Yep, we don't load any information until some post of the person shows up. Mostly to avoid inconsistencies of caching when people change their names, rotate keys etc. Persistent db is coming." -- [note1h0yutrdv3clhwu50p49ujuammtjfdulnwcq4myxxxc79njgq234sr0vmw5](https://www.nostr.guru/e/bbc9c58dac8e3f77728f0d4bc973bbdae496f3f376015d90c6363c59c900546b)

**Comment by vitorpamplona** [comment]
Now the search hits a few relays and downloads potential matches. It's not as fast as a local search but it seems to be working well.
