### ISSUE TITLE
[Request] localization for app

### ISSUE THREAD

**Issue by rashedswen** [vitorpamplona/amethyst#155]
hello 

I want to add Arabic Language for the application and I want to know is there any standard for string keys? 

I will do all localization steps from a to z and just I want to be sure about string keys standards.

my regards.

**Comment by vitorpamplona** [comment]
Hi Rashed,

We don't have any particular standards yet. Do you best and I am sure we will be able to accept it 

Thank you for the contribution

**Comment by rashedswen** [comment]
ok thank you
