### ISSUE TITLE
Unlike after like not possible

### ISSUE THREAD

**Issue by Perlover** [vitorpamplona/amethyst#156]
V0.18.3
After a like I cannot do an unlike - the heart active icon is on always

**Comment by vitorpamplona** [comment]
Yep, there is no delete in Nostr.

**Comment by Perlover** [comment]
Delete an unlike? It seems to me that I could have removed the "heart" earlier

**Comment by Perlover** [comment]
> Yep, there is no delete in Nostr. It's like e-mail, once you send a like, a retweet, a post, a report, it's out of your hands. 

I wonder what the problem is with sending an event like, signed, with a date later? This is not a question for you - this is a rhetorical question for those who are responsible for the protocol.

**Comment by vitorpamplona** [comment]
The problem is that now you have two events. You haven't actually deleted it. People still have a signed record of the thing you wanted to delete. 

So, calling it a delete is misleading. The signed payload is asking others to delete. But there is no way to verify compliance.
