### ISSUE TITLE
NIP05 with only _@domain shown as _@domain

### ISSUE THREAD

**Issue by Kapot** [vitorpamplona/amethyst#157]
I think the point of the _@domain is to have it shown without a name, now it shows with the _ in the nip05. 

![example.png](https://user-images.githubusercontent.com/6935358/221498478-746749c7-36ab-4f6d-a833-103150dd7118.png)

**Comment by dadofsambonzuki** [comment]
Yep, came here to raise the same.

![Screenshot_20230227-111318.png](https://user-images.githubusercontent.com/87125117/221549592-8e722b85-82c0-4cbd-a552-910c74a62f85.png)

**Comment by Kapot** [comment]
Update: in the feed it is now fixed, but on the profile it's still showing the _

![Screenshot_20230228-122354~2.png](https://user-images.githubusercontent.com/6935358/221840202-3e9934ac-1475-4432-be8c-8218f9b3ad53.png)

**Comment by maxmoney21m** [comment]
@vitorpamplona this issue can be closed
