### ISSUE TITLE
On initial load the left slide-out menu does not have valid followers account

### ISSUE THREAD

**Issue by djkazic** [vitorpamplona/amethyst#158]
Once you go to the profile it does set the value properly. Otherwise on first load it is always zero.

**Comment by djkazic** [comment]
When I click on someone else's profile and wait for their followers to populate, mine begin to count up in the slide out menu as well. Our mutual followers, anyway.

**Comment by vitorpamplona** [comment]
> I see. I tried waiting longer (5m) but it doesn't seem to populate. 

It doesn't populate automatically. The count starts when you visit your profile. I will probably move this to when you press a button to compute your follower count in the profile.

**Comment by djkazic** [comment]
Makes sense. Thanks for the clarification.
