### ISSUE TITLE
Notes that have links in the middle of the sentence, render wrongly on feed

### ISSUE THREAD

**Issue by bitcoinuser** [vitorpamplona/amethyst#17]
Hi, 

Notes that have links in the middle of the sentence, render wrongly on feed.

I wrote: Yes, you can use getlaby.com browser extension to login. See how appear on feed:

![photo_2023-01-22_11-50-11](https://user-images.githubusercontent.com/1178856/213922193-620d9c33-191e-467e-a6fb-12e68cd5ad10.jpg)

**Comment by KotlinGeekDev** [comment]
Please @bitcoinuser any screenshot of this?

**Comment by KotlinGeekDev** [comment]
Edit : now I see, @bitcoinuser . The screenshot was not rendering for some reason. I think it can be fixed.

**Comment by vitorpamplona** [comment]
This has been fixed. The preview card only shows if you type http:// with the link :)
