### ISSUE TITLE
[FEATURE] Mark All Read for Direct Messages

### ISSUE THREAD

**Issue by derekross** [vitorpamplona/amethyst#172]
**Is your feature request related to a problem? Please describe.**
Amethyst does not have a feature to allow the user to mark all direct messages as read. All DMs that a user has previously read on other clients remain with a notification bubble as un-read even though they've been read. This makes it hard to know when you receive a new DM because a user could potentially have hundreds of DMs that have been previously read on another client.  Because of this, users have a constant notification bubble that won't go away.

**Describe the solution you'd like**
Implement a button in the Direct Message tab that marks all DMs as read. Tapping this button marks all DMs as read as seen on other clients like Snort and Astral.

**Bounty (in Bitcoin sats) offered for the implementation**
I'll start the bounty off at 50K sats and post on Nostr to raise more awareness.

**Comment by maxmoney21m** [comment]
Considering taking a stab at this. Do you (or @vitorpamplona) think this would be better as:

1. A simple persistent button that shows whenever you have more than some threshold of unread messages (e.g. 10)
2. A popup button (style similar to zap amount selection buttons) that shows on long pressing any message. This method could allow for additional actions, perhaps: Mark Read, Mark All Read, Hide

**Comment by vitorpamplona** [comment]
Thanks @maxmoney21m! 

Since this is for all DMs at once, the easiest design would be an action on the Tab itself that simply marks all DMs on that tab as Read. 

The most flexible design would be a per-row selector when you press and hold each user. In that way, users could mark many of them and then hit Mark all as Read in a similar way Telegram and WhatsApp do. 

In both cases, we could use the 3-dot menu icon after the time, in the same way we use on the home page, to also have these options (so people don't have to guess that press and hold does something)

**Comment by derekross** [comment]
I wouldn't want to have to select 500 individual rows to mark all of my DMs as read. It's better than having to open 500 DMs and scroll down through each one, but it's still a very time consuming task that I just wouldn't do.

**Comment by vitorpamplona** [comment]
Agree, looks like we are doing an action at the tab level, @maxmoney21m

**Comment by maxmoney21m** [comment]
Reference images @vitorpamplona 

![image](https://user-images.githubusercontent.com/124794312/222466233-7bb7b9dc-cd1b-4001-8116-905979b88150.png)

![image](https://user-images.githubusercontent.com/124794312/222466281-05fd9dd5-e299-48e6-8d0e-66b94398ad82.png)

**Comment by efraimbart** [comment]
Alternatively:

![image](https://user-images.githubusercontent.com/8098171/222629851-4c31d015-71a1-4694-9a15-67cee4078602.png)
