### ISSUE TITLE
[Feature Request] Follow a person directly from a note

### ISSUE THREAD

**Issue by GianlucaTassara** [vitorpamplona/amethyst#175]
On Twitter, everytime I saw a great tweet/reply and I wanted to follow that person, all I had to do was click on the top right corner of the tweet and then click follow.

On Amethyst, it's really cumbersome to follow people. You have to go inside their profile, click follow and then go back to where you were on the feed.

**My request is really simple:**

Enable the option to follow someone by clicking the three dots on the top right corner of a note. This way you can quickly follow those people that make valuable notes without having to go inside their profiles.

**Comment by rashedswen** [comment]
done

**Comment by rashedswen** [comment]
@vitorpamplona  close this
