### ISSUE TITLE
If I expand an image and then some new message load on feed, the image is closed automatically.

### ISSUE THREAD

**Issue by bitcoinuser** [vitorpamplona/amethyst#18]
Hi,

If I expand an image and then some new message load on feed, the image is closed automatically. See: 

https://user-images.githubusercontent.com/1178856/213938005-76e5afca-a9f1-4e18-9d94-51e007b3c1b3.mp4

Problem related to issue: https://github.com/vitorpamplona/amethyst/issues/16

**Comment by vitorpamplona** [comment]
This has been fixed a few months back. Let me know if it comes back.
