### ISSUE TITLE
Global feed icon

### ISSUE THREAD

**Issue by maxmoney21m** [vitorpamplona/amethyst#183]
The global feed is currently accessed through the magnifying glass icon at the bottom. This is typically the search icon. While the screen does have search, new users are often unaware that it is also the global feed.

I suggest replacing the magnifying glass with a globe icon to make this clear. The search bar is rather obvious once you are on the screen, and probably doesn't need it's own icon at the bottom.

**Comment by 3j2009** [comment]
I agree, globe icon for global feed is more intuitive (Jacob's Law).

Attached files are OS & royalty free.

![Global feed icon](https://user-images.githubusercontent.com/126127093/222864016-f40848b6-a400-479f-88cc-5ee4022415a8.png)
![Global feed icon](https://user-images.githubusercontent.com/126127093/222864020-b6c5f858-1d65-4451-a0d0-15250157857c.svg)
![Screenshot](https://user-images.githubusercontent.com/126127093/222864022-80e225a5-5c11-4409-b8ca-46341459ce6c.png)

**Comment by vitorpamplona** [comment]
Looks like the icon fits really well with the other icons! We will use. Thank you!
