### ISSUE TITLE
[FEATURE] Additive feeds instead of Regenerating feeds

### ISSUE THREAD

**Issue by vitorpamplona** [vitorpamplona/amethyst#198]
**Is your feature request related to a problem? Please describe.**
The app currently uses LiveData observers to notify ViewModels of new items added to the LocalCache. I am not talking about the updates within each object, but new items to the database. Upon a LiveData notification, each feed screen calls a refresh function of it's respective ViewModel. That refresh collects data from a DAL Filter which loops through the entire repository again and creates a new list of posts to be displayed in the feed, even if the new object was never going to be in the feed in the first place. 

Because there is always a new event coming in from relays, this architecture creates an unfortunate situation where all feeds are updated at all times (2-3 times a second). We want our user to see the new Nostr Event right away if it's part of the view he/she is currently seeing or be notified right away if it's in a view he/she is not seeing. It's just a roundabout way of doing it. 

**Describe the solution you'd like**
I'd like to find a way for the LocalCache to have an Observable interface where we can send only the new Events to the filter/view model. The filter then decides if that event changes or not the feed and adds or removes that one element accordingly avoiding loops through the LocalCache database. 

I know that Live Data doesn't seem to support this type of thing (MutableList individual notifications for adds and removes). Maybe Flow or Kotlin's Channels can be used instead. Or maybe we will need to code our own Observables interface. 

I am looking for solutions here. The current architecture is getting old and we will need to figure out more performant solutions soon. 

Ideas? 

**Additional context**
Add any other context, video, or screenshots about the feature request here.

**Comment by maxmoney21m** [comment]
I think Flow should be able to do what you described. Instead of the LocalCache consume functions doing `refreshObservers` and starting everything over again, they can simply emit the new item. So items go into LocalCache, get parsed and saved, and then emitted in a flow. The ViewModel can initialize the feed from the cached values in LocalCache as it does now, collect the flow (using the ViewModel lifecycle), and map it through the filter, into a local mutable state list, so it is just adding single elements as needed and recomposing.

I looked at the code a bit and I think this would work, but I did not try to code it up so I don't know if there will be any big problems / blockers.

**Comment by KotlinGeekDev** [comment]
That's true, @maxmoney21m . But @vitorpamplona have you tried just exposing a LiveData from the VMs, and using Compose's observeAsState() ?

**Comment by vitorpamplona** [comment]
Yes, that's how we do it today. However, each screen has its own filter for what it sees. The screen receives a "New object in database" event and then runs the filter through everything again, not just that new object.

**Comment by KotlinGeekDev** [comment]
@vitorpamplona Could we put some kind of cache between the DB and the VM, that the VM could use?

**Comment by vitorpamplona** [comment]
Same problem, no? The issue is on how to pass a new object from the DB to the Cache, then.

**Comment by KotlinGeekDev** [comment]
Yeah.

**Comment by vitorpamplona** [comment]
Ideally, we would want to receive a new event, save that in Room (doesn't exist yet), and then hit every part of the view that might need this object without requiring the view to reload the entire query.

**Comment by KotlinGeekDev** [comment]
Right. And then we could have something linked to Room(could be a LiveData object) that helps observe that change and just get it

**Comment by KotlinGeekDev** [comment]
@vitorpamplona Here is a library that implements that diffing functionality.(It uses Flows :) ). https://github.com/xxfast/KStore

**Comment by vitorpamplona** [comment]
Is KStore just an example or is the idea to use it to store Nostr events without using Room? If the latter, then it all depends on how fast it is, since we are processing around 500-1000 events a second.

**Comment by KotlinGeekDev** [comment]
@vitorpamplona please what do you think it could be? (Could it be better to implement such a model with LiveData, or just use the library?)

**Comment by vitorpamplona** [comment]
The library's goal is to save to disk. It depends on how fast it is. I suppose Room is faster as a storage layer. We can test it out to see how it goes...

**Comment by KotlinGeekDev** [comment]
I see. OK.

**Comment by vitorpamplona** [comment]
@KotlinGeekDev Is the fact that LiveData only refreshes observer in the Main thread a problem? Does Flow operate in the IO thread?

**Comment by KotlinGeekDev** [comment]
Sorry @vitorpamplona for responding now. As for LiveData, I don't think it is a problem. As for Flow, if it is collected in the main thread, it operates in the main thread(but does not block it).

**Comment by vitorpamplona** [comment]
This was merged a while back and seems to be working great. I will close this for now. Feel free to create new issues if problems arise.
