### ISSUE TITLE
versionCode not increased?

### ISSUE THREAD

**Issue by IzzySoft** [vitorpamplona/amethyst#20]
Looks like today's release (v0.10.0) still has the same `versionCode` (17) as the previous v0.9.6. As Android uses `versionCode` to tell APKs apart, it's important to increase it with each release (or whoever had the previous version installed would get no notification of a newer one being available). Guess it just slipped through this time, so please take this just as a notification (oops, or reminder) to always increase `versionCode` right before releasing :wink: Thanks!

**Comment by vitorpamplona** [comment]
Nice catch! I just released v0.10.1 to fix this issue:  https://github.com/vitorpamplona/amethyst/releases/tag/v0.10.1

**Comment by IzzySoft** [comment]
Yeah, my updater complained, that's how I caught it :see_no_evil:

Oh, sorry, I should have mentioned: Amethyst is [listed in my F-Droid repo](https://apt.izzysoft.de/fdroid/index/apk/com.vitorpamplona.amethyst). If you wish you can [pick a badge](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) to link there e.g. from your Readme. If you wish I can send you the metadata used there in [Fastlane](https://gitlab.com/-/snippets/1895688) format to include with your repo, so you can control description, screenshots etc (changes to them will then be picked up automatically with each new release). Updater runs once a day, starting around 6 pm UTC and publishing about an hour later.

**Comment by IzzySoft** [comment]
I just caught you again, @vitorpamplona – please keep up fixing! Ideally before tagging :speak_no_evil: :dash:

> Binary files com.vitorpamplona.amethyst_38.apk and com.vitorpamplona.amethyst_v0.13.3.apk differ
