### ISSUE TITLE
[FEATURE] Code style guide

### ISSUE THREAD

**Issue by maxmoney21m** [vitorpamplona/amethyst#203]
I assume people are mostly using Android Studio for development? @vitorpamplona would you consider using the standard [Kotlin style guide](https://kotlinlang.org/docs/coding-conventions.html) conventions? For me, after writing some code for a PR, I'd be happy to make a final commit that just uses Android Studio autoformat to bring everything in line with the conventions. Currently there is no real consistency between files, including some 2-space and some 4-space, long argument lists on one line vs. multiple lines, etc.

I'm not suggesting to require this or reject PRs for formatting issues, but it might be nice just to have a statement encouraging contributors to use the same formatter for consistency & readability. If so, I suggest just adding a line on the README under Contributing:

```
Please format pull requests using the [Kotlin style guide](https://kotlinlang.org/docs/coding-conventions.html) coding conventions.
```

**Comment by vitorpamplona** [comment]
I would favor a forcing code styling check upon commit/test. We use [Spotless](https://github.com/diffplug/spotless/tree/main/plugin-gradle#applying-ktlint-to-kotlin-files) in another project but I am open to any tool that might do a similar job.

**Comment by maxmoney21m** [comment]
Closing since we have linting hooks now
