### ISSUE TITLE
[FEATURE]: Amethyst official relay & server

### ISSUE THREAD

**Issue by niteshbalusu11** [vitorpamplona/amethyst#207]
**Is your feature request related to a problem? Please describe.**

One of the issues with using public relays right now is they limit you. They usually have limits on how much and how frequently you pull info. This could be be an issue when we are trying to do more advanced stuff on the client side like fancy metrics or even something as simple as showing reliable followers count or maybe even push notifications. 

**Describe the solution you'd like**
These are just my initial thoughts, apart from decentralized relays that do their job as usual, we could have an official amethyst relay and also run a server/database along with it that pulls info from Amethyst relay (and maybe some more big relays) and our server processes that info for the client to display more interesting info without public relays ever being a bottleneck. 

This could also be additional paid services for people use amethyst. 

Just drinking beer and brainstorming. Happy to convert this from an issue to discussion if y'all want it. 

I would love to know the thoughts of everyone on what you think of it. 

**Bounty (in Bitcoin sats) offered for the implementation**

Could potentially consider hosting it and cover some costs.

**Comment by maxmoney21m** [comment]
I don't like this idea. Amethyst is currently the best nostr client for Android (and possibly just the best nostr client all around). I think it should stay as neutral as possible, client-only. Users can get any relay specific features they need (more space, lower latency, faster, better uptime, etc.) by using or paying for different relays as they need.

I would look for another client if Amethyst started depending on its own relay to function properly.

**Comment by niteshbalusu11** [comment]
> I would look for another client if Amethyst started depending on its own relay to function properly.

I think depending is the wrong word to use here. Nothing in the feed of the user would show up from Amethyst relay. In fact using the relay can be opt-in. 
The relay along with the server could simply be used to offer cooler stuff. Doing everything client side isn't possible, clients have limitations and always rely on servers.

**Comment by maxmoney21m** [comment]
@niteshbalusu11 have you looked at the Relay Implementations section of [nostr.net](https://nostr.net)? There are lots of projects to work on for doing cool stuff with relays.

**Comment by niteshbalusu11** [comment]
> @niteshbalusu11 have you looked at the Relay Implementations section of [nostr.net](https://nostr.net)? There are lots of projects to work on for doing cool stuff with relays.

Right, but you're still depending on a relay to pull from, which is a server?
Maybe I am missing you point.

**Comment by maxmoney21m** [comment]
In the context of nostr, what is the difference between a relay and a server? Either our identities & data are portable, or they aren't. If a nostr client additionally saves separate data on proprietary / centralized servers, and that centralized server is required for the app to be fully functional (to do the "cool stuff" as you say), then it defeats the purpose of this nostr experiment.

I want all the "cool stuff" to be something any relay can do, and that any client can use. If you have ideas for any way to improve relays, that would be great -- you should make some suggestions to the relay projects like nostream or strfry. There are many relay projects to look into. For now, this particular project is only about a client. Sure, Amethyst could also build a relay implementation, but why? Sure, Vitor could run an "Amethyst relay" (like relay.damus.io) and use that as a default connection for new users, but this would just again be a standard relay, not specific to Amethyst.

**Comment by vitorpamplona** [comment]
Let's try to avoid a relay setup... Clients building up servers/relay services is a centralizing incentive. We should strike to build in-app tools to educate users on the relays they choose and help them choose better ones.

**Comment by niteshbalusu11** [comment]
Don't want to upset more people. Closing this.
