### ISSUE TITLE
Nostr reply enhancement support

### ISSUE THREAD

**Issue by arthurfranca** [vitorpamplona/amethyst#211]
Hello, @vitorpamplona. I'm calling all main nostr client authors to join the [discussion regarding thread enhancement](https://github.com/nostr-protocol/nips/issues/267). Could you please give your opinion on willingness to support it on Amethyst.

At the end of the discussion, you can see that clients would only need to do small tag addition when creating reply events. Nothing else would change as it would be completly backwards-compatible. It would merely allow for new optional ways of requesting slices of a thread.

Without client authors support the enhancement will never be approved. Thanks

**Comment by vitorpamplona** [comment]
Closing it here to continue the discussion there.
