### ISSUE TITLE
[FEATURE] add upload button in channel view

### ISSUE THREAD

**Issue by Dielan** [vitorpamplona/amethyst#214]
**Is your feature request related to a problem? Please describe.**
The upload feature works great already. The button is missing in the view used for channels. I simply want it added so I can reply with the same image attaching experience

**Describe the solution you'd like**
Add the upload button in channel/DM view (the envelope tab)

**Bounty (in Bitcoin sats) offered for the implementation**
Not urgent, no bounty

**Comment by vitorpamplona** [comment]
Added in 0.27.0
