### ISSUE TITLE
[BUG] Static robohash as the default avatar

### ISSUE THREAD

**Issue by maxmoney21m** [vitorpamplona/amethyst#215]
I knocked together a quick demo of this just to see if it would work, and turns out to be very easy. The [robohash](https://robohash.org/) icons are available as svg under MIT license [here](https://github.com/nimiq/robohash).

Some quick and dirty splicing them together directly in the code gives me a nice looking avatar:

![image](https://user-images.githubusercontent.com/124794312/223343778-5988e82c-9eca-40c8-88ce-d54af7893e3b.png)

@vitorpamplona if you would accept a PR for this I will polish up the code and submit.

The end result is just a function:

```
@Composable
fun Robohash(npub: String): ByteBuffer { ... }
```

Where the `ByteBuffer` can be passed directly to `Coil` data loader instead of a URL:

```
AsyncImage(
  model = RoboHash(user.npub),
  ...
)
```

I didn't benchmark anything but I think it should be pretty performant, it's just some simple string formatting and manipulation.

**Comment by maxmoney21m** [comment]
It would be even more awesome if one of our designer friends wanted to make some ostrich SVGs to use instead of the robots 😆

@3j2009 is that something you'd be interested in doing? It basically works by making SVGs of different components: bodies, heads, eyes, etc. The original version used here has 5 different components, each with 10 variants, so 50 small component SVGs, plus 10 or 20 different backgrounds. The components have to be in the same location and size so that we can overlay them to generate unique images for a different npub. The exact number of components and backgrounds is not important as long as the number of possible combinations is large.

You can check the robohash repo for examples of other characters, there are humans, aliens, cats, etc.

**Comment by 3j2009** [comment]
good sir are you talking about creating the Bored Nostrich Yacht Club?

**Comment by vitorpamplona** [comment]
Interesting.. we are using robohash from a different repo. The issue is that creating tons of bitmaps was a bit slow, so I forced just one until I figured a way to make more performsnt.  Happy to consider this if it uses less resources.

**Comment by vitorpamplona** [comment]
The current lib takes about 2-10ms in the [imageForHandle](https://github.com/vitorpamplona/amethyst/blob/5add9669f2dd5bfe051e5757f9052be2c2ea0b9d/app/src/main/java/com/vitorpamplona/amethyst/RoboHashCache.kt#LL28C23-L28C44). It looks like it's about Bitmap pixel generation. 

An SVG version could transfer the image stack combination to the hardware renderer, which will def be faster than the current version.

**Comment by maxmoney21m** [comment]
@vitorpamplona I [pushed a branch on my fork](https://github.com/maxmoney21m/amethyst/commits/215-robohash-identicons). I replaced all of the current calls to AsyncImageProxy with calls to the Robohash fallback version, and it seems to be working OK for me in the emulator. The entire SVG RoboHash generator (including the SVGs themselves) is in [this file](https://github.com/maxmoney21m/amethyst/commit/438472acca2eb7ec52b96cb580cc5d3149f311a8).

Would it be possible for you to benchmark it the same way to compare it to that 2-10ms number?
