### ISSUE TITLE
[FEATURE] [IDEA] Badges visualization

### ISSUE THREAD

**Issue by kirillkovalenko** [vitorpamplona/amethyst#217]
Over the last few days badges started to take off in the nostr space. I would like to suggest a possible way to visualize badges the profile. Below is how badges are displayed in the Niantic's Ingress game. Amethyst should not necessary do a copy-paste of this. It's just a starting point or a direction of thought. Wdyt?

![image](https://user-images.githubusercontent.com/3592194/223453132-a84ecce0-31b0-47d1-a492-ede275ac1fa1.png)

**Comment by vitorpamplona** [comment]
Definitely cool. But how practical/useful? Would people really have 100s of badges in their profile? 

We can probably add this on a "Show More" button.. Just for the visual effects of it.

**Comment by kirillkovalenko** [comment]
> But how practical/useful? Would people really have 100s of badges in their profile?

Usefulness is questionable and it seems to me badges are not about practicality. People simply fascinated about having them, similar to NFTs and other collectables.  I think that there are already users with dozens of badges.

**Comment by vitorpamplona** [comment]
I didn't mean if the Badges are useful (not for us to decide), I meant if the visualization is useful: 
- Can you find the badges you are looking for? 
- Does it make sense to distribute in 2d like that? 
- etc

**Comment by kirillkovalenko** [comment]
The visualization on screenshot is useful in the sense that it's pretty compact. It somewhat follows the real world UI pattern used in military or boy-scout ribbons.

![image](https://user-images.githubusercontent.com/3592194/223509875-bb383173-72d1-4c84-965f-4ad585eb7ba2.png)

**Comment by vitorpamplona** [comment]
Humm.. are badges not showing up for you on Amethyst? This has been out since last Sunday. 

![Screenshot_20230309-093903.png](https://user-images.githubusercontent.com/532031/224058500-127fb969-6ad5-412f-a599-087c96bda040.png)

**Comment by kirillkovalenko** [comment]
hmm. somehow they don't show up.

**Comment by kirillkovalenko** [comment]
I have nuked the profile, reinstalled the app but I'm still unable to the badges.  Weird. Could it the MIUI issues? I have Redmi Note 9 Pro with MIUI 13.0.2.

**Comment by vitorpamplona** [comment]
There was a bug fix implemented recently. Let me release a new version to see if it fixes it.

**Comment by kirillkovalenko** [comment]
I created this ticket because I wasn't able to see that it's kind of already implemented. So I'm closing the ticket.

**Comment by vitorpamplona** [comment]
Did it work in 0.24.1? 

https://github.com/vitorpamplona/amethyst/releases/tag/v0.24.1
