### ISSUE TITLE
Request: Consider putting the apk on f-droid.org

### ISSUE THREAD

**Issue by improvethings** [vitorpamplona/amethyst#22]
It would be great to see the apk on https://f-droid.org/

**Comment by ValZapod** [comment]
Yes.

**Comment by SiriusLightning21** [comment]
For myself I use the Repo from izzysoft to update Amethyst on FDroid, it works great.

**Comment by vitorpamplona** [comment]
Address on https://amethyst.social

**Comment by Kortik7** [comment]
> For myself I use the Repo from izzysoft to update Amethyst on FDroid, it works great.

it got removed. why is that? no longer there, what happend?

**Comment by Kortik7** [comment]
> Address on https://amethyst.social

no longer there

**Comment by vitorpamplona** [comment]
F droid doesn't like our APK size and Google dependencies

**Comment by ValZapod** [comment]
> F droid doesn't like our APK size and Google dependencies

But it is open source. That should be enough.

**Comment by IzzySoft** [comment]
@vitorpamplona now that your app is listed at F-Droid.org since 2023-04-10, do you want me to keep it in my repo? Usually I drop an app after a decent overlap of about 2 weeks (especially the "bigger ones" :see_no_evil:) unless explicitly requested by its author to keep it in.

**Comment by mrusme** [comment]
Has the issue around the F-Droid APK been resolved? If so, I still cannot find the app on F-Droid unfortunately.

**Comment by RasheedAZ** [comment]
I installed the F-droid version previously... but now it's removed?
