### ISSUE TITLE
[FEATURE] allow custom amount ZAP

### ISSUE THREAD

**Issue by ttpro1995** [vitorpamplona/amethyst#235]
**Is your feature request related to a problem? Please describe.**

Currently, it only allow zap 500 1000 1500.

**Describe the solution you'd like**

Allow custom amount ZAP, or add smaller denomination 50, 5

**Bounty (in Bitcoin sats) offered for the implementation**
Incentivize developers to work on your feature. Describe clear milestones to claim payment. 

**Additional context**
Add any other context, video, or screenshots about the feature request here.

**Comment by vitorpamplona** [comment]
You can click and hold in the Zap button to change amounts :)

**Comment by maxmoney21m** [comment]
It might be nice to add a button to the zap popup for zapping that amount one time without adding it to the list, WDYT?

**Comment by Chemaclass** [comment]
Great idea, @maxmoney21m. That will definitely help people being aware of it.

**Comment by vitorpamplona** [comment]
added on https://github.com/vitorpamplona/amethyst/pull/319
