### ISSUE TITLE
[BUG] Profile banner image is blurry

### ISSUE THREAD

**Issue by Radiokot** [vitorpamplona/amethyst#247]
**Describe the bug**
The profile header banner is blurry.

**To Reproduce**
1. Go to someone's profile having a banner 
2. Notice the image quality

**Expected behavior**
The banner is scaled to the container width and doesn't lose quality.

**Video and Screenshots**
<img src="https://user-images.githubusercontent.com/5675681/224283705-d2eb1719-5771-44dc-9ed3-5553e5628bc5.png" width=400 />

**Device (please complete the following information):**
 - Phone Brand/Model [e.g. Pixel 7 Pro]: Galaxy S20 FE
 - Android Version [e.g. 33]: 33
 - App Version [e.g. v0.20.3]: 0.24.1

---

The issue is caused by forcing the width of 200 px for all the proxied images:
https://github.com/vitorpamplona/amethyst/blob/9cf7cc4e5d8264eb5161cc3b8c4f9b80ffe69c19/app/src/main/java/com/vitorpamplona/amethyst/ui/components/AsyncImageProxy.kt#L21-L22
I see it is done for efficient caching, but the banner quality is a drawback. I think on tablets with high pixel density we'll see more places with miserable quality.

**Comment by vitorpamplona** [comment]
Yep, I want to not pass banners through the resizer (go direct to the source)... But the UserProfile page is already slow... I am currently trying to speed the user page up so that we can load full-width banners
