### ISSUE TITLE
If I click for ex, 5 times in a message on a thread, the android back button needs to be clicked 6 times to go to the previous window.

### ISSUE THREAD

**Issue by bitcoinuser** [vitorpamplona/amethyst#25]
Hi,

If I click for ex, 5 times in a message on a thread, the android back button needs to be clicked 6 times to go to the previous window.

See the video.

https://user-images.githubusercontent.com/1178856/214207140-9599c289-196b-4918-96a3-688df28fe4e7.mp4

**Comment by KotlinGeekDev** [comment]
Please, which version of Amethyst are you using?

**Comment by bitcoinuser** [comment]
> Please, which version of Amethyst are you using?

The latest 0.10.2 I think.

**Comment by vitorpamplona** [comment]
Yep, I confirm the issue. I am not filtering out when a note click points to itself.

**Comment by KotlinGeekDev** [comment]
OK.
