### ISSUE TITLE
[BUG] v0.24.1 crashes when opening notifications view

### ISSUE THREAD

**Issue by djkazic** [vitorpamplona/amethyst#250]
**Describe the bug**
When I go to my notifications the app crashes.

**To Reproduce**
1. Go to 'Notifications'

**Expected behavior**
Notification view renders

**Device (please complete the following information):**
 - Phone Brand/Model: Pixel 5A
 - App Version: 0.24.1

**Comment by vitorpamplona** [comment]
What's you public key (npub)? I can log in and get the stack trace

**Comment by djkazic** [comment]
`npub1xw0g0f9dtve2075gc6jk5ed9808ma2zet2rttkrjqx3ekpqgc2wqrfy3xc`

**Comment by vitorpamplona** [comment]
Thank you!

Fixed here: https://github.com/vitorpamplona/amethyst/commit/78261ccd9434e1423f8e0b887d44be3a78ebadf7 

New version soon
