### ISSUE TITLE
[BUG] unfound posts in notifications makes bell lit forever

### ISSUE THREAD

**Issue by djkazic** [vitorpamplona/amethyst#252]
**Describe the bug**
My notifications bell stays lit

**To Reproduce**
1. Look at bell for notifications when there is an unfetchable post in the feed

**Expected behavior**
Bell should not be lit after scrolling past posts

**Device (please complete the following information):**
 - Phone Brand/Model [e.g. Pixel 7 Pro]: Pixel 5A
 - App Version [e.g. v0.20.3]: 0.24.2

**Comment by vitorpamplona** [comment]
This was solved a few weeks ago. I am closing it for now, but let me know if the bug is still there.
