### ISSUE TITLE
[BUG] Issue with NIP-05 identifier interpretation

### ISSUE THREAD

**Issue by theDavidCoen** [vitorpamplona/amethyst#259]
**Describe the bug**
Amhetyst seems not able to interpret some NIP-05 identifier, in particular the ones with the name "_".

An example:
```
{
  "names": {
    "_": "a976156de0384616921e32bfc8314cc647d33843af649d2d91faabb2450b808d"
  }
}
```

which gives: `_@davidcoen.it` since is in my domain .well-known folder.

"_" name is used in order to show just the domain name in the NIP-05 field of the client's UI.

**Expected behavior**
Amethyst should consider the NIP-05 identifier as valid and show just the domain in the NIP-05 field of the UI.

**Video and Screenshots**
![Immagine 2023-03-11 113430](https://user-images.githubusercontent.com/38695835/224479490-ce8ebf32-e086-4d45-838f-57bd71591051.png)
![Screenshot_2023-03-11-11-34-43-775_com vitorpamplona amethyst](https://user-images.githubusercontent.com/38695835/224479503-2236f9ff-9b0f-4318-9b10-ddc61b4c0ea2.jpg)

**Comment by believethehype** [comment]
It works for me. Maybe there's another issue, like a space after : or something?

**Comment by theDavidCoen** [comment]
I modify my json.
Can you check in a few minutes @believethehype ?

**Comment by maxmoney21m** [comment]
Do you have the correct CORS header set?

**Comment by maxmoney21m** [comment]
@theDavidCoen check npub1dergggklka99wwrs92yz8wdjs952h2ux2ha2ed598ngwu9w7a6fsh9xzpc for an example of a working `_@` NIP-05 in Amethyst.

**Comment by theDavidCoen** [comment]
now Amethyst gives me the domain only (correct) but still a ! on the left.
No other clients give me this issue.

Also I have ```
<IfModule mod_headers.c>
    Header set Access-Control-Allow-Origin "*"
</IfModule>
```
in the .htaccess.

**Comment by maxmoney21m** [comment]
@theDavidCoen I dug a little deeper and found that there is indeed an issue on Amethyst (technically, it's an issue with Apache on your end, but we should support Apache since it's so common). I'll submit a PR momentarily and it'll be fixed whenever @vitorpamplona pulls it in. Here's how it looks for me now:

![image](https://user-images.githubusercontent.com/124794312/224737815-c357bf06-98c8-4318-b9a7-5b6b757cd06e.png)
