### ISSUE TITLE
Export Private Key?

### ISSUE THREAD

**Issue by jontstaz** [vitorpamplona/amethyst#27]
Hi,

Is there some way to export my private key which was generated in Amethyst during the first launch of the application? I've been trying to open the "Settings" button but the button seems to be broken as it doesn't do anything when it is pressed. I would assume if an "Export Private Key" button would be anywhere, it would be within the settings but I can't access them as mentioned.

Is there any way I can somehow export my private key? Many thanks in advance.

**Comment by j-mizzle** [comment]
I'm wondering the same. Wanted to test some other clients but rather not make another profile. Hopefully settins is fixed soon.

**Comment by vitorpamplona** [comment]
The latest version has an nsec button in your profile. It's rudimentary, but it works.

**Comment by ValZapod** [comment]
> The latest version has an nsec button in your profile. It's rudimentary, but it works.

Thank you for that.
