### ISSUE TITLE
[BUG] If we click outside of the impulsinar and Citar buttons to close it, opens the post, but shouldn't.

### ISSUE THREAD

**Issue by bitcoinuser** [vitorpamplona/amethyst#272]
Hi,

[BUG] If we click outside of the impulsinar and Citar buttons to close it, opens the post. But shouldn't. See the video:

https://user-images.githubusercontent.com/1178856/225020493-6a577988-1208-4238-8f84-5c5069d7f29b.mp4

**Comment by bitcoinuser** [comment]
Hi, @geovnn I saw you fixed this problem for likes and zaps but not for repost button. Could you please take a look here too. Thanks

**Comment by geovnn** [comment]
Lol how did I miss it? Gonna fix it soon.
