### ISSUE TITLE
Gson and jackson

### ISSUE THREAD

**Issue by maxmoney21m** [vitorpamplona/amethyst#277]
There is a note in the build file that we should pick one instead of using both. I would like to offer a third alternative: neither. Kotlin's native JSON serialization tooling is pretty good, and it would probably be simplest to just use that. Also removes two more dependencies. Thoughts @vitorpamplona ?

**Comment by vitorpamplona** [comment]
1. We should use whichever is faster while using fewer resources (memory/CPU). The app is parsing 1000 jsons a second, so every millisecond counts. 

2. We need to make sure escaping follows what other Nostr clients are signing otherwise the parse, format functions break the hash check.

**Comment by maxmoney21m** [comment]
I think it'll be worth trying. Gson uses reflection and is generally slower. Kotlinx serialization is the fastest when it comes to working with strings, usually. I'll make a branch for testing, anyway. Not hard to swap things over.

**Comment by vitorpamplona** [comment]
Keep in mind we are bypassing reflection with our own deserializers.

**Comment by maxmoney21m** [comment]
@vitorpamplona I have kotlinx.serialization working on a branch at least for the events (replaced gson so far, did not do jackson yet).

Would be great if you could do whatever benchmarks you like. Seems to work alright, everything looks normal in the app, but testing is not extensive so kind of hard to say for sure. One test currently broken, not sure why.

https://github.com/maxmoney21m/amethyst/tree/test/json-serializer

**Comment by vitorpamplona** [comment]
hum... this one we should really be sure it's better before merging. We might do a benchmark module for the app. We can download a good number of events (say... export from somebody's use/profile into a file) and use those as benchmark, measuring time, memory and energy used.

**Comment by vitorpamplona** [comment]
This leads me to want to separate the `.services.model` package into it's own library and stress test the hell out of it.

**Comment by vitorpamplona** [comment]
We have settled with Jackson. It's still the fastest and less memory-consuming option to parse the JSON.
