### ISSUE TITLE
"Happy Tuesday" message do not appear on chat window.

### ISSUE THREAD

**Issue by bitcoinuser** [vitorpamplona/amethyst#28]
Hi,

"Happy Tuesday" message do not appear on chat window.

I restarted Amethyst and same problem. Looks like the problem only happens on Nostr channel.

https://user-images.githubusercontent.com/1178856/214296995-2323b27c-aef9-4637-ad80-a48de4dcbf7a.mp4

**Comment by vitorpamplona** [comment]
Hum... that's probably a reaction, not a message... interesting.
