### ISSUE TITLE
[FEATURE] options/features/language switcher

### ISSUE THREAD

**Issue by chiajlingvoj** [vitorpamplona/amethyst#298]
I think it would be great to have a way to adjust options/preferences/other settings within Amethyst. For example, the UI language right now always follows the system settings and there is no way to set a different one other than changing system language. The problem becomes: what if the user wants to use a different one, or the desired one is not available as a system language choice?

The options panel could also be a place to adjust other settings that other feature requests have raised such as filtering/visibility/etc.

Alternatively regarding lang choice: I know that in Android 13 (and possibly earlier?) it is possible to change UI language on a per-app basis, but I guess it has to be enabled somehow within the app?

I'd be happy to put a 50k bounty on this!

**Comment by KotlinGeekDev** [comment]
Would like to tackle this. Please @vitorpamplona any preferred UI/UX suggestions?

**Comment by chiajlingvoj** [comment]
> 

related to #394

**Comment by vitorpamplona** [comment]
So want to minimize options as much as possible. That being said, @3j2009 has some good UIs here: https://github.com/vitorpamplona/amethyst/issues/394 

The only question is: are these per account or one for all accounts? And how do we make that clear in the UI?

**Comment by KotlinGeekDev** [comment]
@vitorpamplona  I thought of 3 options.
1. Per the UI mock-up on the option in the settings screen, we can just clarify it in the small text for the option. Something like:
    <h2>Post editing</h2>
    <h4>Edit your posts up to 30s after editing. Limited to this account.</h4>

 2. We can make it a section called Post editing, and inside, have different toggles.
 3. We can make a tri-state toggle, with options, Off, One(For the current account), All(for all accounts)

**Comment by KotlinGeekDev** [comment]
@vitorpamplona  we can have a dropdown menu with the languages, and a dual-state toggle beneath it to choose applying to one account or all accounts.

**Comment by davotoula** [comment]
Android 13 allows per-App language preferences in System settings (App needs to support it though).

Would implementing this be worth the effort considering the small market share of android 13?

**Comment by KotlinGeekDev** [comment]
That really is the question.

**Comment by davotoula** [comment]
I'll have a look at this. If it doesn't complicate the base code it could be a nice ux enhancement

**Comment by KotlinGeekDev** [comment]
Hmm @vitorpamplona @davotoula the only thing remaining here is app-wide or per-account language settings. Cc @chiajlingvoj @greenart7c3

**Comment by davotoula** [comment]
I just realised that the burger menu has a mix of account specific and global settings.

Maybe all global settings should be inside a "Global settings" menu item?

**Comment by KotlinGeekDev** [comment]
I wonder how the UI/UX will be like.

**Comment by KotlinGeekDev** [comment]
@vitorpamplona I think this issue can be closed. @davotoula I guess the global settings menu may be part of the settings re-arrangement mentioned in #734 .

**Comment by vitorpamplona** [comment]
> Maybe all global settings should be inside a "Global settings" menu item?

There will be Account-based Settings and App-based Settings. We just need to make it clear on the UI which one is which.
