### ISSUE TITLE
[FEATURE] LNDHub and/or LNBits integration + Like & Repost Auto-ZAPs right from Amethyst

### ISSUE THREAD

**Issue by Perlover** [vitorpamplona/amethyst#300]
**Is your feature request related to a problem? Please describe.**

Let's say I like to send zaps. But to put a Like, make a Repost (Ok - Renotes ;-) and then send a zap, while you still need to open an external wallet (sometimes wait for connection to nodes), then time is spent on sending a zap, then you need to exit the wallet and return back to the feed. At the same time, there are a lot of problems here - different wallets have a different exit back to Amethyst (Zeus opens directly in Amethyst and you need to make a total of 4 clicks to return. There are fewer clicks in the SBW wallet, it opens as an independent application, but you have to wait for connections to nodes). In general, it takes a huge amount of time to make one zap. At the same time, a zoo of applications is obtained if the user has several wallets.

**Describe the solution you'd like**

In Amethyst, you can build work with a lightweight third-party API, such as LndHub and LNBits. The user can use custodial wallets for zaps (LndHub servers or LNBits Demo site for example), or their own solutions (The plugin LNBank of BTCPay brings the LndHub API and user can install own LNBits server).  At the same time, it is proposed to build the interface in such a way that it is convenient:

- Since Amethyst is now a multi-account, it is necessary that at the level of each account you can configure your LndHub URI or LNBits URI in the settings (preferably, in addition to the text field, it is possible to scan the QR code with the URI). For example, a separate item in the left panel, like "Security Filters". I think that it is necessary to separate the "wallets" for outgoing payments, since a user can have a personal wallet for a personal account, and, for example, a second one for a working (corporate) one.
- Provide the user with the opportunity to specify separately for Like and Repost the amount in sats, which will be sent automatically if he clicked Like or Repost (**Auto-ZAP**). You can do this in the likeness of ZAP amounts - click on the icon, hold it and a field will appear to specify the default amount to the site.
- In order for the user to see that the Auto-ZAP is active, place a small lightning bolt icon next to the like or repost icon. Disabling Auto-ZAP is also a long press and there is somewhere to make the disable button (for example, checkbox).
- For the zaps themselves, the interface remains the same, except that when selecting the amount of sats, the Amethyst automatically has to send a ZAP itself through API, without trying to launch a third-party LN wallet.
- Sending should work in a separate thread without blocking the interface.
- If the recipient of the ZAPs does not have an LN address to receive, then Like and Repost are quietly processed as normal Like & Repost.
- In order for the user to understand that zap has been sent, this can be shown by a yellow lightning icon next to the Like & Repost icon: gray icon - ZAP has not been sent, but default sending is set, and yellow lightning icon - ZAP has been sent. There is probably one inconvenience here - if the feed is updated, we will lose the information that we sent auto-ZAP, for example, for a Like. In this case, it will already look like a "yellow lightning" of a regular zap (as if we sent a regular zap). But I think you can put up with this :) Or immediately show auto-zap as a normal active sent zap.

**Bounty (in Bitcoin sats) offered for the implementation**

I am ready to pay for the implementation of this feature in the amount of 300K sats for example (as ZAP in Nostr). If it requires more time and effort, I'm even willing to increase the amount to 500K sats. I think someone will join me too ;-)

**Additional context**

Having read the description of LndHub now, it seems REST API too as LNBits. LndHub is very desirable, since only it of these two is supported by the BTCPay server, which is installed by many people (via the LNBanks plugin, which, among other things, allows you to divide the balance of one Lightning node between different BTCPay accounts, which makes it a good candidate for a custodial wallet solution for users who do not want to install their BTCPay).

**Comment by vitorpamplona** [comment]
Together with https://github.com/vitorpamplona/amethyst/issues/196 makes it a 1300 bounty :)

**Comment by InnocuousFinch** [comment]
Custodial solutions should not be acceptable. Thankfully you could build a fully contained self-custodial LN wallet in Amethyst using [Breez SDK](https://breez.technology/sdk/)

I know it wasn't the original request, but if a self-custodial LN wallet is integrated inside Amethyst I will donate 250k sats.

Let's start getting users to using self-custodial LN wallets instead of custodial wallets.

**Comment by sethforprivacy** [comment]
I'll echo @InnocuousFinch and add 250k sats if this is done non-custodially, i.e. via the Breeze SDK linked.

**Comment by Perlover** [comment]
> Custodial solutions should not be acceptable. Thankfully you could build a fully contained self-custodial LN wallet in Amethyst using [Breez SDK](https://breez.technology/sdk/)

As far as I know, the Breez wallet has an LND + Bitcoin node inside itself. I am against it, because the user will have to install Breez or have a software copy of all this inside Amethyst. And all this for the sake of a few sats in ZAPs. I can also assume that sending ZAPs will require a connection to the nodes and synchronization with the blockchain before zap. In addition, the user will have to take care of backups (Google Drive?). If this is the F-Droid version of Amethyst, then there will be a problem with this. There will also be a problem for those who don't want to use Google Drive. And many other disadvantages.

**Comment by InnocuousFinch** [comment]
> As far as I know, the Breez wallet has an LND + Bitcoin node inside itself. I am against it, because the user will have to install Breez or have a software copy of all this inside Amethyst.

You would be incorrect. The user would not need to install anything. The Breez SDK (software development kit) is not Breez Wallet.

The Breez SDK leverages [Greenlight](https://blockstream.com/lightning/greenlight/), which is both a bitcoin and lightning node hosted for you, and allows you to add a functional, self-custodial Lightning wallet with on-chain interoperability with only a few lines of code. Additionally, the keys to sign transactions stay on the device so the user always retains custody of funds.

Breez SDK was literally built for this type of use case.

**Comment by vitorpamplona** [comment]
There is a NIP-46 equivalent that Alby is trying to design that could help here. Essentially, in the name of micro apps, Nostr clients talk to wallets over a standard Nostr protocol through relays. This means that each LN implementation will have to offer a module that connects to Nostr directly instead of requiring Nostr Clients to use all these different LN interfaces. That could mean a better compatibility layer and better separation between Nostr Clients and Wallet services.

**Comment by InnocuousFinch** [comment]
> All non-custodial solutions will require the user to take a responsible approach to channel reservation.

This isn't remotely true. If Amethyst used Breez SDK to integrate a LN wallet directly, it would be leveraging Greenlight so users would not need to manage channels. Greenlight is a hosted BTC/LN node so you wouldn't need the node to be on the phone. 

This is all handled for you automatically on the back end by the LSP.

**Comment by Perlover** [comment]
> Greenlight is a hosted BTC/LN node so you wouldn't need the node to be on the phone.

What exactly does this mean ("Greenlight")? If this node works at the Breez company, then this is a not 100% custodial solution. Tomorrow they will shut down their server, and everyone who worked through the Breeze SDK will stop working. Let's say you can close the channels and return the funds, and then what?

If Greenlight is a software suite that everyone can install on their own server, then the options I have suggested also meet the requirements: you can configure your node on LndHub or LNBits.

**Comment by InnocuousFinch** [comment]
It's self-custodial because the keys to spend the bitcoin remain on your device and only on your device. No need to host a node for it to be self-custodial. I've linked Breez SDK and Greenlight links in prior posts. Please do some reading before responding with more FUD about something you do not understand.

Screenshot directly from the Breez SDK website:

<img width="572" alt="Screenshot 2023-03-21 at 11 00 29 AM" src="https://user-images.githubusercontent.com/118941419/226668645-b9e4c7d1-f9f9-4d56-9be8-9bc04149eed4.png">

**Comment by Perlover** [comment]
> There is a NIP-46 equivalent that Alby is trying to design that could help here

Is there no mistake? Now I'm reading what this NIP-46 is for and there is a goal so that the application can sign anything with the Nostr key at the request of any service.

**Comment by vitorpamplona** [comment]
> > There is a NIP-46 equivalent that Alby is trying to design that could help here
> 
> Is there no mistake? Now I'm reading what this NIP-46 is for and there is a goal so that the application can sign anything with the Nostr key at the request of any service.

The idea is to use the same concept between Nostr Client and Wallet.

**Comment by Perlover** [comment]
> It's self-custodial because the keys to spend the bitcoin remain on your device and only on your device. No need to host a node for it to be self-custodial

What you have written and quoted - there is no complete understanding. You have already written so much, but you have not answered - where does the node work and whose is it?

**Comment by InnocuousFinch** [comment]
It is hosted by Blockstream. Please read: https://blockstream.com/lightning/greenlight/

**Comment by Perlover** [comment]
> Remark: in order to build the Breez SDK you need to have access to the Greenlight repository. Greenlight will eventually be open-sourced (with an MIT license), but is not yet public. To access Greenlight, please email us at [contact@breez.technology](mailto:contact@breez.technology).

some kind of crap.

**Comment by vitorpamplona** [comment]
This is what I was talking about 

https://github.com/getAlby/nips/blob/master/47.md

**Comment by Perlover** [comment]
From the user's point of view, I didn't find any changes in the interface plan. It's just about the internal stuffing in terms of the fact that Amethyst will be able to work with a certain Wallet Connect API, which will be like a proxy? To be honest, I haven't figured anything out yet.

**Comment by Perlover** [comment]
From the user's point of view, I didn't find any changes in the interface plan. It's just about the internal stuffing in terms of the fact that Amethyst will be able to work with a certain Wallet Connect API, which will be like a proxy? To be honest, I haven't figured anything out yet.

P.S. Before answering, I started Googling "Wallet Connect" and found some kind of wallet-application connection protocol. There were a lot of shitcoins and I am very skeptical about your words. But after reading your post in Nostr, I realized that that site and protocol have nothing to do with your implementation. I realized that it was about NIP-47 (I haven't read it yet). It is probably worth clarifying this, otherwise many may be misled.

**Comment by Perlover** [comment]
I zapped your note note1dv6k9mqmlw5ezmzk353hm3kcr6ajhjmluqvgztke5ykp6mjppr3sgvency 200K sats. This is the first main step of your NIP-47 so I decided to send 2/3 of my promised bounty :) Thanks!

**Comment by vitorpamplona** [comment]
oh, hey, thanks! Were you using the code alby provided?

**Comment by Perlover** [comment]
> oh, hey, thanks! Were you using the code alby provided? 

No. Can you give to me link of code?

**Comment by Perlover** [comment]
Can I close this issue?

Generally speaking, most of what is described here is implemented ("Wallet Caonnect" protocol and one-click zapping (when the Amethyst has only one value zap setting)). I sent the zaps in the amount that I promised (after the [first 200K sats](https://github.com/vitorpamplona/amethyst/issues/300#issuecomment-1482787720) I sent them through zap to Nostr, just didn't report it, but I think you got them ;-)
