### ISSUE TITLE
Android Camera npub QR Scan does not work [BUG]

### ISSUE THREAD

**Issue by alltheseas** [vitorpamplona/amethyst#301]
**Describe the bug**
When Android phone camera with Amethyst installed scans a npub profile QR displayed on Damus, Android may:
1) ask which app to use to open the link, and not display Amethyst
2) open default browser, and display the npub string in the search bar

**To Reproduce**
1. Go to camera on android
2. Scan QR npub (e.g. on Damus)
3. See unexpected result (i.e. npub profile view does not load)

**Expected behavior**
When Android camera scans a QR containing a npub (e.g. from Damus), Amethyst should automagically open, and navigate to the npub's profile page. 

**Video and Screenshots**
![scan amethyst snapshot](https://user-images.githubusercontent.com/64376233/226703696-d96c4b33-959a-412d-a089-c95ac386bacf.png)

**Device (please complete the following information):**
unknown

**Bounty (in Bitcoin sats) offered for a solution**
-

**Comment by vitorpamplona** [comment]
It will never work. :( 

Google does not allow custom schemes in their main Camera.

**Comment by vitorpamplona** [comment]
Gotta use the scan function in the app. :)
