### ISSUE TITLE
[FEATURE] Simple one page website for amethyst project

### ISSUE THREAD

**Issue by taxitaxitaxi-taxi** [vitorpamplona/amethyst#306]
Simple responsive one page website was made for the amethyst project.  comments welcome

[amethyst_onepage.zip](https://github.com/vitorpamplona/amethyst/files/11047274/amethyst_onepage.zip)

**Comment by vitorpamplona** [comment]
Moved this idea to a simple linktree from another Nostr client: https://nostree.me/_@vitorpamplona.com/how-to-install-amethyst
