### ISSUE TITLE
Twitter or Reddit layout?

### ISSUE THREAD

**Issue by vitorpamplona** [vitorpamplona/amethyst#309]
It's funny how Twitter's base layout is more wasteful but it feels more organized than a "full-screen" one, even though pictures and videos look much better in the full-screen version. 

Reddit | Twitter
--- | ---
![Screenshot_20230323-161149](https://user-images.githubusercontent.com/532031/227342908-891dc6de-a881-4faa-aae4-3177f6fede3d.png) | ![Screenshot_20230323-161206](https://user-images.githubusercontent.com/532031/227342914-c79b9cf0-f191-496a-9fe3-b1fb8f202ab6.png)

**Comment by climardo** [comment]
Card-style ftw 🙌

**Comment by 3j2009** [comment]
@vitorpamplona Both options have pros and cons which you mentioned. I think the answer should be based on what style of content you wish to subtly encourage on the platform. 

The **twitter** layout images are smaller and therefore hold a more equal weight to the text accompanying them; making for a more text oriented platform. This layout encourages a type of citation of the image/tweet/link/ad.
In that layout, as a user my eyes would:

1. Glance image
2. Read text to understand context for the image
3. look at the image again now having read the text and understood it's relation to the image.


However, the **Reddit** layout makes the image content far more engaging, which is a good thing IF there is enough content displayed in the image itself for the user to understand the post without having to necessarily read any accompanying text. This type of content layout is good for things like Memes, videos and pictures and it's probably why Reddit uses that layout, as Memes often have text written on the image and don't necessarily require exterior text to accompany them.

![image](https://user-images.githubusercontent.com/126127093/227810307-4f8684d0-4b91-448c-897f-6a05defcd979.png)

**Comment by Bardesss** [comment]
I like the reddit layout more. Also better for long form posts.

**Comment by vitorpamplona** [comment]
Since we now have the stories feed for images and videos, I think the conversation here is mostly settled. We don't need to switch to Reddit mode to make the media experience more appealing.
