### ISSUE TITLE
Display NIP-05 identifyer

### ISSUE THREAD

**Issue by Dielan** [vitorpamplona/amethyst#31]
I know Amethyst allows us to set our NIP-05 but it doesnt really display it. Other apps do this today in their own ways. Typically adding it to the same line as the handle in different colors or font. Can we have this?

**Comment by TiKawamoto** [comment]
The field is there but the feature isn't implemented. It's listed as a pending feature.

**Comment by chiajlingvoj** [comment]
NIP-05 is displayed in profile now, can close?

**Comment by vitorpamplona** [comment]
Closing this as resolved.
