### ISSUE TITLE
Can't invite to group chat

### ISSUE THREAD

**Issue by Dielan** [vitorpamplona/amethyst#32]
Amethyst displays (I believe these are Channels, which Anigma is known for) group chats, and allows us to create them, but we can't find their channel IDs nor input them. Unclear how we are meant to create and use these just within Amethyst

**Comment by vitorpamplona** [comment]
Hi Dilan,

Thanks, we are still refining the interface. You can insert your channel id in the search field and it should present you the opportunity to join . 

To see the id, just press the note button up top in the channel screen.
