### ISSUE TITLE
[BUG] Some reposts of posts by non-followee do not appear in the user timeline

### ISSUE THREAD

**Issue by heguro** [vitorpamplona/amethyst#320]
**Describe the bug**
Some reposts of posts from users you don't follow don't appear in the user timeline.
If you manually load the original post using a different method and return to the timeline, it will appear correctly.

**To Reproduce**
1. Login with npub/nsec which has few following users
2. Open the user timeline
3. You can't see some reposts
4. Open the profile of the user who reposted or posted the original note and find the original note
5. Return to the user timeline
6. You can see reposts which found in step 4

**Expected behavior**
You can see all reposts in step 3 without any tweaking.

**Video and Screenshots**
Tested with my sub account that only follows my main/sub accounts: `npub1leyuldps62y23eh9n8aphcagzy2dyz4cful8485y355y2q2rdd8qyu9kfq`

https://user-images.githubusercontent.com/65112898/228396883-cb83395f-4cfe-4ac9-b3c5-6506adb94734.mp4

**Device (please complete the following information):**
 - Phone Brand/Model [e.g. Pixel 7 Pro]: Pixel 6a
 - Android Version [e.g. 33]: 33 (Android 13)
 - App Version [e.g. v0.20.3]: v0.30.1 (Google Play Universal)

**Comment by KotlinGeekDev** [comment]
Please @heguro does this happen on newer versions as well?

**Comment by heguro** [comment]
> Please @heguro does this happen on newer versions as well?

Yes, it still happens in v0.32.1.

**Comment by KotlinGeekDev** [comment]
Please @heguro check to see whether this issue still exists in the latest version.

**Comment by heguro** [comment]
(Sorry for too late response, I confirmed this issue doesn't occur in latest version)
