### ISSUE TITLE
[FEATURE] Allow importing nsec from QR code

### ISSUE THREAD

**Issue by sethforprivacy** [vitorpamplona/amethyst#328]
**Is your feature request related to a problem? Please describe.**
One of the core issues with Nostr today is that generating and storing a Nostr private key is cumbersome and insecure by default. A solution to one of the problems (namely secure storage and backups) is to generate and store private keys on a secure hardware device (like Foundation Passport) and export it only when necessary to sign into an app like Amethyst.

This simplifies backups (keys are derived from a master seed via the same approach as BIP 85) and allows you to never store your key in a password manager, text file, etc.

**Describe the solution you'd like**
When logging into Amethyst, allow scanning in the nsec formatted key via QR code. When this approach is used, prevent export of the key in the app itself to provide better security around someone getting your nsec from your phone being open.

**Bounty (in Bitcoin sats) offered for the implementation**
I'm offering 500,000 sats for this once implemented and usable in Amethyst binaries.

(An additional 1.25m sats have been pledged by @BitcoinQnA and an anonymous Nostr user)

**Total bounty (as of April 3rd): 1.75m sats**

**Comment by sethforprivacy** [comment]
An example QR code is below, note that it's just a standard nsec formatted key as raw text:

![image](https://user-images.githubusercontent.com/40500387/229552159-f98d1331-d33d-4d6a-b0b2-345539248d30.png)

**Comment by vitorpamplona** [comment]
I think it is an extremely dangerous idea to transfer private keys via a QR code. 

QR Codes are designed for sharing. Since users can't see what's inside the QR without an electronic device, I expect private keys to leak by simply misusing the QR. For instance, I expect people to scan it with Android's camera, which immediately checks Google Search for more information after parsing the contents of the QR.  

But I will merge it if somebody makes a reader in the login page.

**Comment by vitorpamplona** [comment]
An NFC interface would make a lot more sense for this use case.

**Comment by sethforprivacy** [comment]
The tricky thing is that we need *some* way to properly import an nsec from a secure device without copy-pasting and exposing the key to your keyboard etc.

IMO QR code is a low barrier of entry to making it easy to do, along with appropriate warnings that you shouldn't scan it with other apps.

Our release notes around the feature will include something like this:

> Please note that if you export keys as QR codes, you should be careful what you scan them with! Apps like Google Camera will often open the content of the QR code in your default search engine, exposing that key to Google etc.

Using QR codes allows us to bypass many of the other issues (like generating keys in Amethyst and exporting via copy-paste, exposing nsec to clipboard attacks, online clipboards (like Google Keyboard), etc.

**Comment by sethforprivacy** [comment]
One other note -- we also allow exports to microSD as a raw text file with `nsec`, but that is a far inferior approach for both security and UX in my opinion.

I think a one-time export + import of QR is the best middle ground to allow you to normally keep your private key locked away tightly.

**Comment by sethforprivacy** [comment]
Already done in v0.31.4 🤯

note1vtsxla366x5wrde77fstz3uqpng0j6u8qd8q6dw60pj5kr04kqqq4plwzd

**Comment by vitorpamplona** [comment]
Bounties work.

**Comment by BitcoinQnA** [comment]
Paid my contribution.

**Comment by sethforprivacy** [comment]
1.5m sat bounty paid. Thanks again so much, @greenart7c3!

**Comment by vitorpamplona** [comment]
We need to figure out how to do that well. Right now there is not difference between this method and others... I am wondering if this should be inside the QR itself, as a NIP19 option.

**Comment by sethforprivacy** [comment]
Would it make the most sense to open that as a new issue?

**Comment by vitorpamplona** [comment]
I kinda want to make that a NIP to make sure the behavior is consistent with all apps. It feels weird to block exporting of something the user knows the app has. I am sure this will trigger a lot of people in the wrong way.

**Comment by vitorpamplona** [comment]
PS: right now if they have biometric unlock setup, the fingerprint scanner is required to export the key.

**Comment by sethforprivacy** [comment]
True, there is some benefit to redundancy on keeping it available to export, but also more security exposure.

Probably best left to user choice somehow! I'll go ahead and close this and let you proceed how you see fit, I think both approaches have merit, though I lean towards blocking exports if imported via QR.
