### ISSUE TITLE
[BUG] Unencrypted public DM response 

### ISSUE THREAD

**Issue by MaxHillebrand** [vitorpamplona/amethyst#333]
**Describe the bug**
When replying to a DM in the notification tab, a public unencrypted note is published that references the encrypted DM. 

**To Reproduce**
1. Go to notifications 
2. Click reply to a DM notification
3. Write a note, assuming it is private, send it
4. See error, the not is public and references the encrypted DM note. 

**Expected behavior**
Never ever send DM messages unencrypted. 

**Example**
note1czmw59q3gm3k60z60f52kwl9wmkdzvg6l8ex5ue6j9m87ze8uehqw6u92e

**Device (please complete the following information):**
 - Phone Brand/Model: Pixel 6
 - App Version: 31.3

**Comment by vitorpamplona** [comment]
Thanks Max! 

It was fixed yesterday: https://github.com/vitorpamplona/amethyst/commit/a8a3915c8d7ad27b597d0bf018f97a79b44bd6bf

**Comment by MaxHillebrand** [comment]
That's the best way to respond to a bug report, awesome, thanks!
