### ISSUE TITLE
en_fr.zip and en_lv.zip automatically downloaded while using Amethyst.

### ISSUE THREAD

**Issue by dopapopa1** [vitorpamplona/amethyst#335]
Can someone explain this? I think I might have not cancelled one of the attempts in time, but can't find where the zip file went to or came from. It happened while using Amethyst

![signal-2023-04-05-124114_002](https://user-images.githubusercontent.com/129986986/230160609-33d048c9-4bbb-4a00-9d84-c23569125c57.jpeg)

**Comment by KotlinGeekDev** [comment]
Please @dopapopa1 what system(or app) language(s) do you use?

**Comment by dopapopa1** [comment]
@KotlinGeekDev English.  Guessing these are language packs but why/how/where are they downloading to? The only permission granted is to photo/videos. I just had "en_sv.zip" automatically download as well.

![en_sv](https://user-images.githubusercontent.com/129986986/230168204-f4632ece-929a-4915-8fea-33c144781c6b.jpeg)

**Comment by KotlinGeekDev** [comment]
@dopapopa1 that happens when you encounter a foreign language in your feed. The app downloads the corresponding language pack in order to translate it into English.
