### ISSUE TITLE
[FEATURE] Add Comments or Notes field to expanded zap menu

### ISSUE THREAD

**Issue by RenegadeButcher** [vitorpamplona/amethyst#338]
Other clients including Snort and Damus all a comment or note to be sent with a zap, so the receiver can view it in their wallet.  This should be standard across clients.

This would be a big benefit to content creators, allowing messages to be sent with value for value payments much like boosts in Podcasting 2.0.

**Comment by vitorpamplona** [comment]
You can double click and send a note with the zap.

**Comment by RenegadeButcher** [comment]
Thank you!  I feel dumb 😂

Perhaps this could show up in the expanded menu on a long press?  But much
appreciated!
