### ISSUE TITLE
Edit profile button not appearing correctly on my profile

### ISSUE THREAD

**Issue by greenart7c3** [vitorpamplona/amethyst#34]
I'm using a Google pixel 6a and the edit profile button is not rendering correctly 

![Screenshot_20230125-094346.png](https://user-images.githubusercontent.com/115044884/214566681-d1288c7a-8f24-4766-95dd-43d4b7decd9e.png)

**Comment by vitorpamplona** [comment]
Fixed on v.10.5, coming to the play store soon
