### ISSUE TITLE
[BUG] After installing Amethyst, Android system becomes unstable and freezes

### ISSUE THREAD

**Issue by elbakkayg** [vitorpamplona/amethyst#347]
After installing Amethyst on Android 10, the Android system becomes unstable and freezes the screen for a few seconds and the applications at launch as well.

 - Nokia C3
 - Android 10
 - Amethyst v 0.32.3 (118)

**Comment by vitorpamplona** [comment]
Does this still happen?

**Comment by elbakkayg** [comment]
the problem no longer exists after the updates
