### ISSUE TITLE
Adding custom relays doesn’t seem to “stick”

### ISSUE THREAD

**Issue by pjv** [vitorpamplona/amethyst#35]
If I add my self-hosted relay, it goes up into the list of relays but then no matter how I leave that screen (pressing the purple post button, or pressing the grey cancel button, or gesturing “back”), when I re-enter that relays screen my relay is not there anymore.

I also tried deleting one of the default relays and that change is also not saved as far as I can tell.

Is the save functionality on that screen yet to be implemented?

**Comment by vitorpamplona** [comment]
Hum.. this seems to be working. Which version are you on?

**Comment by pjv** [comment]
0.10.4 - under grapheneOS which maybe could be a thing?

**Comment by vitorpamplona** [comment]
Does graphene block saving encrypted preferences in the app? That could be it.

**Comment by pjv** [comment]
I don’t know specifically about that, but I do know that graphene has substantial hardening that includes where and how apps can write. Some of that stuff is optionable so I’ll play with the app settings a bit and see if I can make it work and report back here.

**Comment by pjv** [comment]
None of the hardening / memory / storage app options in graphene made any difference. I assume that after making changes on the relays screen, pressing the “post” button in the upper right is the correct way to save those changes (let me know if that’s wrong).

I tried clearing the app cache and app storage and starting over from scratch but the same behavior occurs.

Another data point: the app does not forget my private key which I guess from the architecture notes it is poking into the android keystore. 

In use, the app is accumulating both data storage and cache, so it’s not being blocked from storing stuff. Could there be an issue with the encryption and decryption? 

I’m a long ways away from an Android dev and pretty allergic to Java. Anything I can do as a user to help debug this?

![image](https://user-images.githubusercontent.com/327716/214597224-3ae356fe-3ccd-4139-b3b3-f017937cb130.png)

**Comment by greenart7c3** [comment]
Not a graphene problem. It's happening with me too.

[Video](https://void.cat/P5p9ZMZ5FjnbhW11CefpxG)

**Comment by vitorpamplona** [comment]
@pjv 

So the app doesn't allow you to log off? Or what do you mean by it doesn't forget your private keys? 

When you press the log off button, it deletes the private key from the encrypted storage.

**Comment by pjv** [comment]
@vitorpamplona ahhh - sorry for the confusion. I can log off fine. I was just trying to say that the app doesn’t have any trouble saving some stuff - just doesn’t save changes to the relays.

**Comment by greenart7c3** [comment]
@pjv it's working for me now on the latest version. Can you test to see if it's working now?

**Comment by pjv** [comment]
@greenart7c3 @vitorpamplona Yup, not only is it working, when I updated to 0.10.7 the relay I added previously showed up in the list of relays without my having to re-enter it. So it was there all the time and the screen not showing it to me must have been a cosmetic thing.

Thanks for Amethyst @vitorpamplona - it’s looking great.
