### ISSUE TITLE
[FEATURE] Enable Private Relay Support NIP-42 [500k sats]

### ISSUE THREAD

**Issue by alltheseas** [vitorpamplona/amethyst#354]
## User Story

As a Amethyst user who wants to connect with a particular group of nostriches privately, I want to be able to connect to a private relay, so that I can read and share notes only with a specific group of nostriches.

### Acceptance Criteria

1. Amethyst user can connect to a private relay
2. Amethyst user has a method to provide authentication details to a private relay
3. Amethyst user can check visually if they are successfully connected to the private relay
4. Amethyst user can remove a private relay
5. Amethyst user can de-authenticate from a private relay

_implementation details_
[NIP-42](https://github.com/nostr-protocol/nips/blob/master/42.md)

Origin: https://iris.to/note1c6khgk6phxzhq7hh2v32nhzrvlyn4y2ctk6h0kgtgfrgrh7y7e5qma8ykl

**Bounty (in Bitcoin sats) 500k sats by Mazin npub18kzz4lkdtc5n729kvfunxuz287uvu9f64ywhjz43ra482t2y5sks0mx5sz

**Additional context**
Introduced feature request to Damus (iOS), and Iris (web) as well. 

Why is this important: private relays provide differentiation and novelty compared to incumbent twtr.

**Comment by nostr-wine** [comment]
We'll offer a 500k sats bounty per client for this feature.

**Comment by nostr-wine** [comment]
Any takers?

**Comment by vitorpamplona** [comment]
Yep. I will start coding soon. Can somebody arrange a few test credentials to existing private relays?

**Comment by nostr-wine** [comment]
Awesome. Yes - I've given your pubkey access to filter.nostr.wine for a year. If you connect to wss://filter.nostr.wine (no path) it will prompt you to AUTH on connect. If you need any other accounts, let us know.

**Comment by vitorpamplona** [comment]
Done: https://github.com/vitorpamplona/amethyst/commit/14bc1fb7d46bb086047dc906639b596a204e3230

New version soon. It will be available on v0.36.0

**Comment by nostr-wine** [comment]
Incredible. Thank you Vitor! I'll zap you the bounty.

**Comment by vitorpamplona** [comment]
Thank you for the SATs! Let me know if you find any issue using it.

**Comment by nostr-wine** [comment]
Was bout to post...I can't seem to load global when trying to test this on 0.36.0 right now.

**Comment by vitorpamplona** [comment]
Hum.. i can check in more detail tomorrow. The relay doesn't send any confirmation that it received the challenge, right? 

The app is sending the secret. And I assume it's shared in all subscriptions. The only question is if the package is received correctly.

**Comment by nostr-wine** [comment]
Yes the relay will respond to the AUTH event with ["OK", "event-id", true, ""] or ["OK", "event-id", false, "error: msg"]

**Comment by nostr-wine** [comment]
Yup, I just confirmed that's whats happening. Just make the 22242 use "AUTH" in front instead of "EVENT" and everything else looked good. Keep in mind that this came after some REQs so be aware that due to that race condition we are ignoring the preceding ones.

**Comment by vitorpamplona** [comment]
Ohhh what an oversight! ( and super weird spec ). Will fix soon

**Comment by nostr-wine** [comment]
Hmmm, that event/response looks valid to me. The path to that message is 

1) if the created_at timestamp is > 10 minutes old (doesnt seem to be the case)
2) If the AUTH challenge was replaced by a new one (happens on reconnect and if you AUTH can't be validated)

Your tags and everything else look correct in the above event. I'm able to test it over and over with nostril from terminal successfully both with authorized and with unauthorized pubkeys.

**Comment by vitorpamplona** [comment]
Could it be my user that the server is rejecting?

**Comment by nostr-wine** [comment]
An unauthorized user returns ["OK", "9bb125d444456b4dd054afc0bcb743a8573fd5aa04c2f98bc21f36b65c33cac8", false, "error: user unauthorized"] not unable to validate auth

**Comment by vitorpamplona** [comment]
Are you using an open source relay? I can take a look at their code to see what I am missing

**Comment by nostr-wine** [comment]
Strfry doesn't support it so it is our own custom websocket but it has worked with every client who has implemented so far. You can also try wss://nostr.kollider.xyz that (I believe) uses https://github.com/scsibug/nostr-rs-relay

**Comment by vitorpamplona** [comment]
Kollider says `User is not admitted`. I am not sure how to get a credential with them

**Comment by darashi** [comment]
Since nostr-rs-relay seems to depend on rust-nostr/nostr crate, the above issue may be related. Now it has been fixed on upstream (on master branch), so if nostr-rs-relay incorporates it, the problem may be solved.

**Comment by skyerjoe** [comment]
**should this the intention to use nostr? Seperated from the Community as an private only member club ? **
