### ISSUE TITLE
[FEATURE] Sound notification when DM arrives for paticulat user

### ISSUE THREAD

**Issue by Kirkoj** [vitorpamplona/amethyst#355]
When a new DM arrives for the particular username, Android app pop-out a notification with sound.

This is the setting for a particular follower, from the drop-down menu.  The application is then running in the background. 

Second thing.
Possibility for DM deletion from the phone. New settings, if selected, particularly DM are not shown in the app.

**Comment by vitorpamplona** [comment]
You can set the sounds now in the actual Android notification, just click and hold.
