### ISSUE TITLE
Add accessibility tags to images [UX][Feature Request][Accessibility] (WIP)

### ISSUE THREAD

**Issue by alltheseas** [vitorpamplona/amethyst#358]
**Is your feature request related to a problem? Please describe.**
Accessibility tags for visually impaired are not supported.

**Describe the solution you'd like**

## User Story
As an Amethyst user who has vision accessibility needs, I would like for there to be support for adding accessibility tags to images, so that I can experience the image being shared.

### Acceptance Criteria
1. Every image has a accessibility tag
2. When Amethyst user uploads an image, they are prompted to add to the accessibility tag (for instance, "cat with with red laser beams shooting from cat's eyes")
3. Screen reader software can detect, and read accessibility tag
4. Accessibility tag is reveal-able to user (what is the UI here?)

_NIP_
A NIP for this would be helpful to keep consistent across clients @nostrbuild

Origin:
@dmnyc

https://iris.to/note14c604wyh4av7ugkk86w8s0a0frscmdhm0vg6pa39h4q58xful33qetxqcg

https://iris.to/note1xf55kkyk8khehc8ha2kxp9jc3dv9huwfq3n7qpv99wkq7mllaugshgh2jx

**Bounty (in Bitcoin sats) offered for the implementation**
-

**Additional context**
Work in progress

**Comment by vitorpamplona** [comment]
There isn't a place to write the text into, though. We definitely need an NIP

**Comment by alltheseas** [comment]
An easy 'hack' could be a text line above the image. Agree on NIP

**Comment by vitorpamplona** [comment]
What I meant is that the line must be saved somewhere. We don't have a place for it.

**Comment by vitorpamplona** [comment]
NIP-94 Now provides a description :)
