### ISSUE TITLE
UX error prevetion feature: Short delay before boosts and likes are submitted

### ISSUE THREAD

**Issue by DanConwayDev** [vitorpamplona/amethyst#36]
I just boosted my first note by mistake!

What if I accidentally boosted or liked something that I really didn't want to show my support for?

Two competing proposals:
1. when the button is pressed its state changes to loading for 1-2 second in which time the action can be cancelled by pressing the button again.
2. the action appears to be sent immediately but is actually delayed by 5 seconds in which time the user can cancel by pressing the button again.

**Comment by braydonf** [comment]
Related issue: https://github.com/vitorpamplona/amethyst/issues/21

A confirmation may be the most common and expected, possibly with an option to quote? 

I think this was added in https://github.com/vitorpamplona/amethyst/releases/tag/v0.17.2

**Comment by braydonf** [comment]
Also related: https://github.com/vitorpamplona/amethyst/issues/110

**Comment by vitorpamplona** [comment]
v0.17.5 has a popup to Boost/Quote. Do we really need to implement this for likes?

**Comment by braydonf** [comment]
It's possible to accidentally hit the like when scrolling. There could be a solution where the press and release action need to be at the some scroll position to activate the behavior (e.g. the button remains still when clicked)?

**Comment by vitorpamplona** [comment]
I believe this has been minimized by the latest Jetpack Compose updates. Together with the popups for repost, like and zap, it hasn't happened much recently. 

I am closing for now, but feel free to reopen this if the issue comes back.
