### ISSUE TITLE
Markdown notes don't render clickable phone numbers and nostr:npub ids

### ISSUE THREAD

**Issue by vivganes** [vitorpamplona/amethyst#361]
**Describe the bug**
Markdown notes don't render clickable phone numbers and `nostr:npub` ids

**To Reproduce**
Go to this note - nostr://nevent1qqsddksmdd9exsjpz3pmqttr5mjel0mekguvyd6807kqrjzns07pe8q8xr4k5

**Expected behavior**
Clickable phone numbers and nostr:npub like non-markdown notes

**Video and Screenshots**
![image](https://user-images.githubusercontent.com/2035886/233630025-09bf0129-ea0a-4612-86c5-bdd1177a6bb1.png)

**Device (please complete the following information):**
Android 13

I am working on a PR to fix this.  Will submit in few minutes

**Comment by vitorpamplona** [comment]
Yep. I am not really sure how to proceed. If we render them, we won't be Markdown compliant anymore. Markdown doesn't have preview tags. 🤔

**Comment by vivganes** [comment]
> Yep. I am not really sure how to proceed. If we render them, we won't be Markdown compliant anymore. Markdown doesn't have preview tags. 🤔

Thanks for replying @vitorpamplona 

I have submitted a PR that proposes a solution.  Will modify it based on your opinion.
