### ISSUE TITLE
[BUG] Navigation is not scrollable: Cannot reach lower sections

### ISSUE THREAD

**Issue by lilaflo** [vitorpamplona/amethyst#363]
**Describe the bug**
If the phone's display is not tall enough to show the whole navigation, it's cut off and not scrollable

**To Reproduce**
1. Open app
2. Click on left top to open main menu
3. Try to scroll down 

**Expected behavior**

**Video and Screenshots**
[![amethyst-2023-04-21-100037.webp](https://i.postimg.cc/5NSYkNS6/amethyst-2023-04-21-100037.webp)](https://postimg.cc/CzdxR0tg)

**Comment by vitorpamplona** [comment]
This has been resolved a few months back. Let me know if it is still an issue in your phone.
