### ISSUE TITLE
Filter notifications by friends [FEATURE]

### ISSUE THREAD

**Issue by alltheseas** [vitorpamplona/amethyst#364]
**Is your feature request related to a problem? Please describe.**
**Describe the solution you'd like**

## User Story
As an Amethyst user who receives many notifications, I would like a setting to be able to filter my notifications according to my friends, so that I can increase my signal to noise ratio.

### Acceptance Criteria
1. Amethyst user has a toggle to filter notifications accoridng to friends
2. Toggle can be turned on or off at any time, and feed reflects this update
3. If toggle is on, the only notifications from friends show

**Bounty (in Bitcoin sats) offered for the implementation**
-

**Additional context**
Damus example 

https://cdn.jb55.com/s/filter-friends.mp4

Origin: Annie
> Would love if Amethyst did this.

https://iris.to/note12pkqn6j45u3w3j3fvhahrg929j8j770jjhv33syv6fgxw5jeqsdsm4zy7k

**Comment by MichelleAPatton** [comment]
Annie is always asking for things. :(

**Comment by vitorpamplona** [comment]
v0.45.1, now in the PlayStore, allows filtering of Notifications by Global, Follows or any NIP 51 list. Let me know if this does not satisfy your needs.
