### ISSUE TITLE
什么时候amethyst能够直接上传图片、视频、音频及其它文件才真正具有实用价值

### ISSUE THREAD

**Issue by liug99cn** [vitorpamplona/amethyst#370]
直到现在，amethyst无法直接上传图片，视频。网页版只能上传图片。什么时候amethyst能够直接上传图片、视频、音频及其它文件才真正具有实用价值。现在也没有建群建圈的功能，感觉用户已经对其失去了新鲜感。或许正在流失用户。

**Comment by vitorpamplona** [comment]
Hum... what do you mean? The app has been uploading videos and images since January. Are you able to access imgur.com?

**Comment by liug99cn** [comment]
我试过多次，上传不了视频，图片只能上传其它网站的链接。



***@***.***
 
发件人： Vitor Pamplona
发送时间： 2023-04-23 22:37
收件人： vitorpamplona/amethyst
抄送： liug99cn; Author
主题： Re: [vitorpamplona/amethyst] 什么时候amethyst能够直接上传图片、视频、音频及其它文件才真正具有实用价值 (Issue #370)
Hum... what do you mean? The app has been uploading videos and images since January. Are you able to access imgur.com?

**Comment by vitorpamplona** [comment]
I believe this has been resolved with the new uploader. Let me know if it still a problem.
