### ISSUE TITLE
[BUG] No visible posts from rsslay relays in feed

### ISSUE THREAD

**Issue by mdebus** [vitorpamplona/amethyst#371]
**Describe the bug**
Posts from rsslay (RSS relay) are not visible in feed. If you go to your follows and select a profile, you see all posts.

**To Reproduce**
1. Subscribe to wss://rsslay.data.haus (my instance)
2. Follow npub1jv7e0vqjw2sr62qaatkz84zx50uuwtyda6p7xqyp7rd3j8r7yrnshsz3dd (Slashdot.org RSS feed)
3. no Posts in feed visible
4. Go to your follows, select Slashdot -> all posts are there
5. Go back to feed. All posts from Slashdot are visible.

**Expected behavior**
See posts from rsslay relay in feed.

**Device (please complete the following information):**
 - Pixel 7pro
 - Android Version 13
 - App Version: 0.34.1

**Comment by vitorpamplona** [comment]
There is an error connecting with your relay: 

Relay wss://rssrelay.data.haus: WebSocket Failure. Response: null. Exception: Read error: ssl=0xb40000751f7dea58: Failure in SSL library, usually a protocol error error:10000458:SSL routines:OPENSSL_internal:TLSV1_ALERT_UNRECOGNIZED_NAME (external/boringssl/src/ssl/tls_record.cc:594 0xb40000753f835b38:0x00000001)

Looks like some weird SSL bug on the Websocket

**Comment by vitorpamplona** [comment]
Which software is this relay using? It doesn't reply to filters with partial hexes, only full hex ids. Amethyst follow list is sent to relays with just the first 6 chars of the pubkey

**Comment by mdebus** [comment]
It's using the current version of rsslay (v0.4.7)

https://github.com/piraces/rsslay

**Comment by vitorpamplona** [comment]
Issue raised with them: https://github.com/piraces/rsslay/issues/60

**Comment by vitorpamplona** [comment]
Looks like they just fixed @mdebus :)

**Comment by mdebus** [comment]
Works! Thank you, @vitorpamplona! Amethyst is getting better and better for me! :)
