### ISSUE TITLE
[FEATURE] Hide Media & Link Preview

### ISSUE THREAD

**Issue by bloodyeyesblackblood** [vitorpamplona/amethyst#375]
**Describe the solution you'd like**
- settings to change the behaviour for media / disabling it/replacing it with a load media button

**Additional context**
- this feature would help saving mobile data, also the feed would look a lot cleaer.

**Comment by bloodyeyesblackblood** [comment]
hi @KotlinGeekDev, 

with Media i mean images and videos. 

the settings also could provide both as a separate feature:
[ ] Hide Videos
[ ] Hide Images
instead of Hide All Media.

Is it Important? idk
does it help with the feed? most likely, also depends how it gets implemented, does the media load in the background? than there is no real benefit besides the feed lookin' clearer.

does the media only load when you press the (show media) button? benefit would be, the servers wouldn't need to do all the work as long the user wants to see it, so less data usage and less stress on the servers (i think?)

**Comment by KotlinGeekDev** [comment]
Please @bloodyeyesblackblood can you check if this is OK in the latest version? (So the issue can be closed)

**Comment by bloodyeyesblackblood** [comment]
> Please @bloodyeyesblackblood can you check if this is OK in the latest version? (So the issue can be closed)

thanks for the new feature 👌
i don't like the design of the download button, somehow looks placed weird, but it does work! couldn't ask for more, thank you!
