### ISSUE TITLE
choose the right development

### ISSUE THREAD

**Issue by Wjxfi** [vitorpamplona/amethyst#382]
right now your app doesn't support the most important ones. You fix and add minor features. This is wrong. I'm sure you need to support the major ones, not the minor ones. 
your application is incomplete right now.
you have to fix bugs after adding main functions. Errors appear in >1% of users.
and inferior additions are of no use to anyone. We need fundamentality.

--------------------------------------

 Local Database
 View Individual Reactions (Like, Boost, Zaps, Reports) per Post
 Bookmarks, Pinned Posts, Muted Events (NIP-51)
 Sensitive Content (NIP-36)
 Relay Pages (NIP-11)
 Generic Tags (NIP-12)
 Proof of Work in the Phone (NIP-13, NIP-20)
 Events with a Subject (NIP-14)
 Workspaces
 Expiration Support (NIP-40)
 Infinity Scroll
 Relay List Metadata (NIP-65)
 Signing Requests (NIP-46)
 Delegated Event Signing (NIP-26)
 Account Creation / Backup Guidance (NIP-06)
 Message Sent feedback (NIP-20)

**Comment by vitorpamplona** [comment]
You just listed 6 months of work. Let me know if you have a preference among them.
