### ISSUE TITLE
I can't upload an image

### ISSUE THREAD

**Issue by nourou4them** [vitorpamplona/amethyst#39]
I was trying the "upload" button which appears when you want to write a post. It doesn't react at all.
I was looking to upload one or multiple pictures with my post.

**Comment by vitorpamplona** [comment]
Which Android version? Some old ones don't really work well with the uploader. :(

**Comment by nourou4them** [comment]
Version 10 QKQ1.190828.002.
Any way around?

**Comment by bitcoinuser** [comment]
I have the same problem with a Xiaomi Redmi note9s

**Comment by TiKawamoto** [comment]
Same issue. Samsung Galaxy S10+ Android 12 / OneUI 4.1

**Comment by psilonux** [comment]
Same issue here. OnePlus Nord OxygenOS 12.1 | Android12 | AC2003_11_F.18

**Comment by lkblkb** [comment]
+1 
LineageOS w/ Android 11, OnePlus 7Pro

**Comment by psilonux** [comment]
Fixed since 14.3

**Comment by nourou4them** [comment]
Thank you for the fix.
