### ISSUE TITLE
[BUG] Japanese text is misidentified as URL.

### ISSUE THREAD

**Issue by mattn** [vitorpamplona/amethyst#390]
**Describe the bug**
Some Japanese text is unexpectedly misidentified as URL.

**To Reproduce**
1. Open input dialog
2. Type some Japanese characters contains `。`  (`\u3002`)
3. Post the note
4. See the text is misidentified as URL.

**Expected behavior**
The  text should be normal text.

**Device (please complete the following information):**
 - Android Version: 0.37.4 

This is related on linkedin/URL-Detector. https://github.com/linkedin/URL-Detector/issues/39

URL-Detector handle `。` as dot. This is not a bug because IDN allow to use `。` as dot. However, most of Japanese text are often misidentified.

![image](https://user-images.githubusercontent.com/10111/235552699-846bd525-d71d-4a7c-b6fc-bbcced9db926.png)

**Comment by afternooncurry** [comment]
Ideographic full stop and full width period are not handled as dot in IDNA2008 while IDNA2003 does. A current recommendation is IDNA2008. linkedin/URL-Detector looks implemented based on IDNA2003 about IDN which may causes the issue.

**Comment by mattn** [comment]
@vitorpamplona Many users in the East Asian region have been waiting for this fix for a long time.

**Comment by vitorpamplona** [comment]
We are waiting for the library to be able to support these additional characters. Until that library is fixed, there is not much we can do :(

**Comment by mattn** [comment]
Thanks. FYI, This issue can be reproduced with English speakers.

![image](https://github.com/vitorpamplona/amethyst/assets/10111/9a519d4d-6261-41be-837c-be627f0c4f22)

**Comment by vitorpamplona** [comment]
Interesting. That is a different "bug". 

We have a separate procedure to linkify all `yyy.xxx` texts. It requires the domain separator `.` and should not affect the `\u3002` character. Is that an issue for you. I see it here and there during the week but always just ignore it because it works most of the time.

**Comment by vitorpamplona** [comment]
And now that urls can have any Unicode character, I am not really sure how to solve it. Because the `Thanks.<emoji>` is a valid URL these days.

**Comment by mattn** [comment]
I don't make sure what is wrong in the code but this is rendered as URL in only amethyst.

![image](https://github.com/vitorpamplona/amethyst/assets/10111/b9d956ab-9f47-47a2-b260-6fe01c0c218f)

**Comment by mattn** [comment]
Is this related on this issue?

![image](https://github.com/vitorpamplona/amethyst/assets/10111/4942c563-1a6d-4c35-beec-1574fd4cb7fa)

**Comment by mattn** [comment]
I confirmed this issue is fixed in https://github.com/vitorpamplona/amethyst/pull/491

Thanks.
