### ISSUE TITLE
EPIC UX/UI improvements. Enable temporary post edits, implement app settings + more.

### ISSUE THREAD

**Issue by 3j2009** [vitorpamplona/amethyst#394]
### _As a frequent Amethyst user I would like to be able to quickly edit my posts after sending them so that I can fix spelling mistakes and text errors in my post._

- **Primary Feature:** Enable user to quickly edit their post up to 30 seconds after posting.

- **How the edit function works:** Amethyst delays sending the Event by 30 seconds, allowing for the user to edit the post. When a user clicks the `Edit` button to edit their post, the 30 second timer stops. Timer resumes and resets when user finishes editing their post (clicks the Post button again to send the newly edited post).

***Here's a conceptual video of the Edit function being used:**
https://user-images.githubusercontent.com/126127093/236348958-200d838e-f515-485c-9dac-da680792442f.mp4

If the post is older than 30 seconds (and therefore the post Event has happened) the `Edit` button should be greyed out as seen in the following image:
![Post older than 30 seconds](https://user-images.githubusercontent.com/126127093/236350452-e98f036e-84e5-4dda-b84e-2ec1bf358782.png)

Did you notice the `Relay` icon isn't visible? That's because it's been moved into the new `Settings` screen.

### The new settings screen:

Whilst post editing and other features are useful, not every user may want it. As more features and functions are added to Amethyst, the need for the app settings to be located in a central (god forbid I say that word) location in the app grows stronger. One place for all settings to live. One screen to rule them all (am I being too dramatic?).

With this in mind, I'm suggestion all applicable settings be located in a settings screen, as seen in the following image:

![Settings](https://user-images.githubusercontent.com/126127093/236357504-c972754b-857d-4b18-b2cb-89db8df50c7a.png)

### Breaking the above down into actionable tasks.

- Enable the `Edit` function to work by making Amethyst add a 30 second delay on creating the post **Event** on nostr. Within the 30 second window the post shows in the app feed but is not yet a live event on nostr and can therefore be edited in Amethyst.
- Add `Edit` button with countdown timer below the `Request Deletion` button located in the posting options when you click the 3 dots
- Temporarily disable the `Copy Note ID` button for posts that are not an **Event** yet. Grey out the text to show it's disabled. This is because you can't copy a note id if the post isn't an **Event** yet.
- Create `Settings` panel, accessible in the left side-window underneath `Profile` and `Bookmarks`
- Move `Relay` settings, `Security Filters` and `Backup Keys` inside the `Settings` screen
- Add `Post editing` with an On/Off toggle as a setting in the `Settings` screen
- Add subheader text for each setting explaining what it does. See the above image for what text to add.

Below you can find PNG & SVG icons.
[Icons & Buttons.zip](https://github.com/vitorpamplona/amethyst/files/11402515/Icons.Buttons.zip)

[BOUNTY]
I'll start the bounty off at 10k Sats. I know it's not much, but it's what I can afford to give. Hopefully other's can contribute.

If you need other assets or design support to achieve this, please reach out to me.

**Comment by KotlinGeekDev** [comment]
Please @3j2009 see whether the new Settings screen fits your needs. As for temporary post editing, please @vitorpamplona @davotoula what do you think?

**Comment by davotoula** [comment]
First of all @3j2009, really cool designs. Especially the concept videos!

Just today I wished I was able to edit a note immediately after posting it so i think there is value in it. Users coming from other centralised platforms will expect an edit function 😂

The fact that it can be switched on/off and also be transparent most of the time when turned on makes it unintrusive. 

The growth of available settings will make the app more complex for new users. I hope it can be solved with intuitive settings groups and tool tips with explanations.

**Comment by vitorpamplona** [comment]
Edit has been added a few versions back. :)
