### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by StellarStoic** [vitorpamplona/amethyst#397]
**Is your feature request related to a problem? Please describe.**
*No, just my personal opinion.*

**Describe the solution you'd like**
*Enable markdown*

**Additional context**
*I believe a basic Markdown is highly important. We are creating notes after all and notes are easily readable when we emphasize some important part of our note. I also realize that headers can become a problem to so, I'm proposing to bring back markdown except headers.*

**Comment by vitorpamplona** [comment]
If so, we might need a way to know when a post should be rendered as Markdown and when not to. Because most posts will look vastly different when rendered with a Markdown renderer. 

Also, Markdown without headers is not Markdown :)

**Comment by vitorpamplona** [comment]
Amethyst now detects if there are markdown tags and render it as such. It's not fool proof but it works most of the time.
