### ISSUE TITLE
Link purple highlighting a bit off 

### ISSUE THREAD

**Issue by StellarStoic** [vitorpamplona/amethyst#398]
**Describe the bug**
While typing a domain dot.somethingSomething, it colors the characters one line below. That's only while typing and after posting the, right link is colored. Just a weird behavior that doesn't brake anything. 

**To Reproduce**
1.start a new note
2. And write a note a couple of lines long.
3. Now try to ad some links in the beginning or middle of the note. 

**Expected behavior**
After typing anything after the dot .org for example, the purple colored text appear one line below the actual link.

**Video and Screenshots**

![20230508_183208.gif](https://user-images.githubusercontent.com/34000272/236879148-45c5865c-4764-48aa-99bd-4b4874e84625.gif)

**Device:**
 - Phone Brand/Model [Pixel 4a]: 
 - Android Version [13]: 
 - App Version [v0.43.0]:

**Comment by faruqkanji** [comment]
I can't reproduce this. Can you give it another go, @StellarStoic?

**Comment by StellarStoic** [comment]
Yes on a totally different version as my first report. Now on [0.58.2 FDROID] the purple text persist but an @faruqkanji mention needs to be prior to link to reproduce it. . 

![20230617_133730.gif](https://github.com/vitorpamplona/amethyst/assets/34000272/493a504a-2e74-41b7-a2e8-7cc2411c7dd7)

**Comment by faruqkanji** [comment]
Got it, I'm seeing it using these steps. When you post, is the link still off?

**Comment by vitorpamplona** [comment]
It's an issue in this mapping algorithm: https://github.com/vitorpamplona/amethyst/blob/244e3f3b292f46e6b8e3e9e3ebb3faf317cce149/app/src/main/java/com/vitorpamplona/amethyst/ui/actions/UrlUserTagTransformation.kt#L29

**Comment by vitorpamplona** [comment]
I believe this has been fixed. Let me know if it still happens in your phones.
