### ISSUE TITLE
Navigation behaviour.

### ISSUE THREAD

**Issue by KotlinGeekDev** [vitorpamplona/amethyst#4]
Right now, when navigating between bottom bar destinations, even when navigating to the same location again, it gets added to the back stack. Thus, when pressing the back button, it goes through all the locations passed by. I wonder whether it is a desirable behaviour, or whether it should be fixed.

**Comment by KotlinGeekDev** [comment]
cc @vitorpamplona

**Comment by vitorpamplona** [comment]
Definitely an oversight. What's the best way to fix this? I am new to the whole Compose + Navigation structure :)
