### ISSUE TITLE
Avoid users to boost many times the same note

### ISSUE THREAD

**Issue by grunch** [vitorpamplona/amethyst#40]
![Screenshot_20230125-171835.png](https://user-images.githubusercontent.com/228364/214681018-83f94f7e-cd1b-4c54-b6e9-4a1ec0b33ec0.png)

**Comment by bitcoinuser** [comment]
I love this concept.

**Comment by vitorpamplona** [comment]
Already fixed on https://github.com/vitorpamplona/amethyst/commit/857a31faf0afbd01118c021a4750864e7c5cde8d

**Comment by ValZapod** [comment]
So you can still boost after 5 minutes?
