### ISSUE TITLE
[BUG] Loaded images do not automatically rotate when device orientation is changed

### ISSUE THREAD

**Issue by paulosacramento** [vitorpamplona/amethyst#405]
**Describe the bug**
Loaded images do not rotate when device orientation is changed from vertical to landscape

**To Reproduce**
1. I saw a post with a landscape image.
2. I tapped on it and it loaded.
3. I changed the orientation of my mobile device and the image just disappeared.

**Expected behavior**
The expected behavior is that the image would adjust and still be displayed, filling the screen in landscape orientation.

**Device (please complete the following information):**
Google Pixel 3a (Android 12)

**Bounty (in Bitcoin sats) offered for a solution**
Incentivize developers to work on your issue. Describe clear milestones to claim payment.
50000 sats

**Comment by KotlinGeekDev** [comment]
Please @paulosacramento do you still experience this?

**Comment by vitorpamplona** [comment]
Yep, the dialog is not saved when rotating the device. Actually it looks like the whole activity restarts when the orientation changes.

**Comment by KotlinGeekDev** [comment]
Please @vitorpamplona does it happen when creating a note?

**Comment by KotlinGeekDev** [comment]
Please @paulosacramento if you still experience this, feel free to reply here.
