### ISSUE TITLE
If I'm on Follows+Replies tab and I click on on home bottom button, I don't want it to switch to Follows tab.

### ISSUE THREAD

**Issue by bitcoinuser** [vitorpamplona/amethyst#41]
Hi,

If I'm on Follows+Replies tab and I click on on home bottom button, I don't want it to switch to Follows tab.

I clicked on Home bottom button to jump the feed to top on Follows+replies tab and not go to Follows tab.

Thanks.

**Comment by KotlinGeekDev** [comment]
I think the purpose of tapping on the Home bottom button is to show the feed of your follows(and in this case, without the replies as well). Is it really undesirable?🤔
I think there are two ways to go about it: 
1) provide a button on the side to jump to top, or provide a Twitter-like experience, showing a top button for new notes, 
2) provide an option in the settings, to modify this behavior for you.

**Comment by bitcoinuser** [comment]
> 1. provide a button on the side to jump to top, or provide a Twitter-like experience, showing a top button for new notes,

Yes, would love this.

![photo_2023-01-28_11-54-07](https://user-images.githubusercontent.com/1178856/215273338-6ef991e8-e756-4b3f-8f39-a77b97ee7df1.jpg)

**Comment by KotlinGeekDev** [comment]
One tradeoff with (1),  @bitcoinuser is that it is more complex and o implement, and could potentially use a lot more bandwidth. But maybe @vitorpamplona can find a way.
