### ISSUE TITLE
[BUG] Set hashtags to lowercase on json tags section before posting event

### ISSUE THREAD

**Issue by pleblira** [vitorpamplona/amethyst#413]
**Describe the bug**
Because of the way hashtag events are filtered, a hashtag with an uppercase character isn't displayed when searching for that hashtag.

**To Reproduce**
1. Post a note with #Stackjoin using Amethyst
2. Search for #stackjoin
3. Note won't be displayed

**Expected behavior**
It would be expected for the post posted with #Stackjoin to be displayed, but the Amethyst client is submitting the tags section as [["t","Stackjoin"]] instead of [["t","stackjoin"]]

**Video and Screenshots**
https://pleblira.s3.amazonaws.com/case_sensitive_hashtags.json
In the json file above, the first note has the tags section with the uppercase character, and doesn't show when you search for #stackjoin. Notes number 2 and 3 show, number 2 because the user posted with lowercase #stackjoin using Amethyst, and on number 3, the user still used #Stackjoin, but his client set the hashtag to lowercase before submitting (waiting to hear back from the user of the client he's using).

**Device (please complete the following information):**
 - Android (not sure which version)

Would a fix be to add toLowerCase() to this line and line 48?
https://github.com/vitorpamplona/amethyst/blob/bb9fa8e14437cfddbae5c04614c987903ffa4b85/app/src/main/java/com/vitorpamplona/amethyst/service/model/TextNoteEvent.kt#L45

Thank you, let me know if I can help provide any more context.

**Comment by KotlinGeekDev** [comment]
Since the issue occurs when you are searching, a better fix would be ignoring the lettercase. Would fix this with a PR. :+1:

**Comment by vitorpamplona** [comment]
Also keep in mind that many relays will only return a case-sensitive match to the hashtag. #Amerhyst and #amethyst are different hashtags for most relays.

**Comment by pleblira** [comment]
> Also keep in mind that many relays will only return a case-sensitive match to the hashtag. #Amerhyst and #amethyst are different hashtags for most relays.

Yeah, that's how I realized it... I'm building a bot to track and reply to a hashtag (https://github.com/pleblira/stackchainsiggy_nostr), and realized the first event wasn't picked up by the filter because the tags field had the uppercase character.

What are you guys' thoughts on the concept of case-sensitive hashtags? I personally feel it's a complexity that could be avoided.

I heard back from the user below, and he used Snort to submit the note below, which even though contained #Stackjoin in the content field, was lower-cased when having the tag added.

Thanks so much for taking the time to look into it!

    {
        "content": "#Stackjoin $12\n\nhttps:\/\/i.nostrimg.com\/61a8580b6b34a3f139ec9e1183a9414ea981c148e07624cfc5e3b95fde316e8b\/file.png",
        "created_at": 1684277132,
        "id": "e8dc0ac1f4fb1329fff3c2ea93f9eabd764715b57876de2482d3f066e62bbdc3",
        "kind": 1,
        "pubkey": "47f33c191ec5ca03c82f3e5d147384e028b3126409cabaf01649e01f9b69b6a3",
        "sig": "c9a4ce21ceb51c4fffa2c2064fa449e35f296ffdd6ae012c7bb2ff9644b9836e216978f9cb5aac8227950ed051527a2888edc382ed07f25c2921fc4e7fe0bb6a",
        "tags": [
            [
                "e",
                "1c5c2cc60cc30f80b1096b646f6f15423972e53a241b0efef39f7220c4e57f0d",
                "",
                "reply"
            ],
            [
                "p",
                "3f770d65d3a764a9c5cb503ae123e62ec7598ad035d836e2a810f3877a745b24"
            ],
            [
                "t",
                "stackjoin"
            ]
        ]
    }

**Comment by KotlinGeekDev** [comment]
so @vitorpamplona it means that the hashtag search filter would need a modification, if I understand.

**Comment by vitorpamplona** [comment]
The HashTagDatasSource asks relays for the most common spelling: 

```kotlin
TypedFilter(
            types = COMMON_FEED_TYPES,
            filter = JsonFilter(
                tags = mapOf(
                    "t" to listOf(
                        hashToLoad,
                        hashToLoad.lowercase(),
                        hashToLoad.uppercase(),
                        hashToLoad.capitalize()
                    )
                ),
                kinds = listOf(TextNoteEvent.kind, ChannelMessageEvent.kind, LongTextNoteEvent.kind, LongTextNoteEvent.kind, PollNoteEvent.kind),
                limit = 200
            )
        )
```

Once posts are in the device, the HashtagFeedFilter to bring them to the screen is case insensitive. 

To create posts with hashtags, the TextNoteEvent.create function assembles all hashes automatically. Maybe here we can send the hashtag as written and ALSO a lowered-case one. That avoids breaking any expectation for case sensitivity the user might have (if he/she searches relays for case-sensitive tags, it will return it as he/she typed as well as in a lower case setting).

**Comment by KotlinGeekDev** [comment]
The other idea I had was sending a request with two filters, one with the original form, and one with the lowercase variant. cc @vitorpamplona @pleblira  what do you think?

**Comment by KotlinGeekDev** [comment]
> > The other idea I had was sending a request with two filters, one with the original form, and one with the lowercase variant. cc @vitorpamplona @pleblira what do you think?
> 
> yeah, it seems this would help cover the search results for Nostr clients that aren't yet adding the lowercase variant to hashtags.

That was my thought too.
