### ISSUE TITLE
note content order is preventing image to load and disables hashtags 

### ISSUE THREAD

**Issue by StellarStoic** [vitorpamplona/amethyst#416]
**Describe the bug**
I'm not sure if this is a bug but I'd like to report this anyway.
When my [bot](https://snort.social/p/npub1ap0dw55xedm5w4mkcyq8m7xyluwfc680lywrvfe50vr9ckl5m3uqtf5l75) posts a note with img url in the middle of the note and hashtags at the bottom, the image isn't shown (just a url link) and the hashtags aren't purple text but rather just as text. if I would post in order as text -> hashtags -> image url, everything would be visible. 

**To Reproduce**
1. post a note with a link to an image and hashtags in different content orders. Use text, image url and hashtags. 

**Expected behavior**
- If the content order is text -> hashtags -> img url, then the image is visible and hashtags clickable
-  if the content order is text -> img url -> text -> hashtags, then the image isn't shown and hashtags not clickable

**Video and Screenshots**
visit npub1ap0dw55xedm5w4mkcyq8m7xyluwfc680lywrvfe50vr9ckl5m3uqtf5l75 to see how the bot posts the content.

**Device (please complete the following information):**
x

**Bounty (in Bitcoin sats) offered for a solution**
x

**Comment by vitorpamplona** [comment]
The issue here is the use of this: `[Image Credit & Copyright:](Mark Johnston)`. [<something>](<something>) is a Markdown tag and thus the post finds it and renders as a Markdown (which doesn't support image previews yet. If you just add a space or use a different way to encode this, it will render fine.

**Comment by StellarStoic** [comment]
thanks for explanation
