### ISSUE TITLE
[BUG] Scanning wrong QR code

### ISSUE THREAD

**Issue by dgyg** [vitorpamplona/amethyst#417]
**Describe the bug**
Scanning a QR code containing a nostr public key instead of a nostr npub key does does not result in an error

**To Reproduce**
1. Got to the profile
1. Scan a QR code containing a nostr public key
1. QR code is read and then nothing happens anymore

**Expected behavior**
- An error message saying unsupported format or similar is displayed
OR
- Goes to the profile page represented by the public key

**Video and Screenshots**

**Device (please complete the following information):**
 - LineageOS 19.1 
 - App Version [v0.46.2]

**Bounty (in Bitcoin sats) offered for a solution**

**Comment by vitorpamplona** [comment]
This is on purpose. The app tries to decode whatever comes in its way.
