### ISSUE TITLE
Like spamming

### ISSUE THREAD

**Issue by toadlyBroodle** [vitorpamplona/amethyst#42]
Able to spam like button every second: bug or feature?

**Comment by KotlinGeekDev** [comment]
Please can you explain what you mean by that?

**Comment by toadlyBroodle** [comment]
You can 'like' things more than once, by clicking like every second, you can increase 'like' count as high as you have patience for.

**Comment by vitorpamplona** [comment]
Not in the latest version. Please update.

**Comment by toadlyBroodle** [comment]
Right on, can confirm fixed since 0.10.4

**Comment by ValZapod** [comment]
> Not in the latest version. Please update.

Wait a second. This is not a bug if it registers in network.

>These likes register on other clients as well, thus you can use this bug to spam the network.

What do you mean by this? You see 2 or more likes or it just 1 like but multiple times every time you remove the like it removes and when you set it it notifies the user? Well, that is how it works on any network.

**Comment by toadlyBroodle** [comment]
No. It was possible to increment likes indefinitely high in 0.10.4, which would propagate to the network and even other clients would rank popularity of spammed posts based on false like-counts.

**Comment by vitorpamplona** [comment]
@toadlyBroodle frankly, people that are ranking on likes need to filter duplicates anyway. Client apps might help, but in the end, users can always broadcast as many likes as they want. It's their bug.

**Comment by toadlyBroodle** [comment]
Gotcha
