### ISSUE TITLE
[BUG] F-Droid 404 Page Not Found

### ISSUE THREAD

**Issue by felipebueno** [vitorpamplona/amethyst#422]
**Describe the bug**
404 Page Not Found

**To Reproduce**
1. Access https://f-droid.org/packages/com.vitorpamplona.amethyst/

**Expected behavior**
200 OK

**Video and Screenshots**
![image](https://github.com/vitorpamplona/amethyst/assets/241271/4949c55d-e772-41c2-aa1e-e43846f44a01)

**Device (please complete the following information):**

**Bounty (in Bitcoin sats) offered for a solution**

**Comment by vitorpamplona** [comment]
Long discussion here: https://github.com/vitorpamplona/amethyst/issues/378

Essentially, we need some terms of use for the app to avoid liability of the shipper of the app and F-Droid doesn't like those restrictions.

**Comment by vitorpamplona** [comment]
This has been resolved.
