### ISSUE TITLE
Tor/Orbot mode is leaking traffic [BUG]

### ISSUE THREAD

**Issue by StuartLitt** [vitorpamplona/amethyst#425]
I was using RethinkDNS while Amethyst was activated in Tor/Orbot mode until I came across a traffic leak.

I use version v0.50.6 of Amethyst.
![IMG_20230524_101743](https://github.com/vitorpamplona/amethyst/assets/70270395/3701d3d1-70e7-4773-b01d-49f45f3aa5d0)
![IMG_20230524_101817](https://github.com/vitorpamplona/amethyst/assets/70270395/6c0a2c80-6be5-4c39-b1d9-3c2d0cc11159)

**Comment by vitorpamplona** [comment]
Looks like Coil goes around the OkHttp setup with a proxy. I will submit a patch soon
