### ISSUE TITLE
lightning tips

### ISSUE THREAD

**Issue by murdawkmedia** [vitorpamplona/amethyst#43]
Are there plans to incorporate lightning tips? I use them often and don't see them. 

Cheers!

**Comment by hopitas** [comment]
It would be awesome if they were integrated into app, so they could be used as likes/zaps. No need to open external wallet.

**Comment by kiwiidb** [comment]
I agree that an integrated solution would provide top-notch UX, however the problem with current Lightning providers, both custodial and non-custodial, is that there is no common API. At Alby we've implemented the API of LND, CLN, Eclair and a whole host of custodial wallet providers. A possibility would be to integrate the [LNDhub API](https://yojoe.github.io/lightninghub-api/). This would be interoperable with the following custodial wallet providers:

- Alby
- Bluewallet
- Kollider (coming soon)
- LNBits (has an extension with the LNDhub API)

In addition, you can run LNDhub yourself in front of your own node.

FYI, at Alby our accounts are powered by [lndhub.go](https://github.com/getAlby/lndhub.go), an LNDhub server in Go with a PG backend.

A fallback mechanism for a user that does not want to do this would be to just hyperlink the `lightning:lnbc..` links , which would open the user's wallet of choice on their phone, which is a bit worse UX-wise but is obviously interoperable with every Lightning wallet out there.
