### ISSUE TITLE
[FEATURE] Don't load media when not connected to WiFi

### ISSUE THREAD

**Issue by Dielan** [vitorpamplona/amethyst#435]
**Is your feature request related to a problem? Please describe.**
Amethyst is difficult to use while traveling, as poor cell phone reception can cause timelines with several media attachments at the time to load slowly or not at all.

**Describe the solution you'd like**
A non-default option to not load media when not connected to WiFi, so I can scroll past those posts while on cellular data. The posts should display a button, similar to the recent nsfw/sensitive button, to click thru this and load the media. That way I can choose what posts to load media on when I'm on the go.

**Bounty (in Bitcoin sats) offered for the implementation**
Dont have sats to offer for this

**Additional Details** 
This is similar to something offered by the Fedilab app, which is a similar app to Amethyst but for ActivityPub instances

**Comment by davotoula** [comment]
I like this one. I'll have a poke around to see whether it's something I can do!

**Comment by davotoula** [comment]
#440

**Comment by greenart7c3** [comment]
@davotoula are you still going to do it?

**Comment by davotoula** [comment]
This was too complex for me with limited android development experience 😱 feel free to do it @greenart7c3

**Comment by davotoula** [comment]
If you do a pull request draft I can follow your development 👍

**Comment by greenart7c3** [comment]
Thanks, I'll start working on it next week

**Comment by greenart7c3** [comment]
#486
