### ISSUE TITLE
Feature Request: Alternative Share URLS Other than Snort

### ISSUE THREAD

**Issue by Ryonez** [vitorpamplona/amethyst#437]
Do we really need a setting for this? Users don't care which site to use when sharing (it should never be the senders choice anyway), we can just send them to snort for now.

_Originally posted by @vitorpamplona in https://github.com/vitorpamplona/amethyst/issues/71#issuecomment-1457999170_
           
Hi there. I'm a user who does a lot of image saving. Often when I find an image, I'll flick the link to my computer, and do reverse searches from there.
However, in selecting snort as the service to make a share url with, this kinda breaks my workflow completely.

Snort uses an image proxy, which then serves images via the avif format. This is an issue in that I can't give the proxy url to the reverse search services I use (They can't phrase it), but downloading the image leaves it in the avif format, which can't be used in the services either, alongside my image viewers not being able to open it.

I would find it immensely helpful to either be able to select alternative services. [Astral](https://github.com/monlovesmango/astral) shows images as they should be using the original file url.

I have had a quick look at seeing if I can use the snort url made to open the image in Astral, but snort seems to use nevents urls, and Astral note urls. Astral doesn't seem to support bookmarks, so I can't use those either.

Just a heads up as well, I'm fairly new to Nostr, so I'm still learning a lot about it.

**Comment by Ryonez** [comment]
[iris](https://github.com/irislib/iris-messenger) also proxies images, but preserves the file in the process.

**Comment by vitorpamplona** [comment]
Besides proxies, almost all image hosts themselves change their files over time. There is not much that is original. It's why we created NIP-94 and NIP 95.

**Comment by vitorpamplona** [comment]
I assume the save button on Amethyst is not good enough? Do you want to save the image or share with others?

**Comment by Ryonez** [comment]
> Besides proxies, almost all image hosts themselves change their files over time. There is not much that is original. It's why we created NIP-94 and NIP 95.

I can understand some changes over time, however the proxy snort has setup makes the url unusable by reverse search services ([Example URL](https://imgproxy.snort.social/h9DGeDdUceY7Y8dWbB-ZoluPpvaaLva8AT9Z7qEHOhM//aHR0cHM6Ly9pLm5vc3RyaW1nLmNvbS9lMWZlY2EwZmQ0OWUyMDFmNmZmZDYxZWVlNDcxYzBhZDU1NzRhZDg0ZDMyMjU2ZmM1Y2IwYjkzZmYzZmYwNGEzL2ZpbGUuanBn)), and changes the format into something my software isn't working with, even though they are meant to have avif support. The file format also prevents usage through the reverse search services I use.

NIP-94 isn't listed as a supported protocol for snort, I don't see NIP-95 in https://github.com/nostr-protocol/nips

> I assume the save button on Amethyst is not good enough? Do you want to save the image or share with others?

It could, but it's a workaround that's a bit lengthy. I'd have to save the file, upload it to the pc, then upload it to the reverse image services. By sending a url that links to a useable image link, I can just give that link to the reverse image services via my context menu. Which cuts out dealing with file transfers.

So what I'm aiming to do is save the images, but I run them through the reverse image services to find source files and tags first, which are sent to a bit of software called [hydrus](https://github.com/hydrusnetwork/hydrus).

**Comment by vitorpamplona** [comment]
We are now using njump.me that helps the receiver choose a client to open the link.
