### ISSUE TITLE
Amethyst crashes on start after altering relay list

### ISSUE THREAD

**Issue by YellowWords** [vitorpamplona/amethyst#44]
Hello, after the update to 0.10.7 I updated my relay list. This appears to have caused Amethyst to crash consistently though. After I published the new relay list from Astral, now Amethyst crashes less than a second after opening the app.

My pubkey is `npub1mxrt3fyvaay4plrz7lwzurf80jjs2atmt2nn7z2ekgr9necl0jkqekkyq5` so you can see what my relay list is.

**Comment by YellowWords** [comment]
This is still present in 0.11.0

**Comment by vitorpamplona** [comment]
Are you going back and forth between the APK and the Google Play release? 

If so, see if going into Settings/Apps, choose Amethyst and clear storage and cache. Different signatures between Google Store and APK encrypt the information with different keys and the app is not able to see the previous user. This will crash on opening.

**Comment by YellowWords** [comment]
I had to uninstall 0.10.7 entirely to try 0.11.0 due to something about conflicting APK signatures. I'm not going back and forth. Clearing localstorage does nothing, it still crashes instantly after start if I've input my pubkey.

**Comment by vitorpamplona** [comment]
Ohhh your relay list has one item with a space before the address: " wss://nostr-relay.untethr.me"

**Comment by YellowWords** [comment]
Hmm, okay. I tried removing that relay but it doesn't really seem to improve the stability in Amethyst even after clearing storage and logging back in.

**Comment by vitorpamplona** [comment]
I will release a version to trim the url in case this happens. 

You still have other 2 addresses with space: 
" wss://relay.nostr.info"
" wss://nostr.coinos.io"

**Comment by YellowWords** [comment]
Ok thanks. You can't really see leading whitespace in most web clients.

**Comment by KotlinGeekDev** [comment]
Please @YellowWords does this issue still occur?

**Comment by YellowWords** [comment]
Latest version it seems to work well - Although it maybe displays a bit weird in the relay list, maybe trim that string as well?
![Screenshot_20230131-132751](https://user-images.githubusercontent.com/1665676/215760237-f0642446-e8fb-4e65-a87f-8a0ececc52cb.png)

**Comment by KotlinGeekDev** [comment]
Oh, I see. OK.
