### ISSUE TITLE
[FEATURE] Spam filter opt-out option

### ISSUE THREAD

**Issue by RenegadeButcher** [vitorpamplona/amethyst#443]
An option to turn off or opt-out of auto-blocking users that end up in a spam filter would be excellent.  I'm glad I can block bots or annoying users, but I already have a mute list on the protocol level, I would like to be able to opt-out of automatic filtering on the client side.

This doesn't have to clutter up the UX, it could be a simple checkbox in the security filers menu.

**Comment by vitorpamplona** [comment]
Fixed on https://github.com/vitorpamplona/amethyst/pull/449
