### ISSUE TITLE
[FEATURE] - Only show boosts once.

### ISSUE THREAD

**Issue by dadofsambonzuki** [vitorpamplona/amethyst#453]
**Is your feature request related to a problem? Please describe.**
Popular posts that get constantly boosted spam the timeline.

**Describe the solution you'd like**
Add each npub that boosts, like we do with likes and zaps on a note.

We might want to bump the timestamp on latest boost so that boosted post stays high on timeline if popular.

**Bounty (in Bitcoin sats) offered for the implementation**
100k sats

**Additional context**
Add any other context, video, or screenshots about the feature request here.
![Screenshot_20230616-110127.png](https://github.com/vitorpamplona/amethyst/assets/87125117/0322d04f-357b-4281-8835-b0e2919201d1)

**Comment by vitorpamplona** [comment]
I believe this has been fixed. We only show duplicated reposts when the two reposts are far from each other: 100 posts or 1 day
