### ISSUE TITLE
"MIT" license allows Amethyst code to be used in proprietary apps

### ISSUE THREAD

**Issue by strypey** [vitorpamplona/amethyst#455]
Can I suggest you consider [publishing Amethyst source code under the AGPL license](https://www.gnu.org/licenses/why-affero-gpl.html)?

Non-copyleft licenses like "MIT" allow your code to be reused in proprietary apps. Whereas with a copyleft license like GPL or AGPL, any software that incorporates your code must be released under a compatible Free Code license. This way the software freedoms of any downstream users of your code are protected, and as a bonus, you can incorporate improvements made in derivative versions back into your own code, if you want to.

I usually suggest using AGPL instead of GPL, so if someone tries to use your code in server-side software, rather than an app distributed to users, copyleft still applies.  I convinced the Loomio developers to switch from "MIT" to AGPL years ago, and they've never regretted it. 

(Standard disclaimer: IANAL and this is not legal advice)

**Comment by vitorpamplona** [comment]
Thanks Danyl! We use MIT exactly because it is more free than AGPL. I understand that MIT is worse for open source, but it is better for decentralization. Since Nostr is all about decentralization and freedom from overlords, it is important to allow any use of the code, even private/for profit ones, by anyone.

**Comment by aidik** [comment]
@vitorpamplona thank you for this approach. Sticking to a truly free license is definitely a good choice.

**Comment by strypey** [comment]
@vitorpamplona 
>We use MIT exactly because it is more free than AGPL

Depends whose freedom you are prioritizing. A non-copyleft licenses means that corporations are "free" to include your code in proprietary software, without even letting you know. But you're not "free" to incorporate any improvements they make back into your own code. Nor is anyone using that proprietary derivative "free" to obtain the source code of the software they're using. Which they are if they use Amethyst directly. If there are your intended consequences, you've chosen the right license.

But you also say that "MIT" is ...

> better for decentralization

How? Building proprietary derivatives around non-copyleft Free Code (MacOS, iOS, Android, Chrome etc) is one of the main ways tech corporations have centralized things. While using the unpaid work of people like you.

In contrast, look at the fediverse, which is a hotbed of decentralisation advocates of all types. The [main license used in fediverse software like Mastodon is AGPL](https://codeberg.org/fediverse/delightful-fediverse-apps). Any corporate work on derivatives has to obey copyleft, by making their code improvements available to the developers of the original. That seems much more helpful to decentralisation from where I'm standing.
