### ISSUE TITLE
[FEATURE] Show information about relays

### ISSUE THREAD

**Issue by greenart7c3** [vitorpamplona/amethyst#457]
**Is your feature request related to a problem? Please describe.**
In the relay list add a button or dropdown to show the relay information (Supported nips, paid relay, etc)

**Describe the solution you'd like**
When pressing the relay name or a button in the relay list show the relay information (Supported nips, paid relay, etc)
[Nip 11](https://github.com/nostr-protocol/nips/blob/master/11.md)

**Bounty (in Bitcoin sats) offered for the implementation**
No bounty yet. 

**Additional context**

**Comment by StellarStoic** [comment]
It would also be helpful to include toast messages on relay icons toggles. I still don't know what every relay Icon represents.
