### ISSUE TITLE
what is this? 

### ISSUE THREAD

**Issue by nilskp** [vitorpamplona/amethyst#458]
Not sure what's going on here. Is this a retweet UI issue, or something else.
Sorry if this is the wrong place to ask this question.
![Screenshot_20230618-204056~2](https://github.com/vitorpamplona/amethyst/assets/74843/ffd17827-cfb0-4ead-b137-2cfce83ec6eb)
![Screenshot_20230618-204106~2](https://github.com/vitorpamplona/amethyst/assets/74843/c9e035cd-c46a-4460-aef0-7e53e40a658a)

**Comment by vitorpamplona** [comment]
Yep, it's a retweet by Mandrik on Rizzo's post :)

**Comment by nilskp** [comment]
Ok, so can we agree that retweets perhaps could need some improvement? Or am I the only one struggling here?
