### ISSUE TITLE
[Request] Dark Mode Toggle Switch

### ISSUE THREAD

**Issue by manakill** [vitorpamplona/amethyst#46]
Dark mode manual toggle switch.

Most of my phone is in Dark Mode but this app forces Light for some reason.

**Comment by spidyhackx** [comment]
Yeah. I hate it :(

**Comment by KotlinGeekDev** [comment]
@vitorpamplona I think this issue can be closed.

**Comment by KotlinGeekDev** [comment]
@vitorpamplona I think this issue can be closed.

**Comment by vitorpamplona** [comment]
The switch setting has been implemented a few months ago.
