### ISSUE TITLE
[FEATURE] Ask for confirmation before deleting account 

### ISSUE THREAD

**Issue by GameOverFlowChart** [vitorpamplona/amethyst#464]
It's too easy to accidentally deleted an account while trying to switch them. Deletion should at least require to confirm an "are you sure?" message. Would be even better to hide the deletion button at the bottom of the "edit profile" menue instead.

**Comment by davotoula** [comment]
Is this still relevant? I see the below warning when trying to logout... 

![Screenshot_20230627-214816.png](https://github.com/vitorpamplona/amethyst/assets/1747287/ceb7b703-b990-43cc-9722-b7098936ad70)

**Comment by GameOverFlowChart** [comment]
Just checked it, seems like the last update introduced it.
