### ISSUE TITLE
RichText Bug while removing chars [Video]

### ISSUE THREAD

**Issue by KushGene** [vitorpamplona/amethyst#48]
Using Pixel 7 with GrapheneOS.
Amethyst 0.11.0

Watch Video for demo.
https://youtube.com/shorts/N5YIPm-ROtg

If writing, and removin chars, the Spacey between the words will be removed too sometimes.

**Comment by vitorpamplona** [comment]
Hum.. does this happen with other words? It looks like an autocompletion gone wrong. I don't think we change the text in any way that would create this bug. Hum...

**Comment by KushGene** [comment]
I have the problem only with Amethyst. And it is also caused with every word.

**Comment by anton-isidore** [comment]
This is happening to me as well. Only in Amethyst.

**Comment by vitorpamplona** [comment]
Does it happen on other input fields, like on messages or chats, or on the search bar?

**Comment by anton-isidore** [comment]
I have just tried in search bar and it is happening as well.

**Comment by vitorpamplona** [comment]
Hum... that means it's probably an Android Compose bug. We will need to wait for Google to release a fix. :(

**Comment by vitorpamplona** [comment]
This is an issue only with the default keyboard of GrapheneOS not working well with the Jetpack Compose UI library. Changing the keyboard to a more modern one fixes this. 

More: https://github.com/vitorpamplona/amethyst/issues/154
