### ISSUE TITLE
[BUG/TYPO]  Typo, Cashu Redeem description is "Reedem"

### ISSUE THREAD

**Issue by findingsov** [vitorpamplona/amethyst#487]
Typo: Redeem is mispelled in description
 Reedem Cashu

In file: 
![Screenshot 2023-07-03 at 4 41 40 PM](https://github.com/vitorpamplona/amethyst/assets/113792100/410e7875-1b91-4ad3-862b-10d4fe4e82b3)

**To Reproduce**
Click Redeem Cashu on a Cashu token.

**Comment by vitorpamplona** [comment]
Thank you @findingsov

**Comment by findingsov** [comment]
Thanks for implementing this feature!
