### ISSUE TITLE
Minor bug: Text with ellipsis (...) rendered as clickable link

### ISSUE THREAD

**Issue by ahanniga** [vitorpamplona/amethyst#49]
Issue is illustrated below.

<img width="305" alt="image" src="https://user-images.githubusercontent.com/28892939/215119230-bc6a87c5-43db-4682-9241-755b5905599c.png">

It appears that Patterns.WEB_URL allows this! Maybe this is a better regex, works for me: 

```
(http|https):\/\/([\w_-]+(?:(?:\.[\w_-]+)+))([\w.,@?^=%&:\/~+#-]*[\w@?^=%&\/~+#-])
```

**Comment by ahanniga** [comment]
Just another comment... I noticed that abbreviations such as e.g, n.b and i.e also get the link treatment. 
I think it's better therefore not to make assumptions about the text and use the scheme/prefix provided. After all, that's what it's there for!

**Comment by vitorpamplona** [comment]
I believe this was fixed a few versions ago. Closing it for now
