### ISSUE TITLE
[BUG] Redeeming cashu tokens to alby lightning address fails

### ISSUE THREAD

**Issue by vnprc** [vitorpamplona/amethyst#490]
**Describe the bug**
When attempting to redeem a cashu token to my LUD-16 getalby.com lightning address I get a "Token melt failure: timeout".

**To Reproduce**
1. Go to cashu.me, create a lightning invoice, redeem it for ecash tokens, click "send ecash" and copy the cashu token string to your clipboard. Or get a valid cashu ecash token via other means.
2. In amethyst, DM the ecash token to yourself to ensure no one else can claim it.
3. In the DM view you should see a "redeem" button in place of the ecash token text. Click it.
4. If you have a getalby LN address set on your profile you should see a "Token melt failure: timeout" error.

**Expected behavior**
No errors. Expect a lightning payment to my LN address.

**Device (please complete the following information):**
 - Phone Brand/Model [e.g. Pixel 7 Pro]: moto g power 2021
 - Android Version [e.g. 33]: 11
 - App Version [e.g. v0.20.3]: v0.64.4

**Comment by findingsov** [comment]
Confirming I had the same issue with getalby.   I was using a legends mint for these tests.  What were you using vnprc?   If you were using legends also, I can try later with my own lnbits instance or the 8333 mint.

**Comment by callebtc** [comment]
Hey there, 

The reason might've been that the LN node simply failed to find a route.

Client-side, the `POST /melt` call should have a very long (or infinite) timeout, as this call will block until the payment either succeeds or fails.

That should hopefully resolve the issue. Following further updates!

**Comment by vnprc** [comment]
@findingsov I was also using legend.lnbits.com

**Comment by vitorpamplona** [comment]
I believe this was resolved lately in our Cashu redesign. Let me know if it still happens otherwise.
