### ISSUE TITLE
[BUG] cannot zap creator using live events hosted by zap.stream 

### ISSUE THREAD

**Issue by davotoula** [vitorpamplona/amethyst#492]
**Describe the bug**
cannot zap creator using live events hosted by zap.stream . I suspect zap.stream is used for the zap rather than the content creator 

**To Reproduce**
Go to a live event hosted by zap.stream 
Click on the large zap icon 
Zap fails with error "User does not have a lightning address setup tO receive sats" 

**Expected behavior**
Zap should succeed 

**Video and Screenshots**
![Screenshot_20230705-221320~2.png](https://github.com/vitorpamplona/amethyst/assets/1747287/a7572709-2324-4987-a1f5-245060bff57f)

**Device (please complete the following information):**
 - Phone Brand/Model Pixel 7 Pro
 - Android Version 33
 - App Version V0.65.1-PLAY

**Comment by vitorpamplona** [comment]
I think this was fixed a few weeks back. Let me know if it still a problem
