### ISSUE TITLE
android notifications for DM

### ISSUE THREAD

**Issue by AndySchroder** [vitorpamplona/amethyst#494]
**Is your feature request related to a problem? Please describe.**
Have to regularly open amethyst to see if anyone messaged me.

**Describe the solution you'd like**
Show an android notification like my e-mail or jabber client that shows me when a new message comes in. I'm assuming this means a background process is required and also you should be able to set an interval to poll (or maybe nostr keeps websockets open all the time so you'd only need to poll of the socket breaks?).

**Bounty (in Bitcoin sats) offered for the implementation**
50,000 sat

**Additional context**
If people are going to use nostr to replace all other messaging systems, it needs to be quick.

I realize some people have phones that are locked down and don't let apps stay awake all the time and rely on centralized push notification services, but for users that have phones that don't try to control us so much, we should be able to receive notifications and do it in a decentralized way.

**Comment by vitorpamplona** [comment]
Hum... are you using the Play Edition? Can you check if your notifications aren't disabled in the Android Settings / Apps / Amethyst? 

We have had notifications for DMs for almost 3 months now...

**Comment by AndySchroder** [comment]
No, F-droid. Notifications are indeed enabled in android settings.

I realize google play notifications use less battery, but I don't have google play services installed for very intentional reasons!

**Comment by vitorpamplona** [comment]
Yep, sorry, we haven't found a way to make notifications work in the FDroid version yet. :(

**Comment by AndySchroder** [comment]
I'd check the architecture of these. They seem to work well with notifications.
- https://f-droid.org/en/packages/com.b44t.messenger/
- https://f-droid.org/packages/com.tutpro.baresip.plus/
- https://f-droid.org/en/packages/com.fsck.k9/
- https://f-droid.org/en/packages/com.xabber.android/

**Comment by vitorpamplona** [comment]
PushNotifications for the F-Droid flavor was Released on: https://github.com/vitorpamplona/amethyst/releases/tag/v0.80.1

Bouty should go to @KotlinGeekDev

**Comment by AndySchroder** [comment]
Will test as soon as it shows up in F-droid.

**Comment by davotoula** [comment]
You will have to install a third party notification app:

https://snort.social/nevent1qqszny5afrjj85577ecyajdcmcprq32wyj9l9ytjtmhqh0epd5pl35qpz9mhxue69uhkummnw3ezuamfdejj7q3qgcxzte5zlkncx26j68ez60fzkvtkm9e0vrwdcvsjakxf9mu9qewqxpqqqqqqzkpy3zu

**Comment by AndySchroder** [comment]
Why do I need a third party notification app? The other applications I've referenced above don't need that. The intention of my bounty wasn't to require a third party notification app.

**Comment by vitorpamplona** [comment]
Because that is the decentralized way of doing it. This allows you to put your own notification severs up, or use any other service of your choosing. In that way, you are not tied to Amethyst as a notification provider.

**Comment by AndySchroder** [comment]
Yes, but why can't the app stay connected directly to the relays?

**Comment by vitorpamplona** [comment]
Way too much battery use. This version uses a simpler approach that can be shared among any app and significantly saves battery

**Comment by AndySchroder** [comment]
Do the relays send a lot of data that I need to ignore or is it just because you are typically connected to many relays whereas with an e-mail server you are only connected to one server?

**Comment by vitorpamplona** [comment]
The later. Keeping connections to all relays alive all the time is quite costly. Now imagine if all nostr apps have to keep their own connections alive in a single phone.

**Comment by KotlinGeekDev** [comment]
Exactly what @vitorpamplona said.

**Comment by AndySchroder** [comment]
Any more details on the third party notification app and server? There is not much in the link above and it's not all in English.

Is there an account required on the third party notification server to let it know what events you want to watch or does it communicate what events and relays you want to listen on every time you make a connection? Wondering if this is going to evolve into something similar to an e-mail server, except a lot dumber.

**Comment by KotlinGeekDev** [comment]
@AndySchroder you can just download Ntfy app, then restart Amethyst, and tap on the Notifications tab.

**Comment by KotlinGeekDev** [comment]
Then you choose Ntfy in the dialog that opens, and that's it.

**Comment by KotlinGeekDev** [comment]
@AndySchroder there is no account required(for the vast majority)

**Comment by megaptera21** [comment]
How can I get this feature running if I use a private nostr relay? I assume that I also have to run a private push server, right?

**Comment by KotlinGeekDev** [comment]
@megaptera21 currently the Amethyst push server is hardcoded in the app, so even if you do run a private push server, it is not configurable(for the moment).

**Comment by KotlinGeekDev** [comment]
Please @AndySchroder did it work?

**Comment by AndySchroder** [comment]
Can you try sending a message to me at npub1h3ga3tac4uc0c6ld8uuu95q9dw23c783q4d3mtn9crwsqmgehlxsvue0l0 ?

**Comment by AndySchroder** [comment]
So, Ntfy connects to many push servers, but the benefit is it synchronizes the wake up time for all the servers to the same time and that is way more efficient than different apps doing wake ups at different (random) times?

**Comment by KotlinGeekDev** [comment]
> So, Ntfy connects to many push servers, but the benefit is it synchronizes the wake up time for all the servers to the same time and that is way more efficient than different apps doing wake ups at different (random) times?

Ntfy acts as push notification manager for other apps(the ones that choose to integrate it). As for push servers, it depends on how you configure Ntfy(primarily).

**Comment by AndySchroder** [comment]
I was able to get some people to send me test messages. Notifications came up, but then I swiped them to go away. Shortly after, the notification came back again. Seemed to happen 2 or 3 times for each message.

**Comment by KotlinGeekDev** [comment]
@AndySchroder cool! Please does that problem happen with the latest version?
