### ISSUE TITLE
[BUG] App crash when creating note with @ and any url (Pixel)

### ISSUE THREAD

**Issue by davotoula** [vitorpamplona/amethyst#495]
**Describe the bug**
App crashes when I attempt to write a note with an @ mention followed by an URL. 

**To Reproduce**
Reply to a note or create a new note 
Add any @ mention
Add any URL

**Expected behavior**
Note is successfully created 

**Video and Screenshots**
N/A

**Device (please complete the following information):**
 - Phone Brand/Model . Pixel 7 Pro
 - Android Version 33
 - App Version 65.1
 - Accessibility mode activated because Read Screen is on
 
Note: I will debug it locally to see if it's something specific to the note I'm trying to reply to

**Comment by davotoula** [comment]
So far only able to reproduce it on my pixel 7 pro.

Any @ followed by any url will cause the crash.

I suspect it's the preloading of url preview causes the crash as the crash happens while I'm typing the url.

**Comment by davotoula** [comment]
Just before crash I see the below error:
`java.lang.IndexOutOfBoundsException: setSpan (212 ... 253) ends beyond length 207
                 	at android.text.SpannableStringInternal.checkRange(SpannableStringInternal.java:493)
                 	at android.text.SpannableStringInternal.setSpan(SpannableStringInternal.java:199)
                 	at android.text.SpannableStringInternal.setSpan(SpannableStringInternal.java:186)`

I suspect it has to do with colouring the link. The problem is that app assumes full npub but it gets shortened somewhere in the call stack (npub1adfg:sdfsdf).

Not sure whether the above error causes the crash.. I'll keep looking.

**Comment by davotoula** [comment]
I have a workaround for the app crash. The above error (`setSpan (212 ... 253) ends beyond length 207`) is causing a crash when AndroidAccessibilitySpannableString is used by the system.

This was happening for me because I had "Reading mode" enabled in my Accessibility settings.

At least now the app crash isn't happening but the error is still there and it may be preventing URL preview in the note compose. I'll keep looking

**Comment by KotlinGeekDev** [comment]
Please @davotoula does this issue still occur?

**Comment by davotoula** [comment]
Yes
