### ISSUE TITLE
I want to group Amethyst notifications.

### ISSUE THREAD

**Issue by ShinoharaTa** [vitorpamplona/amethyst#501]
My device is a Pixel 7a with Android 13.
I am concerned about the behavior of Amethyst when running in this environment, so I have created this Issue.

Each Amethyst notification that arrives at my terminal is displayed separately.
Ideally, I think notifications from the same application should be grouped together, like Gmail.
When I receive a lot of Zaps as well as DMs, the notification box is sometimes overflowing with unread messages, and I suggest that this should be improved.

![](https://i.nostrimg.com/96db836df18203f981ca11524fbcbb63ca0db2e40d01ddb629b1eb3687c12417/file.png)

*npub:npub1l60d6h2uvdwa9yq0r7r2suhgrnsadcst6nsx2j03xwhxhu2cjyascejxe5
*my account: shino3

**Comment by vitorpamplona** [comment]
Yep, that has been in the plans for a while. We just never found the time to code it. :(
