### ISSUE TITLE
[BUG] App crashes when switching languages.

### ISSUE THREAD

**Issue by ShinoharaTa** [vitorpamplona/amethyst#503]
Thanks for the latest release.

I was in the Japanese community and saw everyone's appreciation.
I decided to raise an Issue because I received a report that there was a bug in it.
We have received reports of crashes when switching languages.

Once I get the report I will add the environment in a comment.

■日本人向け - for japanese.

使用環境を記載してください。以下はテンプレートです

-- テンプレート --
Device: （例）Google Pixel 7a
OS Ver: （例）Android 12
Amethyst Ver:（例）v0.68.2-PLAY
Result: Crash / Safe

**Comment by ShinoharaTa** [comment]
Device: SONY Xperia 5 II (SO-52A)
OS Ver: Android 12
Amethyst Ver: 0.68.2 PLAY
Result: Crash

**Comment by ShinoharaTa** [comment]
Nostrでの投稿にクラッシュのヒントがありました。
その投稿を引用します。

from: @akiomik 

> Crashes with API Level 32.

https://imgproxy.snort.social/krMdnO7xWCqUNIgMKJgnK3FQAvAtmKtB3RTmatRYcVU//aHR0cHM6Ly9pLm5vc3RyaW1nLmNvbS81NWM1ODIxNjg4ZThhODVjMTg0NGY4ODYyOGE3Yzk0ZmM3ZjdhYjQ0M2IyMzQ5MGIxYzY3MzEwNWI3NWQ2ZjdlL2ZpbGUucG5n

https://snort.social/e/note1gfj4xjp78yawef6n0f6fva0hxxx2hzh4rr580q3vju8htnw86ptsg0gnw6

**Comment by ncy35** [comment]
Device: xperia 1ⅲ
OS Ver: Android 12
Amethyst Ver:（例）v0.68.2-PLAY
Result: Crash
