### ISSUE TITLE
[FEATURE] hash to profile?

### ISSUE THREAD

**Issue by ghost** [vitorpamplona/amethyst#508]
**Is your feature request related to a problem? Please describe.**
One of the problems with social media or "things on the internet" that have human contact is verifying who "send things" or "receive things". You are never sure who is on the other side of the screen. In this case, Twitter has an interesting idea of adopting [a different color scheme for different types of verification](https://help.twitter.com/en/managing-your-account/about-twitter-verified-accounts), amethyst could adopt the same measure. For example, when someone clicks on the verified profile icon in amethyst they can see this:
![image](https://github.com/vitorpamplona/amethyst/assets/119423239/ec9e98e7-5b9c-48d9-be9b-88638dd181d5)

***Workflow:***
**1.** "Verified profile with blue: This demonstrates that someone is trusted with the verified profile"
Pros: 
- Every public or private profile verification depends on peers, which are people who will verify this information for other people.

Cons:
- One of the biggest issues with public or private profile verification is peer verification. For example, an public verification is verification that people do without necessarily having government, business, or social resources for verification. An example of public verification is always done in a distributed and decentralized way. An example of this is the issuance of undergraduate university degrees, which can be done publicly or privately, and are generally maintained by the entities themselves. For example, if I want to check "user x", I check if the university has the id of that "user x". Generally, the university does this for greater control, transparency, internal and external auditability, in order to avoid any fraud. 
     - But, the problem with someone's public or private verification is that there will always be someone who can use public or private information to create financial scams among the family members or contacts of that person in question.
     - Someone who is publicly trustworthy is not necessarily privately trustworthy. The same is true in reverse, someone who is privately trustworthy is not necessarily publicly trustworthy. This happens because no everyone is what it appears to be. 
    - Having the profile validated publicly or privately is not a way to say whether the person is responsible or has good conduct. Either he's the person you should or shouldn't trust. That's because we don't have an exact measure or general human verification math. What we have are legal means for greater reliability, for example, in business contracts you can be prevented from saying the source code under fine, imprisonment.
    - Just because more people think someone is what they say they are, that's not true. So, this is a classic pair-verification problem, "who checks this"? (Because if there is only verification of who the target audience is, verification is compromised)
- Dependence on authority: It is not possible to predict whether those who opt for a speech today are less right or wrong just through a paper or authority.
    - For example, in theory everyone is equal before the law, and in that sense there is no central authority for all people, only the "law" or "constitution" depending on your country of origin. But, the problem with the conception of "what is legal" is that there are many bad things that were legal in past. So, we must assume a certain skepticism towards what people imagine to defend by "law" at all costs and what is not yet law and should be considered. 
    - For example, a artist who talks about astronomy should have the same space as someone who knows astronomy. What differs from one to the other in my view is the level of social responsibility, transparency and knowledge. But the "law" grants that there is a space where people can talk, ask about subjects that they still don't dominate or want to study. This is what we call "freedom" on a level of studying, knowing. But, the general problem with this is that there can be people with a good speech that people trust blindly, compromising the work of those in the area of astronomy. Therefore, what is in the law must be considered, but to some extent we must consider the dependence on authority in some cases. So, the problem of dependency on authorship, is which authorities do we entrust certain matters to?
    - Dependence on authority creates an argumentative illusion, in which those who have power can intermediate or mediate the discourse, this I consider a mistake, everyone must have space. It is clear that in situations of health, science, art, law, I trust certain people in particular, not because of dependence on authority, but because of their good intentions, because they have studied a lot and have a lot to contribute. A common problem is that you depend on more and more centralized people to make certain decisions for yourself.
    - A general problem with trusting authority is validating certain profiles as you see fit. For example, there may be a lack of interest in profiles that belong to another type of social group.
    - People talk nonsense with or not undergraduate university degrees. What we can evaluate in certain situations are legal applications, when the discourse can lead to errors, as is the case of financial scams or illegal procedures with regard to law, reason, custom, politics. In this sense, authoritarian dependence makes no sense when there are legal measures to make some decentralized, fair and possible action possible.
    - Another interesting measure is to analyze what is being said and by whom and where it is being said, that is, to analyze the speech at various points or stages, to analyze the speech by context without relativism.

**2.** "Verified profile with color yellow: This demonstrates that someone has bought the verified profile"
   - Pros:
     - In case someone wants to contribute or pay monthly through the app, they can buy "verification" of the app, guaranteeing that it is the person who writes. This is initially interesting to think about.
- Cons:
    - "The problem with this feature is that this feature is interesting for some users, but not for everyone": For example, if the user has no interest in contributing to the community or the company, or if the user does not have the financial resources to do so. In other words, it doesn't make sense to have a resource that nobody uses or is willing to financially support the idea. 
       - Furthermore, this raises the problem that the user may feel bad about not having a verified profile because of not having money. 
       - Furthermore, this does not prevent malicious people with money from not using in bad faith, the purchase of fake profiles to send mass messages to nostr network users with paid verified profiles.
       - In other words, not everything can be solved with money or not everything can be solved only with money. So, "life is very complex" and "paid verification is always arbitrary, you can never escape", "because you never know the intentionality behind verified profiles with money".
    - "Depends on the centralized or decentralized entity": The problem with paid profile verification is that it creates a supply chain to which the user is inserted conditionally or unconditionally, and there may or may not be decentralization or centralization in all of this. This is bad for user experience because you always depend on third party infrastructure to send or receive certain trust space.  Even maintaining your own infrastructure costs some money or level of technical knowledge too. So in practice you trust people because all you have to do is trust people, there is no alternative when everything is paid for or costs something. 
        - For example, although the nostr(protocol) is decentralized, that doesn't stop people from liking certain apps. So, in a way, there's still some centralization to decentralized things in the sense of trust or choice. For example, on the one hand we have the common user who doesn't have the money to have his profile verified, on the other we have the common user who doesn't have the money to maintain his infrastructure.  Soon, the same user will depend on third-party services. 
        - These third-party services can become like monopolies or large centralizations in the sense of governance or even if there is some decentralization, it may be that the service is not of quality in relation to a centralized or monopolized outsourced service. 
        - This same case I described is the same as the IPFS network protocol, although IPFS is decentralized, there is a concept called: "gateways" which are "services centralized" for IPFS to work. So again, that's bad because you're dependent on a supply chain, and you have less freedom of choice to decide something.

**Describe the solution you'd like**
- A practical way is to adopt the verified profile through decentralized, centralized entities. For example, there could be different profile types verified with different colors, this would be similar to the idea of [Open Badges that nostr supports](https://github.com/nostr-protocol/nips/blob/master/58.md).  That feature is already partially implemented, but we could have this other Twitter feature as well despite some teething issues. 
- We should have a general decentralized verification that includes: payment verification, public verification and private verification. This is done through specific metadata, an general form of verification can be done by making these 4 previous or initial measures:  [qrcode](https://github.com/Path-Check/universal-verifier-app), open badges(2), verified-profile(3), [profile scheme](https://github.com/telamon/powmem).
   
**Bounty (in Bitcoin sats) offered for the implementation**
None, I'll check how I can help with the coding part, since I don't have any money.

**Additional context**
- If I am sick or going to the doctor, I should have a sick/going to the doctor profile status.
- An another way of verifying the profile is through recognition, specific awards that only that person has and that cannot be sent to anyone else.  I can have the badge as a 'award', 'reward' or 'prize' if what I have is a 'award', 'reward' or 'prize'.
- As I said, it's important to differentiate between "paid verification" and "public/private verification".
- As we can see above, there are 2 possibilities: paid verification, public or private verification
   - Paid verification is where you send or receive donations, money or status to verify a profile. 
   - Private or public verification is done without government, corporate or social resources.

**Comment by davotoula** [comment]
It's really cool seeing such thinking, thank you for the contribution @degaur.

Personally I think this (enhanced verification) sounds like a Nostr protocol feature level rather than a client level feature.

It should be discussed with the wider Nostr community for feasibility and inter-operability.

https://github.com/nostr-protocol/nips
