### ISSUE TITLE
I can't scroll down the window to see older messages on chat window without closing the keyboard

### ISSUE THREAD

**Issue by bitcoinuser** [vitorpamplona/amethyst#52]
Hi,

I can't scroll down the window to see older messages on chat window without closing the keyboard

![photo_2023-01-29_14-01-08](https://user-images.githubusercontent.com/1178856/215343090-01dcb709-f3a2-4360-b941-c30ce268da22.jpg)

**Comment by vitorpamplona** [comment]
I believe this has been fixed a while back. Closing it for now.
