### ISSUE TITLE
[BUG] Translation breaks image link

### ISSUE THREAD

**Issue by f321x** [vitorpamplona/amethyst#523]
**Describe the bug**
The auto translation tries to translate image URLs and breaks them by doing so.

**To Reproduce**
https://cdn.nostr.build/i/df3783dcdf7dd289ba02ba538dc039c8fe1d4db055e580b81604ed88c6af4ee0.jpg
got auto translated from welsh to German in Note 
nostr:nevent1qqsy5gtnyla7xmwe8a6yykl7qfxz4svmur8nhpmcqjs9ardfz2m42lspzemhxue69uhhyetvv9ujuurjd9kkzmpwdejhgq3q504jj42t6flu5l6n7e389e9mt8gxduhnzuyv7dq4gr95w20mmpqsxpqqqqqqzdrdgvk

**Video and Screenshots**
![Screenshot_20230725-173023](https://github.com/vitorpamplona/amethyst/assets/51097237/a51e37dd-76d1-4bdd-a6e0-0edcdc4c6faf)
![Screenshot_20230725-173016](https://github.com/vitorpamplona/amethyst/assets/51097237/bea5f397-af39-4281-b8e8-379849b18c9e)

**Device (please complete the following information):**
 - Phone Brand/Model [e.g. Pixel 7 Pro]:  Pixel 6a
 - Android Version [e.g. 33]: 13 GrapheneOS
 - App Version [e.g. v0.20.3]: 70.8 play apk

**Comment by vitorpamplona** [comment]
Just addressed this one: https://github.com/vitorpamplona/amethyst/commit/c20277a7542c7992948b8438712a2b3adb34d66c
