### ISSUE TITLE
[FEATURE] Thoughts on single form for NWC?

### ISSUE THREAD

**Issue by TonyGiorgio** [vitorpamplona/amethyst#527]
**Is your feature request related to a problem? Please describe.**
The current NWC form requires manually inputting client pubkey, relay, and secret. 

**Describe the solution you'd like**
Both Alby and Mutiny use the `nostr+walletconnect:` connect string. I don't know any other wallet that splits up the form. It becomes a real pain for the user to manually split apart the string. 

**Bounty (in Bitcoin sats) offered for the implementation**
I'm willing to do it, just want to know if a PR would be accepted to unify the form.

**Comment by vitorpamplona** [comment]
Is it not working? When you click the Alby button on the zap setup page, it goes over there, creates the key and the website sends it back to the app. I don't think people manually fill in those fields.

**Comment by TonyGiorgio** [comment]
That only works for the alby wallet? Should it not be a clean experience elsewhere for other wallets or should we submit a PR to have a "mutiny wallet" button too?

**Comment by vitorpamplona** [comment]
We can have a mutiny wallet for sure. As long as the list of supported wallets is small, it's fine. 

But it should work outside the use of the button as well. If you send a `nostr+walletconnect:` intent on Android, Amethyst/Onyx should pop up to open it. 

Unless there is a bug somewhere...

**Comment by TonyGiorgio** [comment]
Cool, didnt realize that was an option actually. Will give that a try and let you know if it doesn't work for whatever reason. Thanks!
