### ISSUE TITLE
I think on Chat window, if I follow an user, the messages should never be on New request tab, but instead on Known

### ISSUE THREAD

**Issue by bitcoinuser** [vitorpamplona/amethyst#53]
Hi,

I think on Chat window, if is an user I follow, the messages should never be on New request tab, but instead on Known.

Thanks.

**Comment by vitorpamplona** [comment]
Nice idea! I will code it.

**Comment by vitorpamplona** [comment]
Finally fixed this: [Moving follows to the known list.](https://github.com/vitorpamplona/amethyst/commit/81290f2b26b1487f55302a612ab8f0eccd200227)
