### ISSUE TITLE
[BUG] Deleting "not last" poll options in note breaks creation of poll

### ISSUE THREAD

**Issue by davotoula** [vitorpamplona/amethyst#532]
**Describe the bug**
Deleting a poll option that is not last in the list causes issues.

**To Reproduce**
1. Click to create a new note
2. Add two or more poll options
3. Delete poll options in the middle of the list

**Expected behavior**
Poll list can still be edited by adding new items or removing items.

**Actual behaviour**
1. Unable to add additional poll options
2. Unable to delete additional poll options
3. Bit random in terms what can be added / removed aftwards

**Device (please complete the following information):**
 - Phone Brand/Model: Pixel 7 Pro
 - Android Version: 33  
 - App Version: v0.71.0

**Comment by KotlinGeekDev** [comment]
Please @davotoula does it occur while creating the note, or after having created the note?

**Comment by davotoula** [comment]
The app didn't crash for me but the poll option became unusable... Just like you described.

**Comment by davotoula** [comment]
Bit better but still behaves funny when you delete middle options.

**Comment by KotlinGeekDev** [comment]
@davotoula please does this still happen again?

**Comment by davotoula** [comment]
Unfortunately yes. It feels a bit more resilient but you still get the following if you remove middle options and keep adding new:

When you add a new option you see values from and older deleted option

Delete middle option but instead the last option was deleted

Add middle option and an additional lady option appears with an old value

Some others 😂

**Comment by KotlinGeekDev** [comment]
> Unfortunately yes. It feels a bit more resilient but you still get the following if you remove middle options and keep adding new:
> 
> When you add a new option you see values from and older deleted option
> 
> Delete middle option but instead the last option was deleted
> 
> Add middle option and an additional last option appears with an old value
> 
> Some others 😂

I see :sweat_smile:
