### ISSUE TITLE
[BUG] URLs containing "-" may not become clickable link.

### ISSUE THREAD

**Issue by shion72** [vitorpamplona/amethyst#536]
**Describe the bug** 
The URLs that containing FQDN written in the following format does not become clickable link.
https:// **aaa.b-b.ccc** /

 **To Reproduce** 
Post the URLs that containing FQDN written in the following format.
https:// **aaa.b-b.ccc** /

**Expected behavior** 
URLs become clickable.

**Video and Screenshots** 
<img src="https://github.com/vitorpamplona/amethyst/assets/132278089/da0ab69b-3b23-4762-926d-a22cab00720a" width = "270px" height = "100px"> </br> <img src="https://github.com/vitorpamplona/amethyst/assets/132278089/a964e8d1-5046-4cc7-9c19-7a24b47a1491" width = "270px" height = "100px">

**Device (please complete the following information):**
 - Phone Brand/Model [Sony Xperia SO-52A]: 
 - Android Version [12]: 
 - App Version [0.71.0-PLAY]:

**Comment by KotlinGeekDev** [comment]
@vitorpamplona I think this can be closed.
