### ISSUE TITLE
[BUG] Rotating screen to landscape open sidebar menu

### ISSUE THREAD

**Issue by anthony-robin** [vitorpamplona/amethyst#538]
**Describe the bug**
When rotating the phone from portrait to landscape, the sidebar menu auto open and hide half the view width.

**To Reproduce**
Open Amethyst app in portrait then rotate it to landscape in the home view

**Expected behavior**
Sidebar navigation should be hidden and only a user action should make it appearing

**Video and Screenshots**
Happy to provide a screenshot if necessary to figure out the bug, let me know :)

**Device (please complete the following information):**
 - Phone Brand/Model [e.g. Pixel 7 Pro]: Pixel 6A
 - Android Version [e.g. 33]: GrapheneOS
 - App Version [e.g. v0.20.3]: V0.72.0-FDROID

**Comment by KotlinGeekDev** [comment]
Please @anthony-robin does this still happen?

**Comment by anthony-robin** [comment]
> Please @anthony-robin does this still happen?

Yes, still happen in v0.72.2-FDROID

**Comment by KotlinGeekDev** [comment]
@vitorpamplona there are two solutions for this, but with different trade-offs:
For solution 1: The trade-off is Activity recreation and redrawing of UI (with cached feed) during device rotation. Time to redraw is between 1s to 2.5s.
For solution 2: The trade-off is a rapid but noticeable closing of the menu drawer. Time to close is between 0.4s to 1s.
I'm thinking of settling with solution 2. Please what do you think?

**Comment by vitorpamplona** [comment]
Are these times on release or debug? Solution 2 seems fine for now

**Comment by KotlinGeekDev** [comment]
> Are these times on release or debug? Solution 2 seems fine for now

They are times on debug, gathered manually.

**Comment by vitorpamplona** [comment]
> They are times on debug, gathered manually.

That makes sense. Release will be much faster. :)
