### ISSUE TITLE
[FEATURE] Fullscreen video on stream view portrait to landscape mode

### ISSUE THREAD

**Issue by anthony-robin** [vitorpamplona/amethyst#539]
When opening a live stream in portrait and then turning phone to landscape mode, I would like the video to be automatically in fullscreen as does NewPipe or other video apps.

Thank you :)

**Comment by KotlinGeekDev** [comment]
@vitorpamplona I think we can both this issue and #525 at once, by making them options in the settings. Please, what do you think?

**Comment by vitorpamplona** [comment]
I am not sure why these two will be together, but this one doesn't seem to need a settings option. Unless I am missing something. The idea would be to make the live stream screen go full when the device changes orientation. 

We just need to be careful with the new folding designs out there. Many of them have squarish aspect ratios and I think in those cases, when people rotate their phones they don't want full screen. They are just fishing the orientation of the device.

**Comment by KotlinGeekDev** [comment]
> I am not sure why these two will be together, but this one doesn't seem to need a settings option. Unless I am missing something. The idea would be to make the live stream screen go full when the device changes orientation.
> 
> We just need to be careful with the new folding designs out there. Many of them have squarish aspect ratios and I think in those cases, when people rotate their phones they don't want full screen. They are just fishing the orientation of the device.

I see. The media player should just automatically adjust itself then.

**Comment by KotlinGeekDev** [comment]
Please @anthony-robin does this still happen again?

**Comment by davotoula** [comment]
Video expands to fullscreen but is overlayed with various comment elements.

![Screenshot_20240706-212915.png](https://github.com/vitorpamplona/amethyst/assets/1747287/3156cfe2-b305-468d-82f6-82763bda744e)

**Comment by anthony-robin** [comment]
@KotlinGeekDev I confirm @davotoula screenshot, interface overlap the video.

My original post was more about a way to simulate a user click on the fullscreen icon of the video player automatically when turning the phone as landscape. Not sure what could be done to support all devices screen size the more friendly as possible.

**Comment by KotlinGeekDev** [comment]
> @KotlinGeekDev I confirm @davotoula screenshot, interface overlap the video.
> 
> My original post was more about a way to simulate a user click on the fullscreen icon of the video player automatically when turning the phone as landscape. Not sure what could be done to support all devices screen size the more friendly as possible.

Yeah, thank you(and @davotoula for the feedback).

**Comment by KotlinGeekDev** [comment]
I looked into this, and it seems that there is an option to go full-screen when rotated in landscape mode. The button is located at the bottom right.
However, I am looking into how to make the full-screen mode the default behavior when rotated into landscape mode.
cc @anthony-robin @davotoula

**Comment by davotoula** [comment]
I can't reproduce it in 89.7. When I rotate to landscape video plays correctly in full screen

**Comment by KotlinGeekDev** [comment]
> Edit: sorry, for videos in feeds it works correctly. The issue still in live stream but to be honest it's just a click away so could be "as designed" to have the comment visible in landscape?
> 
> I can't reproduce it in 89.7. When I rotate to landscape video plays correctly in full screen

Got it. So I guess this issue can be closed then?(Unless @anthony-robin has any observations to make).

**Comment by anthony-robin** [comment]
The issue I opened was about the live tab when clicking a live stream. As there is only one video showing, going full screen would not conflict with other content contrary to the feed for example that might have several video players. 

The goal was to spare a manual click on the fullscreen icon of the player when turning device to landscape but keeping a real fullscreen experience with no Amethyst interface visible (same as NewPipe does on fullscreen).

If you think this cannot be done, so feel free to close the issue ;)
Thank you both for having a look into this :)

**Comment by KotlinGeekDev** [comment]
@anthony-robin  thanks for the response. It is still possible to make that the default behavior. Just wanted to hear your thoughts/reasons. :)

**Comment by anthony-robin** [comment]
When watching a video from Live section, I prefer a full focus on the video as I'm less interested in comments (for example the Euro 2024 football gamesthat was streamed last month is so much better in real fullscreen mode without chat comments) :)
