### ISSUE TITLE
[BUG] Discover not working

### ISSUE THREAD

**Issue by ondra-novak** [vitorpamplona/amethyst#544]
**Describe the bug**
Cannot see content of people i follow

**To Reproduce**
My kind:3 
```
{
    "content": "",
    "created_at": 1691438494,
    "id": "bc5951138fbe032304ebdd299f219aefd797b7f2d75ec0ecc55b10432b21ae07",
    "kind": 3,
    "pubkey": "8593bde32b52ab5218e69d0d24e36e44795de24d9b42d52312b02a04931bd196",
    "sig": "4459f01f10c8a1af0959857283c60c61211b524bbf55551e7a00cea542fb5d78e993e70755dc6bfd0be016f51ba0aa9c247d4feec3a633d7ad498780a7a1426c",
    "tags": [
        [
            "p",
            "eaf1a13a032ce649bc60f290a000531c4d525f6a7a28f74326972c4438682f56",
            "wss://relay.plebstr.com/"
        ],
        [
            "p",
            "0fe0b18b4dbf0e0aa40fcd47209b2a49b3431fc453b460efcf45ca0bd16bd6ac",
            "wss://relay.plebstr.com/"
        ],
        [
            "p",
            "045745ac0e90a436141a3addd95575c2ead47b613f45287283e5802ff7fd99fd",
            "wss://nos.lol/"
        ],
        [
            "p",
            "c69cdd8605e097448e0ead57b9249e0162405a56cb9cca8b696db939e886f8bb",
            "wss://nostr.novacisko.cz/"
        ],
        [
            "p",
            "68c14d1993aa7053d17023fc577d334618b05900f6c8a1d8419726b38bcbd8bf",
            "ws://nostr.novacisko.cz:10000/"
        ],
        [
            "p",
            "1021f50b98a00115490be641ec2339c0cd1b781e4a6a69f06e8fdbd021fde1dd",
            "wss://nos.lol/"
        ]
    ]
}
```
Application is connected to single private relay.

**Expected behavior**
Application should use relays to connect people i follow

**Device (please complete the following information):**
 - Uniherz Titan Slim
 - v0.72.2-PLAY

**Comment by vitorpamplona** [comment]
Thanks, @ondra-novak 

We don't use the relays from Kind 3 yet. The app only connects to relays specified in the Relay screen for now. 

> Application is connected to single private relay.

Does it load information that exists in that private relay? On the relay screen you can see how much data is being downloaded from the private key in bytes. You can also see if there are errors happening. 

Private relays is something new that we still have to test with the multiple implementations out there. So, I don't discard that there might be a bug somewhere on the auth process with your relay.

**Comment by ondra-novak** [comment]
what is correct behavior? Is it relay who need to discover and cache content of people followed by users on that private relay or the client should handle this? Each client works differently. Coracle discovers other relays

Private mean that relay has whitelist on pubkeys. Auth is there but doesn't block access for reading and discovering

**Comment by ondra-novak** [comment]
Thank you for explaining. I was confused as I tested many clients to find out how well my relay (in development) works with them. I am still unsure how Nostr routes and discover events and profiles and how relay can help with it
