### ISSUE TITLE
[REQUEST] Move "Broadcast" away from "Block / Report" in 3 dot menu

### ISSUE THREAD

**Issue by Git-Forked** [vitorpamplona/amethyst#550]
**Is your feature request related to a problem? Please describe.**
It's frustrating when I attempt to click "Block / Report" and instead accidentally hit "Broadcast" with no apparent way to undo a broadcast, and end up broadcasting a spam post I was attempting to ignore. 

**Describe the solution you'd like**
I would like to see the "Broadcast" moved away from the "Block \ Report".  Perhaps moving it under "Follow" would be a better spot for it.  Then above "Block / Report" would be "Add to Public Bookmark", which if accidentally clicked would be easy to undo.

Thank you for considering this QOL enhancement.

**Comment by atrifat** [comment]
I think this is a reasonable. Sometimes, i have also accidentally hit the wrong button like "Block / Report". I think i will send a PR later for this issue @vitorpamplona .
