### ISSUE TITLE
Same bugs of issue 25

### ISSUE THREAD

**Issue by bitcoinuser** [vitorpamplona/amethyst#56]
Hi,

See:

https://user-images.githubusercontent.com/1178856/215489205-c27e7074-b330-4738-b147-ddc61b8c2ea6.mp4

https://user-images.githubusercontent.com/1178856/215489242-5839e773-c583-47b9-a2e3-11200fd7e18f.mp4

cc @KotlinGeekDev

**Comment by KotlinGeekDev** [comment]
Will check it soon.

**Comment by KotlinGeekDev** [comment]
Please @bitcoinuser what version are you using?

**Comment by bitcoinuser** [comment]
> Please @bitcoinuser what version are you using?

0.11.5

**Comment by KotlinGeekDev** [comment]
Please @bitcoinuser can you upgrade and test again?

**Comment by bitcoinuser** [comment]
> Please @bitcoinuser can you upgrade and test again?

Will wait for updates on Playstore.

**Comment by KotlinGeekDev** [comment]
Oh, OK.

**Comment by KotlinGeekDev** [comment]
@bitcoinuser it seems 0.11.6 is already available on the Play Store.

**Comment by bitcoinuser** [comment]
> @bitcoinuser it seems 0.11.6 is already available on the Play Store.

For me it's not. Will see fdroid

**Comment by KotlinGeekDev** [comment]
OK @bitcoinuser please find out and test it. It seems to be working fine for me.

**Comment by bitcoinuser** [comment]
> OK @bitcoinuser please find out and test it. It seems to be working fine for me.(On the latest version)

Same problem 0.11.6

**Comment by KotlinGeekDev** [comment]
Hmm, that's really strange.

**Comment by KotlinGeekDev** [comment]
Please @vitorpamplona do you experience this as well?

**Comment by KotlinGeekDev** [comment]
OK. Will check it again.

**Comment by KotlinGeekDev** [comment]
Please @bitcoinuser does this issue still occur for you?

**Comment by KotlinGeekDev** [comment]
Please @bitcoinuser just to be clear, are you trying to go back to the feed, or are you trying to go to another note?

**Comment by vitorpamplona** [comment]
I think we should just block the navigation to the same route.

**Comment by KotlinGeekDev** [comment]
Right. Thanks for confirming.

**Comment by KotlinGeekDev** [comment]
@vitorpamplona I am not aware of a means of doing that. Will dig into it.

**Comment by KotlinGeekDev** [comment]
Please @bitcoinuser does this still happen?
