### ISSUE TITLE
[BUG]The previous post may remain in the text area

### ISSUE THREAD

**Issue by ncy35** [vitorpamplona/amethyst#561]
**Bug description**
The previous post may remain in the textarea

**To reproduce**
Here are the steps to reproduce the behavior:
1. Post.
2. Open a text area.
3. Posted sentences will remain as they are.
4. This phenomenon does not always occur. Sometimes it happens, sometimes it doesn't. When I try to reproduce it, it doesn't happen. I'm not good at leaving evidence.

**Videos and Screenshots**
When I try to take a picture, I can't. It happens suddenly.

**device:**
Xperia III
android 12
App 0.75.8

**Comment by shion72** [comment]
Same bug happens on my phone.

Phohe : Xperia5Ⅱ
OS : Android 12
App ver : 0.75.13 PLAY

**Comment by ShinoharaTa** [comment]
I am having trouble with the same bug on my Android.

Device: Google Pixel 7a
OS: Android 13
App ver: 0.75.13

**Comment by anp163** [comment]
I have also confirmed a similar phenomenon.

Phone: GooglePixel 7a
OS: Android13
App ver: 0.75.10-PLAY

**Comment by ncy35** [comment]
The text you've already posted will remain, not the draft. The same goes when replying to someone.

**Comment by ShinoharaTa** [comment]
@vitorpamplona 

Hi Vitor pamplona.
I found out how to reproduce this issue.
This may be a Japan-specific issue.

In Japanese, there is a process of inputting "Hiragana" in the IME and then converting it to Kanji.
Japanese can be spoken in Hiragana, and you can post even before pressing Return in the lower right corner of the IME.
The IME would have the status as Typing and would remain in the Text area.

https://i.nostr.build/n25M.jpg

https://i.nostr.build/0BM6.jpg

**Comment by ShinoharaTa** [comment]
This Keyboard app is called Gboard.
It is produced by Google and comes standard on devices in the Japanese market (e.g., Pixel series).

**Comment by ShinoharaTa** [comment]
@vitorpamplona 

Hi. 
This bug has not occurred in recent builds. It appears to have been resolved.

**Comment by vitorpamplona** [comment]
Nice. Let's close it until it shows up again :)
