### ISSUE TITLE
[BUG] Allow to translate "mute" word

### ISSUE THREAD

**Issue by anthony-robin** [vitorpamplona/amethyst#567]
**Describe the bug**
The "mute" word in the home screen popup filter menu is not translatable

**To Reproduce**
1. Go to main screen
2. Click on "All follows"
3. See "mute" word

**Expected behavior**
A way to translate this word in crowdin

![IMG_20230903_184451](https://github.com/vitorpamplona/amethyst/assets/5428510/da5289f8-1ccf-44e8-af95-5b8fa1d9d046)

**Comment by davotoula** [comment]
I've also seen this. I believe it's the name of the list and not a word defined in amethyst.

**Comment by KotlinGeekDev** [comment]
Please @anthony-robin and  @davotoula do you still see this?

**Comment by anthony-robin** [comment]
> Please @anthony-robin and @davotoula do you still see this?

Hi @KotlinGeekDev, yes I still see it in the latest `v0.78.2-FDROID` version :)

**Comment by davotoula** [comment]
I still see the "mute" word in my list. I don't believe it's a bug, it's the actual name of the list. You cannot translate that just like you cannot translate a hashtag?

A thing has changed though. I used to be able to see all muted threads when selecting this list. Now it's blank (I guess spam filter blocks it).

It was a nice feature to view muted posts for anything interesting.

![Screenshot_20230927-211443.png](https://github.com/vitorpamplona/amethyst/assets/1747287/d8b6462a-7bf5-4c00-88db-38c70a3e0b92)

**Comment by KotlinGeekDev** [comment]
@davotoula I think a fix can be making the word a string resource, so that it can be translated.

**Comment by davotoula** [comment]
But isn't the word coming from the relay actually?

We don't want different language clients have different names for that list?

**Comment by davotoula** [comment]
Go for it! 😂

At the same time, can you look into why posts in that list are hidden now? They used to be visible!

**Comment by KotlinGeekDev** [comment]
@davotoula you're right. It seems to come from the relay.

**Comment by davotoula** [comment]
Would it be possible to treat the mute list in a special way... And show a translated word in the client rather than just displaying what is returned from relay? 

It could work if "mute" word is a standard in nostr... Otherwise it feels a bit unclean?

**Comment by KotlinGeekDev** [comment]
That's the thought I had as well.

**Comment by KotlinGeekDev** [comment]
In a sense, yes.

**Comment by KotlinGeekDev** [comment]
> A bit like a Decorator.. Pass most list names through from the relay but capture "mute" and display it translated?

I actually found another way to do it: translate the word when it is being provided from the ViewModel.

**Comment by vitorpamplona** [comment]
The issue here is that many clients use a "d=mute" list from NIP-51's 30000 event kind, instead of the mute list from 10000, which has no name. 

We can probably migrate to event kind 10000 moving forward and stop using the mute list. That will allow the app to have a mute entry and translate it via crowdin.

**Comment by KotlinGeekDev** [comment]
> The issue here is that many clients use a "d=mute" list from NIP-51's 30000 event kind, instead of the mute list from 10000, which has no name.
> 
> We can probably migrate to event kind 10000 moving forward and stop using the mute list. That will allow the app to have a mute entry and translate it via crowdin.

I see. Makes sense.

**Comment by KotlinGeekDev** [comment]
Please @anthony-robin I dont know if this is still an issue for you. @vitorpamplona  maybe this can be closed already?(assuming clients have migrated to kind 10000 mute lists)

**Comment by anthony-robin** [comment]
Let's close the issue. Thank you for working on this :)
