### ISSUE TITLE
[BUG] can't remove nostr.band from relays

### ISSUE THREAD

**Issue by Brian1-A** [vitorpamplona/amethyst#594]
**Describe the bug**
I am trying to remove all relays except one private relay i want to have on an account.  Once i remove all relays except the one i want and publish, nostr.band continues to be on the relay list.  I cant remove it.  Furthermore, if i turn off all the green options on nostr.band to try and eliminate its interaction with my npub...it will eventually turn back on automatically and start feeding notes from nostr.band into my account.  

I also lightly tested this on another android phone and there were several relays i could not remove ( latest version downloaded via google play store ), but it was not my phone so unable to reproduce.

**To Reproduce**
1. Go to amethyst 0.75.14 f droid
2. Click on user profile pic >> relays
3. Remove all relays, post.  Return to relays page
4. See nostr.band is still present.  

**Expected behavior**
I expect to be able to remove all relays and create the relay selections i choose and for these relays to not return unwanted.  No relays should persist in my nsec if i dont want them to.

**Device (please complete the following information):**
 - Phone Brand/Model [e.g. Pixel 7 Pro]: google pixel 4
 - Android Version [e.g. 33]: 13
 - App Version [e.g. v0.20.3]: 0.75.14

**Bounty (in Bitcoin sats) offered for a solution**
If you can update so that the app can always clear out all relays, 100000 sats.  Bonus sats: have an option to start up amethyst with an nsec with no relays to begin with ( family/friends mode ), another 100000 sats.  Cheers 🤙

**Comment by vitorpamplona** [comment]
The app needs a NIP50 compliant replay to run the search functions. Does any relay on your list include nip50?

**Comment by Brian1-A** [comment]
Ahh.  No it does not.  I am trying to just use my start9 server private relay alone and the start9 OS team confirmed their relay service is not nip 50 compliant and no plans to :( 

Thank you for answering.
