### ISSUE TITLE
[FEATURE] Mute words list

### ISSUE THREAD

**Issue by greenart7c3** [vitorpamplona/amethyst#597]
**Is your feature request related to a problem? Please describe.**

Mute words

**Describe the solution you'd like**

See nostr:nevent1qqs03gj7vm64jv3h2g8er2rgc6n9fgcplvggfkx9e3kuse730tgmz9gprdmhxue69uhhyetvv9ujuemjv4jkuctjwsmkxvewvdhk6q3qr0rs5q2gk0e3dk3nlc7gnu378ec6cnlenqp8a3cjhyzu6f8k5sgsxpqqqqqqzyu2a8m

**Bounty (in Bitcoin sats) offered for the implementation**

Bounty details in

nostr:nevent1qqs03gj7vm64jv3h2g8er2rgc6n9fgcplvggfkx9e3kuse730tgmz9gprdmhxue69uhhyetvv9ujuemjv4jkuctjwsmkxvewvdhk6q3qr0rs5q2gk0e3dk3nlc7gnu378ec6cnlenqp8a3cjhyzu6f8k5sgsxpqqqqqqzyu2a8m

**Additional context**

**Comment by OrigiSize** [comment]
@greenart7c3 Can you paste in the bit about the solution and bounty? How do you view those nostr:nevents?

**Comment by greenart7c3** [comment]
> @greenart7c3 Can you paste in the bit about the solution and bounty? How do you view those nostr:nevents?

You can paste the nevent in the search field in amethyst to see the post
![Screenshot_20230920-190337.png](https://github.com/vitorpamplona/amethyst/assets/115044884/f0749b9e-c83b-42d9-8f94-59334a2fe6fd)

**Comment by davotoula** [comment]
🚀
