### ISSUE TITLE
[BUG] long note not folded if low character count

### ISSUE THREAD

**Issue by libertas-primordium** [vitorpamplona/amethyst#598]
**Describe the bug**
A note with a lot of newlines but low character count is not automatically folded in the feed view.

**To Reproduce**
See this example:

nostr:nevent1qqs0lk0a0qg8ulha6lgp4yk8t09mgesy272qqyqpytpgwk8snr0m4tspz3mhxue69uhhyetvv9ujuerpd46hxtnfdupzqrgxfq9scm3mu0y6rfja0e4uyzgjyl24hax80m4kqda6wamvxq8vqvzqqqqqqy08fv2t

**Expected behavior**
This note is very long. It should be folded. 

**Device (please complete the following information):**
 - Phone Pixel 7 Pro
 - Android Version 13
 - App Version 0.76.0-PLAY

**Comment by davotoula** [comment]
I'm looking into this.

**Comment by davotoula** [comment]
It's a pretty straight forward issue.

The "Show more" code counts line break (\n) as a single character while `\n` in fact takes a whole row.

I'm thinking a fix that will count empty lines as a full row of characters.

**Comment by OrigiSize** [comment]
@libertas-primordium Can you add a more descriptive title?

**Comment by libertas-primordium** [comment]
Whoops! Yes I'll update the title.

**Comment by davotoula** [comment]
https://github.com/vitorpamplona/amethyst/pull/608
