### ISSUE TITLE
[BUG] can't unblock user

### ISSUE THREAD

**Issue by 11100010** [vitorpamplona/amethyst#658]
**Describe the bug**
Can not unblock

**To Reproduce**
1. Click on 'unblock'
2. Nothing happened

**Expected behavior**

**Video and Screenshots**

**Device (please complete the following information):**
 - Android Version:  ColorOS V12.1
 - App Version: 0.79.13

**Bounty (in Bitcoin sats) offered for a solution**

**Comment by davotoula** [comment]
I've seen this before.

If the profile is on the automated spammer list it will get blocked again as soon as you unblock.

If you follow a profile it will not get blocked automatically so you can unblock and quickly follow.

**Comment by 11100010** [comment]
it's pretty strange that some users can be unblocked, but others can't. 

> I've seen this before.
> 
> If the profile is on the automated spammer list it will get blocked again as soon as you unblock.
> 
> If you follow a profile it will not get blocked automatically so you can unblock and quickly follow.

I took a look at "Spammers" in "Security Filters". Pretty sure there was nothing there.

**Comment by 11100010** [comment]
another account doesn't encounter this problem. look likes something's wrong with only the first account. no idea why.

so it's not really a bug from amethyst. 

thank you for your help.

**Comment by josedorrego** [comment]
> another account doesn't encounter this problem. look likes something's wrong with only the first account. no idea why.
> 
> so it's not really a bug from amethyst.
> 
> thank you for your help.

I have exactly the same problem.  Can't unblock a user, but created a new test account, and was able to block it and then unblock it.

Did you get to figure out what the problem is?

**Comment by davotoula** [comment]
Have you tried following the user and see if it resolves the auto block issue?

**Comment by josedorrego** [comment]
> Have you tried following the user and see if it resolves the auto block issue?

Not sure how to check this.  

I think I was already following him before blocking him.  Now I can only see the DM message (envelope icon) and the unblock button (which does nothing).

**Comment by josedorrego** [comment]
Ok, just checked my "Follows" list and it's not there.
How do I get the "Follow" option instead of the "Unblock" one?
