### ISSUE TITLE
Blur images when not following the user

### ISSUE THREAD

**Issue by greenart7c3** [vitorpamplona/amethyst#68]
Blur images and profile pictures by default if you don't follow the user.

**Comment by vitorpamplona** [comment]
I don't know if this is a good idea. We don't want to limit the appeal of the Global feed. 

But, to counter spam and other explicit content, if a post has any report, from anyone, it doesn't not preview any links, images, videos or ln invoices. You can still click on them and see it, but no auto-leading. 

Would that work for you?

**Comment by greenart7c3** [comment]
Yes, that would work
