### ISSUE TITLE
Default relays not working

### ISSUE THREAD

**Issue by greenart7c3** [vitorpamplona/amethyst#70]
Today all default relays are not working in the app. Using a web client the relays work fine.
Tried latest version and the version from the play store

**Comment by vitorpamplona** [comment]
Which app version are you using?

**Comment by greenart7c3** [comment]
tried on 0.11.5 and 0.12.0

**Comment by vitorpamplona** [comment]
Yep, all relays are super busy these days. :(

**Comment by greenart7c3** [comment]
Yeah. It loaded my relays now.
Could you fix the relay list when there's a lot of relays when you have time?

![Screenshot_20230203-105337.png](https://user-images.githubusercontent.com/115044884/216621460-7e918d96-5ce2-4984-a89c-ff5179c5eb6c.png)

**Comment by vitorpamplona** [comment]
We can't just keep adding relays. The more we add the more connections the app has to handle and the more we add as default, the more we break them. We will need to find a different solution. Users must choose which relay they prefer.

**Comment by hannpet** [comment]
Did you have a look at the Gossip-client, it dynamically assigns Relays depending on the followed persons.

**Comment by vitorpamplona** [comment]
Yep, but this is even earlier. I might need to add a relay option on login to download the rest of your relay list.
