### ISSUE TITLE
Feature Request: Share note outside of app

### ISSUE THREAD

**Issue by dtrammell** [vitorpamplona/amethyst#71]
Problem:  I frequently share things from within my Twitter app to people outside of the app via email, or Signal, or other apps on my phone.  Amethyst does not have an external app share feature.  Amethyst does not have a webapp interface, so there is nowhere for it to link to in order to reference posts.

Solution:  

1. Add a configuration parameter for the user's favorite webapp Nostr client.  I personally use Iris.to
2. Add a share entry in the three dots button at the bottom of each post that allows you to send some pre-formatted data to another app on the user's device, linking the note in the configured webapp's URI format for direct view of a note.
 
I frequently share Tweets in this manner via GMail, Signal, Slack, and Discord, but the Share option should really work with any app that the user can select from the device.  Also provide a "Copy Link" option under the Share menu.

**Comment by maxmoney21m** [comment]
[NIP-21](https://github.com/nostr-protocol/nips/blob/master/21.md) would be the correct way to do this, but it would only work for people who already had a nostr client registered to handle `nostr:` URIs. It probably makes sense to allow copying a web URL until NIP-21 is more widely adopted at least.

This should be a relatively quick fix, but again I don't know where to put the URL setting as we don't have a settings dialog @vitorpamplona, ideas?

**Comment by vitorpamplona** [comment]
I am more worried about how to add this to the UI.. we have way too many options already.. with too many complaints of Amethyst been too complicated.

**Comment by maxmoney21m** [comment]
This is partly why I suggested #216. We could probably also merge the "Copy" methods in the same way, and add a Share button. So the result for the menu would be:

- Follow
- Copy
  - Note Text
  - Author PubKey
  - Note ID
- Share (opens usual share dialog, sends to snort)
- Block & Hide User
- Report
  - Spam / Scam
  - Hateful speech
  - Impersonation
  - Nudity / Porn
  - Illegal Behavior

I know it's more taps but you can't have *everything* within 1 tap when we need so many options. And we do need them IMO, but the goal is to make it intuitive so that it doesn't “feel” complicated.

**Comment by maxmoney21m** [comment]
@vitorpamplona I was thinking we could use a more "action menu" style for the long click on a note, and have different options to whatever is in the 3-dots dropdown. Here is a concept:

![image](https://user-images.githubusercontent.com/124794312/223515939-c7267d7e-5c86-4ffb-99dd-9932380f9248.png)

The actual buttons and icons should be chosen more carefully, of course.

I have seen some apps do this before where there is a "Select" action that opens the text in a plain text viewer for using the normal system select & copy tools. It's slightly clunky, but it works when the actual content is complicated (as in this case with multiple `Text`s).

What do you think about this concept, and if you like it, what would you like to see in the action menu popup (long click) vs. the 3 dots dropdown?

**Comment by vitorpamplona** [comment]
I hate DropDown menus, so this is def better. The question is will it fit width-wise on most small screens? I had some issues with the Zap button already...

**Comment by maxmoney21m** [comment]
Right now it's 64 x 4 = 256 dp. Small screens are typically at least 320 dp, so it should be fine. (In theory we can check the screen size and shrink if needed, but probably not worth it to start with.)
