### ISSUE TITLE
[Localization] Russian localization update

### ISSUE THREAD

**Issue by LeonusDH** [vitorpamplona/amethyst#733]
If I want to update the Russian localization, do I just need to send a **Pull request**,
or is there something like **crowdin** to add the language?
If I need to send via **PR**, do I need to send to a specific branch or can I send to main?

**Comment by vitorpamplona** [comment]
You can send it via https://crowdin.com/project/amethyst-social

Don't forget to add your npub in your profile so that I can tag you on releases.

**Comment by LeonusDH** [comment]
Thanks

**Comment by LeonusDH** [comment]
> You can send it via https://crowdin.com/project/amethyst-social
> 
> Don't forget to add your npub in your profile so that I can tag you on releases.

Where exactly in the profile do I need to add npub?

**Comment by vitorpamplona** [comment]
In the description
