### ISSUE TITLE
[FEATURE] Ability to customize media upload servers

### ISSUE THREAD

**Issue by xeruf** [vitorpamplona/amethyst#734]
**Is your feature request related to a problem? Please describe.**
Thanks for the push for NIP-96, highly appreciate it!
I want to self-host nostrcheck or void.cat so I can conveniently upload media files to my own server, not depending on external services. Amethyst is already compatible with these, but does not seem to allow customizing the server URL without recompiling

**Describe the solution you'd like**
Ability to add own media hosting server, maybe by choosing an existing API compatibility.

**Comment by xeruf** [comment]
This would really be a great step for decentralization :)

**Comment by KotlinGeekDev** [comment]
This is definitely an interesting feature. Seems feasible. Please what do you think, @vitorpamplona ?

**Comment by KotlinGeekDev** [comment]
Please @xeruf do you still need this? Thanks.

**Comment by davotoula** [comment]
Yes please! A really missing feature imo

**Comment by KotlinGeekDev** [comment]
So we will need to add it in the Settings page. Now the question is if it will replace the current default list, or just be added to it.

**Comment by KotlinGeekDev** [comment]
PLease what do you think @davotoula @vitorpamplona ?

**Comment by KotlinGeekDev** [comment]
So @vitorpamplona based on [this change](https://github.com/vitorpamplona/amethyst/commit/ff94f45d0414a8bcb59621f082fff0e7f8353fdf) you made, we will just invoke sendFileServersList() when the user adds a custom NIP96 server.

**Comment by vitorpamplona** [comment]
Yeah. It could be very similar to how we edit relays right now.

**Comment by KotlinGeekDev** [comment]
> Yeah. It could be very similar to how we edit relays right now.

Yeah.

**Comment by KotlinGeekDev** [comment]
@vitorpamplona I wonder how it could be called in the drawer menu. 'Media Upload', 'Media sharing'?

**Comment by vitorpamplona** [comment]
"Media Servers" can be a good caption.

**Comment by KotlinGeekDev** [comment]
> "Media Servers" can be a good caption.

:+1:

**Comment by KotlinGeekDev** [comment]
@vitorpamplona I also wonder if it should be a global setting or an account-based one.

**Comment by davotoula** [comment]
Account based? Personally I could be using two different organisation or company profiles. Or one personal and one corporate?

**Comment by KotlinGeekDev** [comment]
> Account based? Personally I could be using two different organisation or company profiles. Or one personal and one corporate?

Interesting...

**Comment by KotlinGeekDev** [comment]
If we go with global settings, we will need to use Shared preferences, which complicates things, due to the servers having a name and a URL, except if I use @vitorpamplona 's way of storing it as JSON.

**Comment by vitorpamplona** [comment]
It should be per account to fill in kind 10096 as requested by NIP-96. Kind 10096 then can be used as the options in the server choice on upload dialogs. 

We can later add some helper to pre-fill multiple accounts in the same device.

**Comment by KotlinGeekDev** [comment]
> It should be per account to fill in kind 10096 as requested by NIP-96. Kind 10096 then can be used as the options in the server choice on upload dialogs.
> 
> We can later add some helper to pre-fill multiple accounts in the same device.

Got it. :+1:

**Comment by KotlinGeekDev** [comment]
@vitorpamplona it therefore means we need to modify the fileServer in Account to take in a list instead of one, right?

**Comment by vitorpamplona** [comment]
> @vitorpamplona it therefore means we need to modify the fileServer in Account to take in a list instead of one, right?

No, that is just the "default" server form the list of server the user has. The app logs the last used server in that field. 

Basically, you are trying to replace the Nip96MediaServers.DEFAULT list by the Account.getFileServersList()

**Comment by KotlinGeekDev** [comment]
> 
> No, that is just the "default" server form the list of server the user has. The app logs the last used server in that field.

I see.
> 
> Basically, you are trying to replace the Nip96MediaServers.DEFAULT list by the Account.getFileServersList()

Yeah, and use the Default list as a fallback.

**Comment by KotlinGeekDev** [comment]
Still one question remains: How do we save the labels the user gives to the different servers, assuming there are several of them? There doesn't seem to be a way to save them, since the default list is hard-coded and the app just reads that.
cc @vitorpamplona
