### ISSUE TITLE
[BUG] Bookmarks not loading

### ISSUE THREAD

**Issue by sclewis90** [vitorpamplona/amethyst#747]
**Describe the bug**
Private and public bookmarks do not load

**To Reproduce**
1. Go to profile icon
2. Click on bookmarks
3. Scroll to Private or Public
4. See error (bookmarks do not appear/load)

**Expected behavior**
I have bookmarked various posta and expected to see them appear under Private and Public Bookmarks

**Video and Screenshots**

**Device (please complete the following information):**
 - Phone Brand/Model [e.g. Pixel 7 Pro]: pixel 7 pro
 - Android Version [e.g. 33]: 14
 - App Version [e.g. v0.20.3]: 0.83.7

**Bounty (in Bitcoin sats) offered for a solution**

**Comment by davotoula** [comment]
Can you provide a screenshot of your relays?

**Comment by sclewis90** [comment]
Not long after i posted this to github, my public bookmarka began to show. I did not change the relays or anything

Feb 3, 2024, 7:33 AM by ***@***.***:

**Comment by davotoula** [comment]
Glad to hear that. Can you please close this bug?
