### ISSUE TITLE
[FEATURE] auto-save note draft as I'm typing

### ISSUE THREAD

**Issue by alltheseas** [vitorpamplona/amethyst#748]
**Is your feature request related to a problem? Please describe.**

App crashes when I'm midway through typing a longer note. I lose my draft, and have to start over again! 

https://njump.me/note1hwkv2e2sxu9kkmqymh7la4ze0rr2ccjkp55nme73ew5ncfxuyyas9xaxn8

**Describe the solution you'd like**
Auto-save note as I'm typing.

If Amethyst crashes, note should be auto saved as a draft.

If I navigate away from the compose note view, note should be auto saved as a draft. 

Draft note should be easily findable.

**Bounty (in Bitcoin sats) offered for the implementation**
1,000,000 SATS

**Additional context**
Posted by Vic npub1yx6pjypd4r7qh2gysjhvjd9l2km6hnm4amdnjyjw3467fy05rf0qfp7kza

https://njump.me/note1hwkv2e2sxu9kkmqymh7la4ze0rr2ccjkp55nme73ew5ncfxuyyas9xaxn8

**Comment by alltheseas** [comment]
@vicariousdrama

**Comment by alltheseas** [comment]
https://damus.io/note1y9hvgpm409fjlmvsd8qflcg3gvmvrlmfhgksghwa9g3y448g3ljq0wta4z

**Comment by vicariousdrama** [comment]
This feature has been implemented and the bounty on this feature has been paid

**Comment by vitorpamplona** [comment]
Thank you, @vicariousdrama!
