### ISSUE TITLE
[FEATURE/BUG] Use ws:// instead of wss:// when connecting to Relays over Tor to an .onion address

### ISSUE THREAD

**Issue by mrusme** [vitorpamplona/amethyst#760]
**Is your feature request related to a problem? Please describe.**
Right now it seems like Amethyst is solely using SSL encrypted Websocket connections for Relays. However, given the baked-in encryption of the Tor network, connections to .onion addresses should be fine to use plain websockets.

**Describe the solution you'd like**
Amethyst should recognize that the address is a .onion address and switch to ws:// in that case.

**Comment by vitorpamplona** [comment]
Hum.. the app should take in ws:// addresses. Does it work if you insert with the scheme?

**Comment by mrusme** [comment]
When entering only the onion address I get the following error:

```
Failed to reach wss://xyz.onion: SOCKS: Connection refused
```

When entering the address with a ws:// prefix it appears to be respecting that and showing me the same error but with `ws://` prefixed (which appears to be a server-side issue — however the protocol seems correct).

**Comment by KotlinGeekDev** [comment]
Hello @mrusme . Please is the issue solved for you then?

**Comment by mrusme** [comment]
@KotlinGeekDev well, since it can be fixed by manually prefixing `ws://`, it can be regarded as resolved. However, as it is unclear to the regular user that the URL must be prefixed like that, you might want to leave this open to at least implement some hint about this somewhere, or, ideally, fix it so that Amethyst recognizes Onion addresses and automatically performs the prefixing.

Please decide what is the best way to proceed and act on this issue accordingly. :-)

**Comment by KotlinGeekDev** [comment]
> @KotlinGeekDev well, since it can be fixed by manually prefixing `ws://`, it can be regarded as resolved. However, as it is unclear to the regular user that the URL must be prefixed like that, you might want to leave this open to at least implement some hint about this somewhere, or, ideally, fix it so that Amethyst recognizes Onion addresses and automatically performs the prefixing.
> 
> Please decide what is the best way to proceed and act on this issue accordingly. :-)

I see.
