### ISSUE TITLE
Can't see messages sent by individual

### ISSUE THREAD

**Issue by maybeLn** [vitorpamplona/amethyst#78]
Testing v0.13.0 version today, the mobile app can no longer display any information sent by individuals。
The web version can display private chat, Notes, and group chat messages sent by yourself。
How to solve this problem?

**Comment by vitorpamplona** [comment]
So, you don't see any post from anybody else?

**Comment by maybeLn** [comment]
can't see my own

**Comment by vitorpamplona** [comment]
They should be in your profile. We removed them from the feed to make the experience cleaner. Do you want it back?

**Comment by maybeLn** [comment]
I clicked refresh, but it didn't work, it kept showing Feed is empty.

**Comment by maybeLn** [comment]
The new version can see its own message，Thanks
