### ISSUE TITLE
Add a way to unboost a boosted note

### ISSUE THREAD

**Issue by ameya-dubey** [vitorpamplona/amethyst#79]
Seems like currently, there's no way to unboost a boosted note. I accidentally boosted a note, and when I clicked on the green highlighted boost button again, it reboosted it instead of unboosting it. I feel like the behaviour here should be to unboost it instead of reboosting it.

**Comment by vitorpamplona** [comment]
There is no reliable way to delete events in the Nostr protocol. We can send a delete event, but frankly, it doesn't mean much. Once you posted, liked, or reported, it's for life.

**Comment by ameya-dubey** [comment]
That seems like a huge disadvantage for a protocol where the user is supposed to have more control over their content! Anyway, thank you for responding and clarifying the issue.

**Comment by vitorpamplona** [comment]
Agree. Any protocol that uses signed messages has this issue. Once you sign something and gets shared, it's signed forever. It's different, but not very different than just sending things to a website. On the website model, you are at the mercy of the website owner. On Nostr, there is no owner, but there is also no delete.

**Comment by ameya-dubey** [comment]
P.S. So I managed to send some delete event requests via a cli tool, and while the client does honour these requests, I can still see the original events when listed via the same cli tool 😬
