### ISSUE TITLE
How to disbale auto translation？ 

### ISSUE THREAD

**Issue by ablegao** [vitorpamplona/amethyst#80]

**Comment by vitorpamplona** [comment]
No way at the moment. May I ask what makes you want to disable it?

**Comment by ablegao** [comment]
Translation error and I can't learn other languages

**Comment by vitorpamplona** [comment]
Interesting.. Are you interested in seeing the raw content of all other languages or just a few? Do we want a complete disable or just a list of languages you don't want to translate?

**Comment by ablegao** [comment]
all other languages,translate a particular one if necessary

**Comment by ablegao** [comment]
Recently I am curious about the language of Israel, and sometimes I read Japanese.  word is very interesting

**Comment by vitorpamplona** [comment]
So, if you add those languages to Android's System languages  (Settings/System/Languages and Input) the app will not translate from those. 

For me: I have Portuguese and English as system languages so the app doesn't translate from those. But I need translations from everything else.

**Comment by ablegao** [comment]
Okey

**Comment by skyerjoe** [comment]
Why i have to add an system language 
To deactivate  an feature in an app ?
Thats makes no Sense in imho

**Comment by vitorpamplona** [comment]
The idea is the same that other apps use: It doesn't translate the languages you use. 

But an option is coming.

**Comment by skyerjoe** [comment]
And thats the Problem cause on some devices ur not able to add multiple languages.

**Comment by skyerjoe** [comment]
> But an option is coming.

👍
