### ISSUE TITLE
Kind 1 edits aren't a good idea

### ISSUE THREAD

**Issue by basantagoswami** [vitorpamplona/amethyst#801]
Feel free to close this issue, but I strongly feel that introducing edits for kind 1 posts will lead to things that we don't want for nostr. Also Amethyst has a big market share and introducing new things without the dev communities approval can be seen as a hostile move.

This [post on nostr](https://njump.com/note1x3qwe5jewuhzsgtava20m4tn23ecsrerc5cgepf929cjuhwn5y7sq24960) by [Leserin](https://njump.com/npub1m4ny6hjqzepn4rxknuq94c2gpqzr29ufkkw7ttcxyak7v43n6vvsajc2jl) reflects my thoughts, so I'm gonna just copy paste it below:

1) Human speech is not machine code. It doesn't need to compile and run dynamically. It has no merge conflicts.
It doesn't need git. Not everything needs git.

2) Small errors and invented words allow speech to naturally evolve, over time. That is one way that vocabulary expands and adapts to the current time and environment, and it fuels a sense of community to share this "new, local vocabulary".

3) It also encourages more people to write, as they know that their errors or local dialects will be glossed over and the readers will focus on their core message.

4) If someone worries about typos, let them use a client with a spell-check. (I'm sure the people implementing note-policing also took the time to implement a spell-check, right?)

5) Not everything needs to be a "community-approved idea". Novel or controversial ideas are often offensive. Offensive people are often creative and ingenuitive. Those individuals also have free speech rights and should be allowed to speak their truth freely, without being harrassed.

6) Debates have value. Replying to an idea, rather than demanding it be rewritten, creates a conversation in the public square, and allows people who are being harrassed and intimidated to be defended by their friends. Much wickedness occurs in darkness.

7) Kind 01 notes were the universal note and all clients were designed to specialize in their display. Changing that dynamic shouldn't be a spontaneous, unilateral decision by a large provider. Which is why I have left that provider, for wantonly abusing a market position.

8) Do not offer a doorway to tyrannical impulses. That door will always be opened. We have all come to know that software developers can become tyrants. That is why we are here.

9) Merely because it has become technologically possible to do something, doesn't mean that other clients or users are forced to accept it. Expect there to be "free speech clients" and "anti-forker filters" coming soon, and those feeds will contain different displays of notes than on the conformist apps.

10) Again: This is the original note. There is no other version of this note and there will not be another version.

**Comment by vitorpamplona** [comment]
> we don't want for nostr

Who is "we"? 

> Not everything needs to be a "community-approved idea". Novel or controversial ideas are often offensive. Offensive people are often creative and ingenuitive. Those individuals also have free speech rights and should be allowed to speak their truth freely, without being harrassed.

If you truly believe this, and since it seems clear that you consider edits an "offensive idea", aren't you trying to shutdown the same freedom you are trying to defend?
