### ISSUE TITLE
Translatable ?

### ISSUE THREAD

**Issue by mondlicht-und-sterne** [vitorpamplona/amethyst#816]
Is this app translatable ?

**Comment by vitorpamplona** [comment]
yep, we use Crowdin to translate: https://crowdin.com/project/amethyst-social

**Comment by mondlicht-und-sterne** [comment]
Had I (translationfoss on crowdin) already made an enquiry ?
Do you have to do this for every language ?

**Comment by mondlicht-und-sterne** [comment]
It looks like I can translate.
