### ISSUE TITLE
[FEATURE] Ability to disable TTS buttons

### ISSUE THREAD

**Issue by TekkadanPlays** [vitorpamplona/amethyst#817]
While the Text-To-Speech features within Amethyst are appreciated, it would also be appreciated to be able to disable this setting entirely. Personally it's inevitable that I accidentally tap them while doomscrolling my Nostr feed. They can be very loud and disruptive.

**Comment by vitorpamplona** [comment]
We just moved them to the profile page. It will be there on the next version.
