### ISSUE TITLE
[BUG] webp files not displaying

### ISSUE THREAD

**Issue by NotGovernor** [vitorpamplona/amethyst#830]
**Describe the bug**

**To Reproduce**
Use a link to a webp image:
```
![[files/FileName.webp]]
```

**Expected behavior**
It displays the image the same as other image file types.

**Actual behavior**
Currently, it just displays a link to the file that doesn't work.

**Comment by davotoula** [comment]
What device and os are you using?

What was the exact url of the webp? Maybe there was a server issue preventing the webp loading. 

Url without http will not display automatically I believe. 

Webp displaying fine on my pixel 7 pro...

**Comment by NotGovernor** [comment]
windows linux and android

Exact URL was in OP.

Server is fine. Other file types work.

URL without https works for jpgs and all other links. IE: `![[files/SomeImage.jpg]]`


Perhaps webp needs to be added to the ALLOWED_FILE_LINK_TYPES environment variable in the docker compose file? Is it not in with the defaults? I'll have to give that a try soon.

**Comment by davotoula** [comment]
Wrong amethyst repo?

**Comment by NotGovernor** [comment]
JFC. Wrong project entirely. Please heap shame upon my family for at least 2 generations and delete this. Sorry.
