### ISSUE TITLE
Bug: Wrong relai number

### ISSUE THREAD

**Issue by f321x** [vitorpamplona/amethyst#89]
I have set up 8 relays but when I scroll my feed the relai number in the top right randomly switches to 18/19 relais, in the relai list window I still have my set up relais. Don't know if it really connects to 19 relais or if it is just a ui bug.

V0.13.1
Android 13, Pixel 6a, GrapheneOS

**Comment by vitorpamplona** [comment]
What's your pubkey so that we can test?

**Comment by f321x** [comment]
npub1z9n5ktfjrlpyywds9t7ljekr9cm9jjnzs27h702te5fy8p2c4dgs5zvycf

**Comment by vitorpamplona** [comment]
This has been fixed a while back. Apologies for the lack of communication
