### ISSUE TITLE
Umbrel Private Relay 

### ISSUE THREAD

**Issue by craigderington** [vitorpamplona/amethyst#91]
I'm using the new Umbrel private relay (nostr-rs-relay).  I have my Amethyst client relay list configured with my private relay address.  This address is only prefixed with ws://<address> and not a secure web socket.  All of my activity in the Amethyst app creates errors on this private relay.  It worked as expected when I initially saved the new relay, then started failing.

**Comment by vitorpamplona** [comment]
Amethyst will force it to be a secure connection. So wss is forced for now when you edit your relay list in the app. 

Other clients might have similar restrictions.

**Comment by craigderington** [comment]
Yeah I noticed it appended the string with the secure socket.  Thanks for your reply.

**Comment by mayankchhabra** [comment]
@vitorpamplona it'd be great if you can add `ws://` support to Amethyst so it can connect to local relays, such as the one on Umbrel. We're getting lots of requests from users who want to connect Amethyst to their relay on Umbrel. Damus recently updated their client to support it too: https://github.com/damus-io/damus/issues/344 and https://github.com/damus-io/damus/pull/383. Keep up the great work!!

**Comment by lukechilds** [comment]
Also @vitorpamplona just to add some more context, when connecting to a private relay on Umbrel users are either connecting directly over the local network or remotely via WireGuard (Tailscale). So although it's plaintext `ws://` from the apps perspective no insecure communication is happening over untrusted networks. It's either all local local plaintext, or if remotely then WireGaurd is providing an encrypted tunnel over the public internet.

**Comment by vitorpamplona** [comment]
Is this issue only when adding relays through Amathyst settings? Does it work when you add them in another interface? 

Because I don't think we actively block the connection if the relay list is already setup in another platform. Unless we have a bug somewhere.

**Comment by craigderington** [comment]
Yes, I am using Amethyst with my private relay.  When I initially added the private relay to amethyst when viewed in another client it appeared like this.  wss://was://
