### ISSUE TITLE
Give some suggestions to the developers about spam.

### ISSUE THREAD

**Issue by godslayer1904** [vitorpamplona/amethyst#92]
It is suggested that developers develop keyword screening function for each client as soon as possible, allowing users to personalize the comments of major channel and global according to their own needs, and directly refuse to display information related to spam.

**Comment by godslayer1904** [comment]
Personally, it is unrealistic and impossible to put an end to spam by paying relay alone. First of all, this violates the original intention of decentralized anti-censorship. Relay operators will arrange the ban rules at will according to their own preferences and call it spam prevention. In addition, paid relay will also prevent users from exploring this social app, making it difficult to establish the ecology of this software and compete with centralized social apps like Twitter, weibo.

**Comment by godslayer1904** [comment]
I hope developers can face up to this problem. I am very optimistic about the prospect of this app, and I also hope that one day people all over the world can live together under one community and be free from the restrictions on people's freedom of speech by governments like CCP. The people of China are looking forward to this day.

**Comment by vitorpamplona** [comment]
But then the app must download ALL the spam to filter it locally. Its a huge waste of data plan. :(

**Comment by godslayer1904** [comment]
Simplicity and ease of use are the core competitiveness of social media. We Geek can spend time studying it, but those who are busy with their livelihood on weekdays are not as diligent as we are.

**Comment by godslayer1904** [comment]
But we can also do this: we can send the keyword blocking information of
spam to the relay node, and let the relay node exercise the right of
censorship instead of us.

Vitor Pamplona ***@***.***> 于 2023年2月7日周二 11:58写道：

**Comment by vitorpamplona** [comment]
I think our current filters are taking care of the worst spam quite well these days.. Closing this issue for now.
