### ISSUE TITLE
When I scroll the screen is too twitchy, unpleasant and uncomfortable, disgusting, so impossible to use

### ISSUE THREAD

**Issue by Wjxfi** [vitorpamplona/amethyst#924]
When I scroll the screen is too twitchy, unpleasant and uncomfortable, disgusting, so impossible to use

poco x3 pro

**Comment by vitorpamplona** [comment]
Let's hope this will make things better: https://github.com/vitorpamplona/amethyst/commit/e18945b3787db99744bce908a1eef663bafcd994

**Comment by vitorpamplona** [comment]
Can you check if version 0.88.0, on the performance mode (left drawer/Settings) makes it work better?

**Comment by vitorpamplona** [comment]
Please check if the [Release v0.88.2](https://github.com/vitorpamplona/amethyst/releases/tag/v0.88.2) fixes it
