### ISSUE TITLE
Restore Default Relay Values [Feature Request]

### ISSUE THREAD

**Issue by alltheseas** [vitorpamplona/amethyst#93]
## User Story ##

As an Amethyst user who is looking to experiment with relays, I would like the capability to reset relays to Amethyst default values, so that I can have greater confidence in tinkering with relays.

### Acceptance Criteria ###
1. In relay view, there is an icon and/or option titled "Restore default relay settings".
2. If option is clicked, a modal is displayed "Are you sure you want to restore default relay settings? You will lose your current relay settings."
3. If user clicks yes, then Amethyst restores the default relay settings.

_User Feedback_
"_`Vitor or anyone else who can share some knowledge. I can't figure out how to restore the default relay list on amethyst, help is appreciated lol`_"
https://iris.to/#/post/note1092um4jjflk4jwfmrc0f6euy2jjych4z0ekx5mtz0u2v03px2xxsvafxlp

**Comment by vitorpamplona** [comment]
It makes sense. We might need a bigger screen or a new design, though. It's quite ugly right now already.

**Comment by vitorpamplona** [comment]
This was implemented a few months ago.
