### ISSUE TITLE
[BUG] crash on app start v0.88.1

### ISSUE THREAD

**Issue by Hagbard89** [vitorpamplona/amethyst#932]
The app crashes at start since i updated to 0.88.1

Im on Graphene OS, Pixel 6, Android 14

**Comment by vitorpamplona** [comment]
Did you go from .87.x to 0.88.1 or from 0.88.0 to 0.88.1?

**Comment by qubenix** [comment]
I'm also experiencing this crash. I went from 0.88.0 to 0.88.1 which had no issue, but then my phone did an update to One UI 6.1 and that broke the app. I'm on a S22, Android 14.

**Comment by vitorpamplona** [comment]
Can you check if 0.88.2 fixes it?

**Comment by Hagbard89** [comment]
> Did you go from .87.x to 0.88.1 or from 0.88.0 to 0.88.1?

I updated fron 0.88.0 to 0.88.1

**Comment by Hagbard89** [comment]
> Can you check if 0.88.2 fixes it? I just released it

It's fixed in 0.88.2! 👍

**Comment by vitorpamplona** [comment]
Nice!
