### ISSUE TITLE
[BUG] crashes every time ncryptsec and password entered

### ISSUE THREAD

**Issue by watou** [vitorpamplona/amethyst#950]
**Describe the bug**
Trying to add ncryptsec and its password crash 0.88.4 every time. Using with my npub no problem.

**To Reproduce**
1. Paste ncryptsec string
2. Paste password 
3. Tick box
4. Press Login button 
5. After spinner spins for a fraction of a second inside button, app crashes.

**Expected behavior**
Login without incident.

**Device:**
 - Phone Brand/Model: Xiaomi Mi Note 11
 - Android Version: MIUI Global 14.0.4.0(TGKEUXM)
 - App Version: 0.88.4-PLAY

**Comment by watou** [comment]
The problem is still present in v0.88.6-FDROID.

**Comment by vitorpamplona** [comment]
Yeah, I am trying to figure out a way to replicate it. Looks like it works fine here. It might be something in your particular key that creates this. 

Was it working before?

**Comment by watou** [comment]
> Was it working before?

I'm a new user, bringing over my password and ncryptsec from gossip running on both MacOS Intel and Ubuntu ARM.
I am happy to install a debug build that can log a stack trace or any clear text I can share with you. Thanks for your efforts.

**Comment by KotlinGeekDev** [comment]
Hmm, can't reproduce this as well.

**Comment by watou** [comment]
On 0.88.7-FROID with Developer settings changed to always show crash dialog.
![Screenshot_2024-06-29-21-19-58-246_com miui bugreport](https://github.com/vitorpamplona/amethyst/assets/3008217/40ead464-e824-4b63-9a4d-a1e7af74e6e9)

**Comment by watou** [comment]
This OOM error tracks with Gossip's default/minimum Encrypted Private Key scrypt N=18 which requires 256MiB per [this doc](https://nips.nostr.com/49). But how to get Android to cough up enough heap memory for the decryption?

**Comment by vitorpamplona** [comment]
Yeah, that's not going to work on most phones. Try decreasing N=16 or so.

**Comment by watou** [comment]
> Try decreasing N=16 or so.

I'll have to convince the Gossip developer to make that a possibility, as the slider doesn't go lower than 18, meaning that Gossip users can't become Amethyst users without moving secret keys in plaintext.  Oh well!  Thanks for your time.

**Comment by watou** [comment]
One last observation: gossip does not recognise an ncryptsec+password exported out of Amethyst, so there is effectively no credential sharing between these two clients in either direction.

**Comment by KotlinGeekDev** [comment]
> One last observation: gossip does not recognise an ncryptsec+password exported out of Amethyst, so there is effectively no credential sharing between these two clients in either direction.

Interesting observation. Is it due to different requirements for desktops and mobile phones? No idea. cc @vitorpamplona
