### ISSUE TITLE
[BUG] App freezes when opening the dm screen

### ISSUE THREAD

**Issue by greenart7c3** [vitorpamplona/amethyst#951]
**Describe the bug**
App freezes when opening the dm screen

**To Reproduce**
1. Open the app
2. Press the dm screen icon
3. The app freezes

**Expected behavior**

**Video and Screenshots**

**Device (please complete the following information):**

**Bounty (in Bitcoin sats) offered for a solution**

**Comment by vitorpamplona** [comment]
Super strange. Just on your user?

**Comment by greenart7c3** [comment]
Yes, tried with other account and it loads normally

**Comment by greenart7c3** [comment]
I think I found the problem. I'm in the 0xchat public chat and someone posted a huge base64

**Comment by greenart7c3** [comment]
nostr:nevent1qqswccrr8ly99aqe2hr7fvpdasgguhn2lx9spyx8z5dhfvxgu7fkpsgpz4mhxue69uhhyetvv9ujuerpd46hxtnfduhsyg8lds4tcx0f662pstqexekdmk2zw70hk4nsw6kj45q3lfvrnsrkrgpsgqqqqq4q0e7hkq
