### ISSUE TITLE
Relay Settings Redesign [UI]

### ISSUE THREAD

**Issue by alltheseas** [vitorpamplona/amethyst#96]
How might the relay settings menu be redesigned. 

A few things that stand out
-home, dm, global, followers/following icons are too small
-it may not be clear what all these icons mean to the user - how might this be communicated to the amethyst user?
-information is data heavy, and not (think typical social media) user friendly. how might we separate relay settings vs. relay performance performance (for instance, simplifying up/down/error to red light / green light?)
-red delete icon stands out. can delete option be shifted to a hidden hold tap menu option?
-might some of these settings be hidden under an "advanced" toggle?

![amethystrelayshmw](https://user-images.githubusercontent.com/64376233/217313138-07c3f69b-f9f1-4fcd-93b3-e5cc8e26c208.png)

See related feature request Restore Default Relay Values #93.

**Comment by braydonf** [comment]
> it may not be clear what all these icons mean to the user 

It wasn't clear to me what the icons meant until I asked. A legend with text may help or just the use of text and then toggles.

**Comment by maxmoney21m** [comment]
How about a small question mark button next to Cancel, which displays the legend and some info in a popup?

**Comment by vitorpamplona** [comment]
Closing this for now since it is based on our old UI.
