### ISSUE TITLE
[BUG] sensitive content auto reveals 

### ISSUE THREAD

**Issue by davotoula** [vitorpamplona/amethyst#964]
**Describe the bug**

**To Reproduce**
1. Go to #buttsr 
2. Scroll down the feed 
3. Sensitive content warning flashes quickly but then the image loads and shows 

**Expected behavior**
I would expect the sensitive content warning to show and stay until it's clicked 

**Video and Screenshots**
Not appropriate 

**Device (please complete the following information):**
 - Phone Brand/Model Pixel 7 Pro 
 - Android Version 14
 - App Version 88.7, Google play

**Comment by KotlinGeekDev** [comment]
Interesting. Please does this also happen on the F-Droid version?(I suspect so).

**Comment by KotlinGeekDev** [comment]
Please @davotoula I don't know if this still occurs on the latest version.

**Comment by davotoula** [comment]
Trying now

**Comment by davotoula** [comment]
Still weird. On version 89.7.

Sensitive content posts unhinde automatically and then dissappear to a thin grey line.

10+ sensitive content notes in a row create a thicker grey bar.

Old behaviour was sensitive content notes remained in the feed and I was able to click individually on the notes to reveal them.

**Comment by davotoula** [comment]
Has this been moved to some global setting?

Trying with a different user now...

**Comment by davotoula** [comment]
I see. Using a different account the issue is not there.

Sensitive content behaves like it used to.

Any suggestions for further troubleshooting?

**Comment by davotoula** [comment]
Could it be relay dependant? Maybe a relay is marking NSFW content as spam or blocked somehow?

**Comment by vitorpamplona** [comment]
It maybe an old setting. Do you want to try logging off (or erasing the local data / uninstalling and installing Amethyst) and try again?

**Comment by davotoula** [comment]
Deleting app data fixed it. Thanks
