### ISSUE TITLE
[BUG] grey bar in feed

### ISSUE THREAD

**Issue by davotoula** [vitorpamplona/amethyst#965]
**Describe the bug**
Since 2 or 3 versions ago the feed occasionally has a 3-30px high grey bar. 

I think it could be related to auto hiding content (spam, sensitive content) 

**Expected behavior**
No grey bars in feed. If content is hidden then it should not leave any UI artifacts behind. 

**Video and Screenshots**
![17198181211561.png](https://github.com/vitorpamplona/amethyst/assets/1747287/9ea2f0e7-2293-46b2-8f78-932d00ad995b)

**Device (please complete the following information):**
 - Phone Brand/Model Pixel 7 Pro (also visible in emulator) 
 - Android Version 14
 - App Version 88.7

**Comment by vitorpamplona** [comment]
That's like 20 hidden posts in sequence. :(

**Comment by davotoula** [comment]
I see. Maybe it's a good/intentional UI clue that posts were hidden?

**Comment by davotoula** [comment]
As designed. Won't fix
