### ISSUE TITLE
Invalid private key[BUG]

### ISSUE THREAD

**Issue by SuziLily** [vitorpamplona/amethyst#969]
Had issues with Amethyst..(crashing).. Reinstalled it and now can't get in with my private key.. Tried some other nostr clients same thing.. It shows me some mistake with the letter b in my key..
Heelppppp.... Please...
I hope I am putting this issue on a right place.. 
Thanks a lot in advance.

**Comment by vitorpamplona** [comment]
Did you have a backup of your key somewhere? It starts with nsec***

**Comment by SuziLily** [comment]
Yes.. I have it saved.. Did this many times in a year.. Dont know what is going on.. I trust you.. I can send it to you if you tell me the safe way..

**Comment by vitorpamplona** [comment]
No, you shouldn't send it to anyone. What's your public key? I can see if the issue is on your profile somewhere.

**Comment by SuziLily** [comment]
I know but I am desperate.. 😢
Here is my public
npub1cpg5tqql4fwgyddxejwyq3lxezxrjxxfmta6xlmhgfhhdl6ffdkqpdy4rt
c05145801faa5c8235a6cc9c4047e6c88c3918c9dafba37f77426f76ff494b6c

**Comment by vitorpamplona** [comment]
Hum.. public seems fine. Did you try logging with the nsec into any other client? 

On Amethyst does it crash before or after loading the feed?

**Comment by SuziLily** [comment]
Vitor.. I did it..
It works now... 
Oh thanks god... 
Sorry for bothering... 
Thank you so much.. Don't know what went wrong or you have done some miracle.. 😀

**Comment by SuziLily** [comment]
Sorry didn't see your answer before I wrote..
The same mistake was on other clients..
This is strange.. Saved my peivate on 2 places..Copy paste from one of them didn't work..even though each sign is the same..


For crashing.. It happens often to me on Huawei.. So I often have to reinstall Amethyst.. It crashes when loading app..

**Comment by SuziLily** [comment]
Should I delete all above or what..
I am an idiot..
No Vitor it doesn't work..
I copy pasted public key.. For God sake what I am doing..

**Comment by vitorpamplona** [comment]
I am confused. Did it work or not?

Which other clients did you try logging in with your nsec?

**Comment by SuziLily** [comment]
It doesn't work.. Sorry.. I copy pasted public again and thought I managed but when I tried to send you a message there I figured out what I did..
Please sorry..
I tried Iris..it post this message there on login
![Screenshot_20240703_042118_com android chrome](https://github.com/vitorpamplona/amethyst/assets/174564166/a079d14c-3b94-4f83-8dc6-905d89ab3573)

**Comment by vitorpamplona** [comment]
Interesting. Is there any b's in the nsec? It should have.

**Comment by SuziLily** [comment]
Yes there are 3 I think..

**Comment by vitorpamplona** [comment]
Ok, either this is not an nsec or some b's appeared out of nowhere in there. 

Does it start with nsec1, like this? 

nsec196fjs9c3s2q5ddhlw5d9qkerptykntm2krfavn7s7cc9twnqxchqqy32ju

**Comment by vitorpamplona** [comment]
Nsec1 always have 63 chars. 

As an option, this is a hex representation: 

2e93281711828146b6ff751a505b230ac969af6ab0d3d64fd0f63055ba60362e

This one has B's but it doesn't start with nsec1

**Comment by SuziLily** [comment]
Yes it does..
Do you want me to copy paste some part of it?

**Comment by SuziLily** [comment]
I had to do to log in and out many times in the past year.. I always used the same one.. Have no others.. And there were no issues with that till now.. Had to update.. It didn't go via apk.. So had to reinstall Amethyst.. It was crashing I reinstalled again and since then this issue came out..

**Comment by vitorpamplona** [comment]
How many characters does your nsec key have in total?

**Comment by SuziLily** [comment]
I just have sent you a message there.. If you can see it.just let me know so that I can leave you alone with loads of sorry sorry sorry and thank you for your time..
