### ISSUE TITLE
[BUG] Amethyst crashes when opening a profile

### ISSUE THREAD

**Issue by jooray** [vitorpamplona/amethyst#989]
**Describe the bug**
I go to this profile:

npub1q9mfvl56uje98qklyk32q3cekp4ex8mljfx0zd2qkxcqv8n0gu0qk73vv7

And Amethyst 0.89.5 from F-Droid running on GrapheneOS crashes.

**Device (please complete the following information):**
 - Phone Brand/Model [e.g. Pixel 7 Pro]: Pixel Fold
 - Android Version [e.g. 33]: GrapheneOS [2024071600](https://grapheneos.org/releases#2024071600)
 - App Version [e.g. v0.20.3]: 0.89.5

**Log:**

[Error in Amethyst c79a30386240.txt](https://github.com/user-attachments/files/16325524/Error.in.Amethyst.c79a30386240.txt)

**Comment by vitorpamplona** [comment]
Fixed on https://github.com/vitorpamplona/amethyst/commit/5a60c3a595869fc9b85ccc6655e3222b30cdfd19
